### ISSUE TITLE
check-ttf.py: "Font contains magic code in PREP table?"

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1005]
Hello,

We have `magiccode = "\xb8\x01\xff\x85\xb0\x04\x8d"`, I'm assuming this is something ttfautohint inserts or why is this needed?

My fonts which have been run through ttfautohint all fail this test.

Cheers,
Marc

**Comment by felipesanches** [comment]
This magiccode check was added to fontbakery prior to my involvement in the development. As it lacks inline documentation in the source, I have just put the effort to manually disassemble this tiny snippet of TrueType instructions bytecode in order to figure out what does it do. Here's what I figured out, based on the instruction set documentation available at https://www.microsoft.com/typography/otspec/ttinst.htm:

```python
    magiccode = "\xb8\x01\xff" + \ # PUSHW 0x01FF
                "\x85" + \         # SCANCTRL (unconditinally turn on
                                   #           dropout control mode)
                "\xb0\x04" + \     # PUSHB 0x04
                "\x8d"             # SCANTYPE (enable smart dropout control)

    # Smart dropout control means activating rules 1, 2 and 5:
    # Rule 1: If a pixel’s center falls within the glyph outline,
    #         that pixel is turned on.
    # Rule 2: If a contour falls exactly on a pixel’s center,
    #         that pixel is turned on.
    # Rule 5: If a scan line between two adjacent pixel centers 
    #         (either vertical or horizontal) is intersected
    #         by both an on-Transition contour and an off-Transition
    #         contour and neither of the pixels was already turned on
    #         by rules 1 and 2, turn on the pixel which is closer to
    #         the midpoint between the on-Transition contour and
    #         off-Transition contour. This is “Smart” dropout control.
```

**Comment by felipesanches** [comment]
I used ttx to inspect the prep table of Merriweather-Black.ttf and the block of truetype instructions is a bit larger than this check expects to see. But I could find this in the middle of the Merriweather-Black routines:

```
      PUSHW[ ]  /* 1 value pushed */
      511
      SCANCTRL[ ]       /* ScanConversionControl */
      PUSHB[ ]  /* 1 value pushed */
      4
      SCANTYPE[ ]       /* ScanType */
```

which is effectively what the check is expecting to find (please not that 511 is the decimal representation of 0x1FF).

So instead of expecting it to be exactly equal, maybe we should check if this tiny snippet of code is at least present in the middle of the tested font prep table bytecode.

**Comment by felipesanches** [comment]
Regarding "why this is needed?" maybe @davelab6 could clarify that to us here. I can trace it back to commit c30b7981 by @vitalyvolkov on January 2015, but it could be a bit older.

**Comment by felipesanches** [comment]
@m4rc1e I have just fixed the check to detect the presence of the expected snippet inside a larger chunk of bytecode,

**Comment by m4rc1e** [comment]
Ah cool.

But still, what exactly is the purpose of this test. To check whether there is a prep table?

**Comment by anthrotype** [comment]
it's a minimal PREP table for enabling dropout control, useful to improving rendering for unhinted TTFs:

See @davelab6 comment at: https://github.com/googlefonts/fontbakery/issues/890#issuecomment-236450011

and my comment here:
https://github.com/googlefonts/fontbakery/issues/890#issuecomment-236457209

**Comment by felipesanches** [comment]
From the O'Reilly book "Fonts and Encodings" by Yannis Haralambous:

```
The tables fpgm and prep contain global TrueType instructions (which, therefore, are not
attached to any specific glyph). These instructions are executed when the first glyph in the
active font is typeset (for fpgm) and every time the type size or the current transformation
matrix is changed (for prep).
```

**Comment by felipesanches** [comment]
@m4rc1e I've just merged it into master now. Let me know if the check still fails for your font projects

**Comment by m4rc1e** [comment]
Thanks folks, that's much clearer.

The comment is great.

surely dropout_control is a much more suitable variable name than magiccode

**Comment by felipesanches** [comment]
well... it was a kind of magic when it was undocumented :-P

**Comment by m4rc1e** [comment]
Fabulous.

`INFO     OK: Font contains magic code in 'prep' table`

Thanks for this,
I've done some more fixes throughout today. I will send you a pr with those in a few hours.

Cheers,
Marc

**Comment by felipesanches** [comment]
cool, thanks.
