### ISSUE TITLE
ftxvalidator availability

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1060]
I'm using usually GNU/Linux as my development machine. `ftxvalidator` is a Mac-only tool.

I wrote a small drop in replacement script for `ftxvalidator`, if there's a remote OSX available via `ssh` this can be used. 

https://gist.github.com/graphicore/a83eeb8829ba64a628c8872092910515

So, if your roomate has a mac and you don't, you might convince him to give you ssh credentials ;-)

It's a start at least.

 * * * 

@davelab6 added these tasks to be resolved before closing, from the discussion below

- [x] Mention this helper script in fontbakery README.md
- [x] Add the ftxvalidator-over-ssh helper script to FB repo
- [x] Replace `remotefile=/tmp/$base` with `remotefile=/tmp/$base-$$`

**Comment by felipesanches** [comment]
Is this really an issue?

**Comment by felipesanches** [comment]
maybe a better issue description here could be "Mention this helper script in fontbakery README.md" or even "Add ftxvalidator-over-ssh helper script to FB repo".

**Comment by felipesanches** [comment]
@graphicore can you clarify what are your expectations regarding this issue?

**Comment by HinTak** [comment]
A small suggestion for improvement: prepend the remote name with $$ (process-id) or date-stamp, to enable parallel running and avoid collision.

**Comment by davelab6** [comment]
I would like to get this fully integrated, because it is inherently useful for people like @felipesanches and @graphicore who are not running on Mac OS X directly (which is exceedingly rare...)

**Comment by davelab6** [comment]
@HinTak thanks for the tip!

**Comment by felipesanches** [comment]
A quick though: Can ftxvalidator run on a docker container ?

**Comment by felipesanches** [comment]
@davelab6 

Based on what I learned so far, it seems docker is tightly attached to very specific Linux calls. Unless someone come up with either a native-OSX docker... Which maybe what's stated in this article https://www.theregister.co.uk/2016/06/20/docker_os_x_windows_beta_orchestration/ when it says "The OS X client uses Apple's builtin hypervisor framework – yeah, Apple quietly embedded a hypervisor API in its desktop operating system. Previously, you had to use Docker with Oracle's VirtualBox".

Anyway, I doubt Google would offer an OSX node on container-engine. (I may be proven wrong though).

In the end, ftxvalidator being non-free turned out to be more than just a big concern for a software freedom "purist" like me. We're seeing here an actual roadblock to get this integrated into the fontbakery web-dashboard running on Google Docker Engine.

**Comment by davelab6** [comment]
Yep forget ftx for now.

**Comment by HinTak** [comment]
Since Mac OS X runs under kvm, I have always wonder whether it is

**Comment by davelab6** [comment]
@graphicore is this still working in the rewrite?

**Comment by HinTak** [comment]
Well, I mentioned that I built part of FontVal 2.1.1 in Ubuntu docker containers from Fedora, so I have experience setting up docker services and running docker clients, though only for a few weeks :) . Yes, I think @graphicore 's script should work inside a Linux docker as is. It requires just an ssh client, AFAIC, which is very minimal.

If my suggestion was not clear, I meant replacing `remotefile=/tmp/$base` with `remotefile=/tmp/$base-$$` . `$$` means the current process id - since process ids are largely unique - at least, it is unique while your shell is running your script! - this allows you to run multiple instances of the script in parallel from the same host or docker container. Assuming the other end, or end(s) can accept them in parallel.

**Comment by davelab6** [comment]
@HinTak thanks for your suggestions :) @graphicore said offline,

> that makes sense when we have a local runner with parallel execution mode; for from-the clould calls, we would likely implement it differently, but still with a `ftxvalidator` drop in replacement... probably some rpc call to a dedicated ftxvalidator service machine, but we could do it still this way.

I added some tasks at the top of the issue

**Comment by graphicore** [comment]
I wonder where to put the script `prebuilt/workarounds/ftxvalidator/ssh-implementation/ftxvalidator`?

**Comment by felipesanches** [comment]
> I wonder where to put the script prebuilt/workarounds/ftxvalidator/ssh-implementation/ftxvalidator? 

Looks reasonable. I'd omit the ``workarounds`` subdirectory, though.

Can you please add it to the repo, @graphicore ?

**Comment by davelab6** [comment]
Reassigning this to @felipesanches now he has access to macOS to test.
