### ISSUE TITLE
Plan the Collection Web Dashboard

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1158]
Per https://github.com/googlefonts/fontbakery/blob/34af3080054d3d332858d65c42486cb5eb2eabc3/BRIEF.md#33-web-dashboard in order to plan the Collection Dashboard, @felipesanches will...

- [ ] Write a document proposing the technical approach to testing fonts in each place, and storing the results of the tests from each place
- [ ] Propose a new UI for the fontbakery.appspot.com checker

**Comment by felipesanches** [comment]
Thanks, @davelab6 !

**Comment by felipesanches** [comment]
This is a list of 104 URLs of git repos with font projects that I extracted from the description files on the google/fonts repo. @davelab6, which of these would you like to monitor in a dashboard?

Yes, it could be them all, but let's say, is there a selection of something like 10 of these that you'd like to see in a first prototype of the dashboard?

I'll probably fork them into my own github account so that I can test travis scripts on my forks as if I were the designers.

github.com/10four/Bhavuka
github.com/adobe-fonts/adobe-blank
github.com/adobe/source-serif-pro
github.com/alefalefalef/Varela-Round-Hebrew/
github.com/alexeiva/poiretone
github.com/andrestelex/sarala
github.com/andrew-paglinawan/QuicksandFamily
github.com/anexasajoop/cambay
github.com/antonxheight/Ranga
github.com/appajid/dhurjati
github.com/appajid/gidugu
github.com/appajid/gurajada
github.com/appajid/lakkireddy
github.com/appajid/mallanna
github.com/appajid/mandali
github.com/appajid/nats
github.com/appajid/ntr
github.com/appajid/peddana
github.com/appajid/ponnala
github.com/appajid/ramabhadra
github.com/appajid/ramaraja
github.com/appajid/raviprakash
github.com/appajid/sreekrushnadevaraya
github.com/appajid/suranna
github.com/appajid/suravaram
github.com/appajid/tenaliramakrishna
github.com/appajid/timmana
github.com/cadsondemak/chonburi
github.com/cadsondemak/itim
github.com/cadsondemak/kanit
github.com/cadsondemak/sriracha
github.com/CaroGiovagnoli/sura
github.com/CatharsisFonts/Cormorant
github.com/christiannaths/Redacted-Font
github.com/clauseggers/Inknut-Antiqua
github.com/cyrealtype/Adamina
github.com/cyrealtype/Alike
github.com/cyrealtype/Federant
github.com/cyrealtype/Sumana
github.com/DunwichType/RhodiumLibre
github.com/EbenSorkin/Asar
github.com/EbenSorkin/Atomic-Age
github.com/EbenSorkin/Basic
github.com/EbenSorkin/Dekko
github.com/EbenSorkin/Fruktur
github.com/EbenSorkin/Kavoon
github.com/EbenSorkin/Merriweather-Sans
github.com/EbenSorkin/Varta
github.com/elms-/Dinah
github.com/erinmclaughlin/Khula
github.com/erinmclaughlin/Yantramanav
github.com/etunni/Amita
github.com/etunni/Arya/
github.com/etunni/glegoo
github.com/etunni/kurale
github.com/figs-lab/datalegreya
github.com/girish-dalvi/Baloo
github.com/girish-dalvi/Ek-Mukta
github.com/girish-dalvi/Modak
github.com/googlefonts/Homenaje
github.com/googlefonts/LatoGFVersion
github.com/impallari/Cabin
github.com/impallari/Raleway/
github.com/itfoundry/hind-colombo
github.com/itfoundry/hind-guntur
github.com/itfoundry/hind-jalandhar
github.com/itfoundry/hind-kochi
github.com/itfoundry/hind-madurai
github.com/itfoundry/hind-mysuru
github.com/itfoundry/hind-siliguri
github.com/itfoundry/hind-vadodara
github.com/itfoundry/kalam
github.com/itfoundry/khand
github.com/itfoundry/poppins
github.com/itfoundry/rozhaone
github.com/itfoundry/tillana
github.com/juandelperal/sahitya
github.com/mooniak/abhaya-libre-font
github.com/motaitalic/vesper-libre
github.com/mozilla/Fira
github.com/Neelakash/sitara
github.com/Omnibus-Type
github.com/Omnibus-Type/Jaldi
github.com/Omnibus-Type/PragatiNarrow
github.com/ossobuffo/jura
github.com/rosettatype/Eczar
github.com/s-a/digital-numbers-font
github.com/silnrsi/font-padauk
github.com/simoncozens/silson
github.com/solmatas/Kadwa
github.com/TiroTypeworks/Slabo
github.com/typeoff/biryani
github.com/typeoff/martel
github.com/typeoff/martel_sans
github.com/VanillaandCream/Catamaran
github.com/VanillaandCream/Palanquin
github.com/vernnobile/anaheimFont
github.com/vernnobile/CodaFont
github.com/vernnobile/Cutive
github.com/vernnobile/CutiveFont
github.com/vernnobile/CutiveFont/
github.com/vernnobile/DhyanaFont
github.com/vernnobile/mondaFont
github.com/vernnobile/MondaFont
github.com/vernnobile/TrocchiFont
github.com/weiweihuanghuang/Work-Sans

**Comment by felipesanches** [comment]
Also... for now we're only going to be able to deal with repos that host TTF binaries. Picking one at random, like https://github.com/appajid/ntr I can see that it only stores UFOs, so that's not going to be supported.

I can look at each of these one by one and see which ones host TTF binaries. I'm only asking because perhaps you already know the answer by heart. :-)

**Comment by davelab6** [comment]
On Jan 19, 2017 9:13 PM, "Felipe Corrêa da Silva Sanches" <
notifications@github.com> wrote:


github.com/10four/Bhavuka


Fontforge project



github.com/adobe/source-serif-pro


Adobe project


github.com/cadsondemak/itim
github.com/cadsondemak/kanit
github.com/cadsondemak/sriracha


Glyphs messier projects



github.com/CatharsisFonts/Cormorant

Big big project



github.com/cyrealtype/Adamina
github.com/cyrealtype/Alike
github.com/cyrealtype/Federant
github.com/cyrealtype/Sumana

github.com/weiweihuanghuang/Work-Sans



These are perfectly normal

**Comment by felipesanches** [comment]
done
