### ISSUE TITLE
check-ttf.py: ERROR: usWeightClass from 275 to 200 (on an ExtraLight font)

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1186]
## Expected behaviour
I expect the ExtraLight to pass when it has a weight value of 275. Our [name spec](https://docs.google.com/spreadsheets/d/1ckHigO7kRxbm9ZGVQwJ6QJG_HjV_l_IRWJ_xeWnTSBg/edit#gid=0) specifies this 275 value.

## Observed behaviour
`ERROR    OS/2 usWeightClass matches weight specified at METADATA.pb Changes that must be applied to this font: OS/2 usWeightClass from 275 to 200`

## How to replicate
Run an ExtraLight font through FB. [Rokkit](https://github.com/m4rc1e/RokkittFont) is a good choice

We're now very close to eliminating all the false positives :-)

**Comment by davelab6** [comment]
yes this is a bug, os/2 table differs from css for 100 and 200 but otherwise match

**Comment by felipesanches** [comment]
[name space](https://docs.google.com/spreadsheets/d/1ckHigO7kRxbm9ZGVQwJ6QJG_HjV_l_IRWJ_xeWnTSBg/edit#gid=0) says:

**CFF.Weight OS/2.usWeightClass:**
> "Value must be 250 or above, because Windows GDI will autobold fonts with a value of 249 or below, and must not be 901 or above. Some font vendors recommend using steps of 50, but we require ExtraLight to be set to 275 so that sorting styles by Weight Class gives a logical order. Regular must be 400, Bold must be 700. Also note that these values are not related to stem widths"

**Comment by davelab6** [comment]
@felipesanches right. Marc says when he runs an ExtraLight font through fb (like Rokkit) it suggested to him to change usWeightClass from 275 to 200... which would not be a good suggestion.

**Comment by felipesanches** [comment]
got it! I'll make it better then :=)

**Comment by felipesanches** [comment]
hmmm.... I get a good result when checking agains Rokkit here with latest master:

>     {
        "description": "Checking OS/2 usWeightClass",
        "log_messages": [
            "OS/2 usWeightClass value looks good!"
        ],
        "result": "OK",
        "target": "data/test/rokkit/Rokkitt-ExtraLight.ttf"
    },

I also see that since march 2016 we have the 275 value for ExtraLight at https://github.com/googlefonts/fontbakery/blob/a5732fb25fef0ff638b44154b225b58eb8e37dc7/fontbakery-check-ttf.py#L80

Which is indeed what is actualy used on the check at: https://github.com/googlefonts/fontbakery/blob/a5732fb25fef0ff638b44154b225b58eb8e37dc7/fontbakery-check-ttf.py#L1229

Maybe @m4rc1e is using an old fontbakery version? Or maybe it's something else... any idea, Marc? Could you please re-check that you still get an error with the latest master branch code?

cheers,
Felipe

**Comment by m4rc1e** [comment]
Alright, I just reran Rokkit-ExtraLight.ttf through FB. The issue is gone.

I probably had an older version of FB.

Closing
