### ISSUE TITLE
add module for shared functions/constants

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1204]
We're producing many functions and constants which could be shared amongst the different scripts.

We should probably bundle these into a single .py module.

The downside to this is we cannot share individual scripts anymore. However, it will cut down on duplication.

@davelab6 @felipesanches thoughts?

**Comment by davelab6** [comment]
Fb used to be more sophisticated and it actually was more hindrance than
help. I like the fact these are stand alone scripts that can be emailed
around and just work. Our target users are irredeemably unsophisticated

**Comment by davelab6** [comment]
With Python script and command line stuff. Their expertise isbon drawing
great letterforms. This is unlikely to change across the type community.

**Comment by felipesanches** [comment]
I frequently think of moving things to external modules, but as @davelab6 pointed out, keeping the scripts stand-alone is currently understood as a product requirement.

**Comment by anthrotype** [comment]
well, if I look at the long list of install requirements in the README, it doesn't seem to me that the fontbakery scripts are much "stand-alone"...

If you want to make it easy for users to install fontbakery, then you could package it with things like pyinstaller so they get something truly standalone (not even python would be required).

Anyway, I don't really use the tool, so you can ignore my comments. :)

**Comment by davelab6** [comment]
@anthrotype all the 3rd party packages (except fonttools) are optional, everything runs fine without them yet with merely reduced functionality

**Comment by davelab6** [comment]
The project has had a high amount of churn in the last years, so packaging wasn't ideal; I preferred that people run from git master always

**Comment by davelab6** [comment]
I guess my recommendation is that @m4rc1e create a branch and go to town and I'll review it and see if I think it is simple enough that its ok :)

**Comment by felipesanches** [comment]
nice! :-)

**Comment by felipesanches** [comment]
@davelab6 and @m4rc1e I think that with the consolidation of the containerized version of the fontbakery dashboard (and soon merging the drag-n-drop feature into container-engine as well) well soon not have to worry so much about the underlying code being single-scripts for easily passing around to designers. That's because I think most designers will prefer to use the web dashboard and/or drag-n-drop. So only developers (or some sporadic hardcore dev/designer) will be fiddling with the actual python scripts.

@m4rc1e If you wish to attempt separating common code into external modules, I'll be happy to review a pull request. Otherwise I'll leave this for later if I ever tackle this myself.

**Comment by davelab6** [comment]
The GF eng team have an active request on this so I'm moving this to the 0.2.0 milestone

**Comment by felipesanches** [comment]
OK, I'll do it then.
