### ISSUE TITLE
Dashboard: Enable setting it up to run checks on other collections of font families

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1286]
Since we can now see the health of the whole collection, how about we allow the dashboard to look at different forks? This will give us the ability to see if a pr will improve the collection before we merge.

I'm working on a collection wide hotfix, https://github.com/google/fonts/issues/641. This would be incredibly useful.

**Comment by felipesanches** [comment]
Yes, I agree.

There are some challenges to achieve that, though.

The current implementation of the worker container involves checking out the last N commits of the full git repo of an upstream project and it expects to have a single family per repo. Multiple families in a single repo are handled by having multiple entries on the fontprojects.csv for the same repo, with differing font_prefix values. Loading up additional containers and re-cloning the repo is not so bad since the full size of the upstream font project repos tend to not be very large.

Dealing with the google/fonts git repo (or forks of it) is trickier since that repo is huge! A different approach would be needed for this. We might try fetching raw files from the Github repo via HTTP requests? I tend to dislike this approach.

**Comment by m4rc1e** [comment]
I understand this is no small task.

so the current [implementation](http://35.184.229.186) currently runs on upstream repos or downloadable families from fonts.google.com?

**Comment by davelab6** [comment]
We probably should have more persistent containers, so that the cloned git
repo isn't lost on each run

**Comment by felipesanches** [comment]
A general mechanism for configuring the dashboard is the CSV file on the dispatcher container. If someone needs to setup the dashboard to monitor a different set of families, that can be achieved by providing a different CSV file. But for that, each family must be hosted in its own git repo.

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383
