### ISSUE TITLE
Dashboard: Enable HinTak's MS FontVal

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1297]
MS-FontVal is not currently running on the worker container.

#1270

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383

**Comment by davelab6** [comment]
How is this a dashboard issue?

On Jun 21, 2017 7:22 PM, "Felipe Corrêa da Silva Sanches" <
notifications@github.com> wrote:

Migrating to fontbakery-dashboard issue tracker per #1383
<https://github.com/googlefonts/fontbakery/issues/1383>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlefonts/fontbakery/issues/1297#issuecomment-310232091>,
or mute the thread

**Comment by felipesanches** [comment]
Docker infrastructure is much closer related to FB-dashboard then to FB-core.

**Comment by davelab6** [comment]
> Docker infrastructure is much closely related to FB-dashboard than to FB-core.

I agree, will close out all FontVal issues from this repo's tracker
