### ISSUE TITLE
Minor suggestion for status bar

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1376]
## Observed behaviour

Running FB from the command line, I see a progression indication, but the Progress Bar is missing context of where the end of the bar is. I see:

`........E..E.E.....`

then

`........E..E.E.....WW.E.E..E.................E.W....EEEEEEEE`

and so on, until finally
  `.......E..E.E.....WW.E.E..E.................E.W....EEEEEEEEEEEEEE.E.EEE..IEI.....E.EW......W......S..EW...................W...S..........`
 
## Expected behaviour

But I would expect:

```
[........E..E.E.....                                                                                                                       ]
```

then

```
[........E..E.E.....WW.E.E..E.................E.W....EEEEEEEE                                                                              ]
```

and so on, until finally

```
[........E..E.E.....WW.E.E..E.................E.W....EEEEEEEEEEEEEE.E.EEE..IEI.....E.EW......W......S..EW...................W...S..........]
```

## Resources and exact process needed to replicate

    $ cd directory_with_font_files/;
    $ fontbakery check-ttf *ttf;

**Comment by felipesanches** [comment]
With the current implementation, the check-ttf script has no knowledge of the total number of checks before actually running them, so providing this context, while desirable, it not trivial. I'm not sure if @graphicore new architecture proposal may provide means to compute that total before running the checks, but that would be a good thing to take into consideration. Otherwise, the total number would have to be hardcoded to the script, which would likely lead to a mismatch in the future if we forget to always update the hardcoded value. (So I'm strongly against hardcoding it.)

**Comment by davelab6** [comment]
I agree; but given the checks are numbered, I'm confused about why fb can not `len()` them

**Comment by graphicore** [comment]
> I'm not sure if @graphicore new architecture proposal may provide means to compute that total before running the checks

Will be totally possible :-)

**Comment by graphicore** [comment]
> I'm confused about why fb can not len() them

Because `fontbakry-check-ttf.py` calls each checks explicitly. That's why we need a test-runner.

**Comment by felipesanches** [comment]
We can't len() them because they're not a list. The checks are currently invoked in a procedural manner, which is at the core of what Lasse is currently addressing.

I'm happy to postpone this until we review and merge Lasse's refactor.

**Comment by davelab6** [comment]
Okay great :)

**Comment by davelab6** [comment]
@felipesanches I guess this can be closed as the rewrite implements a fancy new status bar

**Comment by felipesanches** [comment]
Yep! :-D
