### ISSUE TITLE
[new-arch] merge @register_condition and @condition into a single decorator ?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1411]
Could we replace this with a single **@condition** decorator that does the job of both? 
```
@register_condition
@condition
```

**Comment by graphicore** [comment]
It's possible, but it also hides a lot of the actual action. I'm not sure yet.

Also, we'd need to make sure that the arguments for the two tasks don't clash, which may become a bit fiddly in the long run. Now,  `@register_condition` has an optional `name` as a keyword argument (default is `condition.name`) and `FontBakeryCondition` also has an optional `name` argument (default is `func.__name__`). The `name` argument of `@register_condition` exists so that one can reuse conditions in other specs with a way to avoid name clashes with the rest of the namespace. Similarly `FontBakeryCondition` is so that we can use existing function that do the right thing but have a bad __name__ (It's also used to print the condition via `__repr__`). I'm not sure what's best in this case, there's a (small) semantic gap between the two `name` args, we may have to rename the `@register_condition` argument if we want to unify.

The other thing is, that I find it quite tiring to wrap my head around the two styles of python decorators (with and without arguments) and put it together in one function. But that could be overcome.
