### ISSUE TITLE
[new-arch] How to specify explicit skip messages due to unmet conditions ?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1422]
See: https://github.com/googlefonts/fontbakery/pull/1419/files/f706952d2c7c5cd74d5d2249e17757927a5dc3e7#r126024754

There I said:
> Is a condition understood as "falsy" if its value is an empty list ?
> 
> In some places we need to explicitely skip because we want to provide a feedback message to the user explaining why it was skipped. Alternatively we could perhaps declare in the condition code what message to be displayed whenever the condition is false.

Let's continue this discussion here.

**Comment by graphicore** [comment]
yes, everything that is falsy in python is also falsy as a condition.

e.g.:

```py
>>> bool([])
False
>>> not []
True
>>> not not []
False
>>> 

```


> In some places we need to explicitely skip

I don't understand, how do we implicitly skip? We have output like this for a test skipped because of unmet conditions:

```
>> com.google.fonts/test/064 with ((u'font[0]', '../barcodelibre/fonts/LibreBarcode39Text-Regular.ttf'),)
   Is there a caret position declared for every ligature?
 * SKIP: Unfulfilled Conditions: ligatures

   Result: SKIP
```

> Alternatively we could perhaps declare in the condition code what message to be displayed whenever the condition is false.


We could easily print the `description` of the condition if available, the decorator is able to take one:

```py
@register_condition
@condition(description="A dict containing all ligatures of the font.)
def ligatures(ttFont):
  all_ligatures = {}
  if "GSUB" in ttFont:
    for lookup in ttFont["GSUB"].table.LookupList.Lookup:
      ...
  return all_ligatures
```
(BTW, that one would be nice to have a doc-string as well, I didn't understand the structure of the returned `all_ligatures` just now, but it looks bogus to me.)

but in this case, an even more verbose solution would be to add:

```py
@register_condition
@condition(description="True if the font has ligatures, otherwise false.")
def has_ligatures(ligatures):
  return bool(ligatures)
```

Because we want to provide a feedback message to the user explaining why it was skipped, could be formatted like:

```
>> com.google.fonts/test/064 with ((u'font[0]', '../barcodelibre/fonts/LibreBarcode39Text-Regular.ttf'),)
   Is there a caret position declared for every ligature?
 * SKIP: Unfulfilled Conditions:
             has_ligatures: True if the font has ligatures, otherwise false.

   Result: SKIP
```

I also think you can yield a `SKIP` within a test already. From the original example just remove the `conditions=[]` part. Instead of (old):

```py
@register_test
@test(
    id='com.google.fonts/test/048'
  , conditions=['missing_whitespace_chars']
)
def check_font_has_proper_whitespace_glyph_names(ttFont,
                                                 missing_whitespace_chars):
  """Font has **proper** whitespace glyph names?"""
  if missing_whitespace_chars != []:
    yield SKIP, "Because some whitespace glyphs are missing. Fix that before!"
  elif ttFont['post'].formatType == 3.0:
    yield SKIP, "Font has version 3 post table."
```

If you want to make this, even though `missing_whitespace_chars` is empty do:

```py
@register_test
@test(
    id='com.google.fonts/test/048'
)
def check_font_has_proper_whitespace_glyph_names(ttFont,
                                                 missing_whitespace_chars):
```

There's absolutely no reason to have a `conditions` declaration if you want to read the value in any case.

The rest of the body could start like this, if you are serious with the `SKIP` status

```py
  """Font has **proper** whitespace glyph names?"""
  if not missing_whitespace_chars:
    yield SKIP, "Because some whitespace glyphs are missing. Fix that before!"
    return
  if ttFont['post'].formatType == 3.0:
    yield SKIP, "Font has version 3 post table."
    return
```
after that you don't need the extra `else` block and its indentation (I prefer that style, early exit let's me focus on what's left to do)

**Comment by davelab6** [comment]
@felipesanches can this be closed?

**Comment by felipesanches** [comment]
yes!
