### ISSUE TITLE
New script: which characters in a TTF are not in any GF `.nam` subset?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1466]
Please provide a script to tell us which characters in a TTF are not in any GF `.nam` subset.

**Comment by graphicore** [comment]
For this kind of task it would be **really** great to have the fonts/tools directory as a stand alone module. Because what you are asking for creates a dependency to the fonts repository and every other workaround is a bit of a hack.

Should I file this as an request issue in https://github.com/google/fonts? I'm sure there are some other stakeholders with an opinion and I think it should be tackled.

**Comment by graphicore** [comment]
When I say module, I also really think it should be a stand alone github repository. Everything that needs to read these nam files basically needs code from there. We already have some copy and paste job somewhere in pyfontaine and there's also [graphicore/googleFontsTools](https://github.com/graphicore/googleFontsTools) which is a mess to keep in sync, but used for  [specimentTools](https://github.com/graphicore/specimenTools/tree/languages/build) and much less in size than the google/fonts repository. 

These things happen because we don't want to download thousands of fonts, just to read some nam files.

The new repository could be a git submodule of google/fonts.

**Comment by felipesanches** [comment]
I fully support Lasse's proposal.

**Comment by davelab6** [comment]
> is a mess to keep in sync

However, google/fonts.git/tools is rarely updated, so I'm happy to use https://github.com/graphicore/googleFontsTools for now

**Comment by davelab6** [comment]
This is now urgent - @felipesanches could you do it this week? :)

Now the https://github.com/googlefonts/tools/ repo exists :)

**Comment by felipesanches** [comment]
@davelab6 said:

> To solve google/fonts#1285 I need a small script that will compare all the characters in all the fonts in the GF repo against the bunch of GF subsets, and against the bunch of glyph sets, and tell us what characters and not in each bunch :)

**Comment by felipesanches** [comment]
I'll close this here, since it is now tracked at the googlefonts/tools issue tracker.
