### ISSUE TITLE
[new arch] Update README to reflect new fontbakery check-googlefonts CLI

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1470]
Currently the readme just replaces `fontbakery check-ttf` by `fontbakery check-googlefonts`. But the command line interface changed.

This would also be a good moment to find out what options are missing from the new interface.

Also, new possibilities, like the following, should be documented:

Run one check for all fonts in the google/fonts repository

    $ fontbakery check-googlefonts -c com.google.fonts/test/044 -n \
    -l FAIL path/to/fonts/{apache,ofl}/*/*.ttf

**Comment by felipesanches** [comment]
It seems to me that this command line for running the same test on all fonts in the google/fonts repository would only work for single-font tests. It would probably lead to bad results for family-tests because it would treat all thousands of font files as belonging to a single family.

Also, even for single-font tests this is a bit problematic since we are flooded by 2 thousand summaries like these, which makes the actual log messages hard to reach in the text-terminal buffer:

![screenshot at 2017-08-03 10 55 53](https://user-images.githubusercontent.com/213676/28925130-591b2d2c-783a-11e7-9808-e1733ec7d6ad.png)

**Comment by graphicore** [comment]
> It seems to me that this command line for running the same test on all fonts in the google/fonts repository would only work for single-font tests.

Yes, I suggest to use `-c` and only pick a handful of tests to rum for many fonts. Otherwise this is not very useful anyways. Running 150 test for 2000 fonts wont help you but just flood you with too much results.

This option is useful if you e.g. add a new test and want to explore how the whole library behaves.

> It would probably lead to bad results for family-tests because it would treat all thousands of font files as belonging to a single family.

That's right. Do we need a `--no-family-tests` switch? I rather suggest not to select tests that expect a family. Why would you want to do that anyways?

> 2 thousand summaries like these,

I will make these summaries optional and configurable. It's similar to the clustering option that we need if we want to order "by test then by font", instead of "by font then by test" what we do now.

**Comment by graphicore** [comment]
see also #1471
