### ISSUE TITLE
Check: Combined length of family and style name must not exceed 20 characters

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1488]
https://glyphsapp.com/tutorials/multiple-masters-part-3-setting-up-instances says

> Keep your style name short to avoid problems in Windows. How short? Well, you are on the safe side if the combined length of family and style name does not exceed 20 characters. If the name is too long, Windows may think the font is invalid.

![screen shot 2017-08-04 at 11 41 33](https://user-images.githubusercontent.com/261579/28975951-fff66cae-7909-11e7-8d9e-5d47bbd0c74a.png)

**Comment by anthrotype** [comment]
somebody with access to Windows should make some tests and confirm that this is the case.

**Comment by anthrotype** [comment]
cc @moyogo

**Comment by jenskutilek** [comment]
I don't think this is true. Even the examples in [the name table spec](https://docs.microsoft.com/en-us/typography/opentype/spec/name) show names where the length of ids 1 + 2 exceeds 20 characters.

From reading [this discussion](http://typedrawers.com/discussion/617/family-name/p2) I think there is confusion with the ID1 and ID2 limits, and the real issue is that the length of ID4 must be < 32 characters, while ID4 = ID1 + " " + ID2. That's also what I remember from the FontFont production guidelines.
