### ISSUE TITLE
Set up PyUp.io  to keep requirements.txt updated

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1523]
Set up https://pyup.io to keep https://github.com/googlefonts/fontbakery/blob/master/requirements.txt updated

**Comment by felipesanches** [comment]
I don't see why we should have requirements.txt at all.

Here's my rationale:
* running `python setup.py install` on our development code on the git repo installs every dependency described on setup.py
* a user installing the package with `pip install fontbakery` will also get all the same dependencies installed from PyPI packages
* so where would a `requirements.txt` file be actually needed ?
* if there's no explicit need for it, aren't we potentially shooting on our feet by keeping a separate/redundant mechanism for declaring out dependencies ?

I fear I may be missing something obvious here, so please let me know if that's the case...

**Comment by davelab6** [comment]
https://caremad.io/posts/2013/07/setup-vs-requirement/ explains nicely

**Comment by felipesanches** [comment]
Thanks for the article. I brought the requirements.txt back into the repo (I had removed it earlier today)

**Comment by felipesanches** [comment]
I'm still a bit puzzled though. I don't see in which case we're supposed to actually use the requirements file.

It surely is not ideal to be used by end users as they'll lack direct access to the requirements file for explicitly invoking something like `pip install -r requirements.txt`. The ned users will pip install and that will trigger the installation of whatever dependency packages from pypi are available based on those abstract package names listed on setup.py

If we don't enforce that users must necessarily use the exact same versions of dependency packages that we're using during development, then it seems silly/naive that we're precious about keeping track of the versions we're using for testing. I don't see what tool or technology ties together the setup of the end user environment and the one used by developers.

**Comment by felipesanches** [comment]
I moved this into the next milestone (0.3.4) because I feel this will require (pun intended) further discussion.

**Comment by anthrotype** [comment]
> I don't see in which case we're supposed to actually use the requirements file.

the PyPA recommendation is that "libraries" should use setup.py with abstract requirements, "applications" should use requirements.txt with concrete requirements. Applications in that context usually means a piece of code that is deployed to production, like a web application uploaded to a server.
Sometimes the distinction is blurry. I guess fontbakery is a bit of both now.

So, if you wish to use PyPI as a means to "deploy" your application (even though its primary intent would be to provide a way to distribute libraries), then you could set the install_requires in setup.py with concrete requirements.
However, if you also want users to be able to use fontbakery as a library, you wouldn't want to set the setup.py install_requires too strictly because that makes it harder to specify as dependency alongside other packages.

I think that, even if the requirements.txt will only be used for setting up the environment where fontbakery runs its self test suite, it is still good to keep (along with a system like pyup.io that periodically auto-updates and re-run the tests with updated dependencies), as this will ensure that the test runs are deterministic and don't depend on whatever version of a dependency happens to be available at that moment.

**Comment by felipesanches** [comment]
Thanks, @anthrotype ! That clarifies a lot ;-)

**Comment by felipesanches** [comment]
This is scary, though!

![screenshot at 2017-11-07 09 24 42](https://user-images.githubusercontent.com/213676/32491375-9c642422-c39d-11e7-8ea4-74e9d6425fda.png)

**Comment by anthrotype** [comment]
yes, it needs to create new branches and open merge requests...
it's fine! :)

**Comment by felipesanches** [comment]
Why can't they create branches on a fork on their bot's own account and perform a pull request like any other user would ?

The `fork => feature-branch => commit => pull-request` work-flow is designed to allow decentralized contributions not requiring this kind of invasive proposal.

**Comment by felipesanches** [comment]
I also dislike that it seems to be all-or-nothing. I only have the option of giving them **read and write** access to **all** my public repos, or none at all.

**Comment by anthrotype** [comment]
It's just a api key that you can always revoke. It's used by thousands of projects. Anyway, you can always update the requirements.txt yourself manually from time to time if you prefer. It's not that you have security-related dependencies that you must keep up-to-date.

**Comment by felipesanches** [comment]
yeah. I guess it's against their own interest to sneakily mess with their users repos.

But I'm against that kind of practice on principle. I won't blindly grant write access to my personal repos (or to googlefonts repos) to any thirdparty.
