### ISSUE TITLE
https://fontbakery.appspot.com/ - 500 error response on upload

### ISSUE THREAD

**Issue by peterp** [googlefonts/fontbakery#1545]
I'm not sure if this is the correct place to report this issue, but the website is no longer working.

1. I select 1, or more, font files and click "run the tests"
2. a dialog appears for a few seconds
3. nothing happens, but this error is logged in the console.

<img width="1121" alt="screen shot 2017-08-23 at 17 34 12" src="https://user-images.githubusercontent.com/44849/29624467-728fdcf4-8829-11e7-8e95-88338f735f3a.png">

**Comment by felipesanches** [comment]
The web app is no longer supported. We're working on a new / upgraded version of it at https://github.com/googlefonts/fontbakery-dashboard/ but that is not live yet.

The only practical tool available and up-to-date at the moment is the command-line interface. You can install it locally and use it by following the install and usage instructions on README.md

**Comment by peterp** [comment]
Ok, great, I've followed the installation instructions, but the `brew install ots --HEAD` command no longer installs properly. I've created an issue on `bramstein/webfonttools` so hopefully that's resolved at some point.

**Comment by felipesanches** [comment]
thanks, Peter!

**Comment by felipesanches** [comment]
Font Bakery will work even if you do not install ots. It will simply skip running the ots checker in that case, but the other tests will be available. Same is true for cases like the fontforge-based tests. Let us know if anything crashes for you due to lacking dependencies. Font Bakery is currently being developed with the goal of not having hard dependencies (except for the very basic stuff), but graciously skipping tests instead.
