### ISSUE TITLE
Check and warn or fail for font-v versioning

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1563]
I think the source foundry are doing great stuff in support of the Hack project and I hope more future projects :)

https://github.com/source-foundry/font-v is their latest tool:

- reports all platformID x nameID 5 tables for ttf/otf

- modifies version string number at the command line/in scripts

- git commit sha1 short hash digest stamps the version string to identify repo state at time of build

- adds “dev” and “release” tags to version strings

The git sha1 tagging and dev/release features are awesome and I would love to get a check for this and perhaps even see the approach upstreamed into fontmake someday. 

I guess the check should be a warn level one, not a fail.

**Comment by felipesanches** [comment]
yay! That sounds pretty cool (and useful) !

I love that approach.

**Comment by chrissimpkins** [comment]
Thanks for sharing this Dave!  The string formatting is still under discussion so not completely stable at this point but will be shortly.  

Conversation re: versioning with the additional data is taking place here 

https://github.com/source-foundry/Hack/issues/293

if you can think of ways to make these version metadata more generally useful for other projects.  We are also considering use of the git commit SHA1 short hash digests as the "cache breaker" strings on the web font CSS.  

If the version string tests would be useful here, I would be happy to try to draft a PR for a Font Bakery test (tests) for them.  May need a bit of contributing guidance (e.g. where it fits in, template for your modular tests, and how you are testing) if this comes from me.  If this is easier to do on your own, please let me know if you have any questions about how we are modifying the version strings on our end.  Happy to pitch in however it is helpful to you.

> and I hope more future projects :)

Know of any type designers who would be interested in drawing open source projects with UFO out there?  Need more heads/hands :)  We can definitely support generalization of our tooling approach to get them from UFO to CI testing/builds but for brand new draws we are (unfortunately) swamped with current work...

**Comment by felipesanches** [comment]
> The git sha1 tagging and dev/release features are awesome and I would love to get a check for this and perhaps even see the approach upstreamed into fontmake someday.


So... First draft of a description for the things to be tested. Let me know if that makes sense:

* Make sure that a sha1 hash is provided
* ensure the sha1 hash value corresponds to the git commit hash at the current local working copy.
* Maybe require that a "release" tag is present if sha1 hash is lacking
* And require that sha1 hashes always go along with a "dev" tag 

What do you think, @chrissimpkins & @davelab6 ?

**Comment by chrissimpkins** [comment]
> Make sure that a sha1 hash is provided

👍 

> ensure the sha1 hash value corresponds to the git commit hash at the current local working copy.

We are using `git rev-list --abbrev-commit --max-count=1 --format="%h" HEAD` to format the git sha1 commit short hashes.  I believe that it defaults to a seven character string unless it is not unique in which case it expands the number of characters until it is.  I believe that this is the same approach that is used on the Github repository displayed short hashes for commits.

> Maybe require that a "release" tag is present if sha1 hash is lacking
> And require that sha1 hashes always go along with a "dev" tag

My recommendation would be to label all releases and dev versions with a git commit sha1 stamp so that you know repository source state for any build artifact, release or not.  I suppose this depends upon your use of git tags (e.g. git repo tag `v1.000` = release build `v1.000; RELEASE`) to identify source state at the time of builds intended for release.

@felipesanches has already started to post IR re: how we can help to make font-v more friendly to your approach here.  The current version substrings (`DEV`, `RELEASE`, `[sha1]-dev`, `[sha1]-release`) are open to modifications if anyone has better ideas/prefers different formats.

For those with an interest, see our conversation about the font-v refactor to support use of the font versioning functionality outside of the executable: https://github.com/source-foundry/font-v/issues/14

**Comment by felipesanches** [comment]
0.3.3 was released today, so this is moving to the next milestone

**Comment by felipesanches** [comment]
https://pypi.python.org/pypi/fontbakery/0.3.3

**Comment by chrissimpkins** [comment]
Is necessary work on font-v blocking work planned for v0.3.4? If so I will make sure that I get to this over the weekend and that we have something straightforward for you to import here.

**Comment by chrissimpkins** [comment]
New libfv library available for feedback / testing to support this issue.  New source changes are currently located in https://github.com/source-foundry/font-v/pull/15

Let me know what you think.

**Comment by felipesanches** [comment]
Cool! I've seen that you did a whole ton of work on it throughout the last week. I'm really happy about it!  I was waiting for you to finish your ongoing burst of code before actually trying it. Based on your comment at https://github.com/source-foundry/font-v/pull/15#issuecomment-347903600 it seems that now's the time for that. So I'll be testing it now. Thanks, @chrissimpkins !

**Comment by chrissimpkins** [comment]
Thanks Felipe.  Let me know if the changes address what you need here.  I *think* that this should work reasonably well but will wait for your feedback to be sure.  Happy to modify.

**Comment by felipesanches** [comment]
ok, thanks
