### ISSUE TITLE
Maybe we should host a copy of MS vendor id list

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1566]
The Travis build too often gets broken due to a failure to load MS website for fetching the list of valid vendor ids. This is becoming increasingly annoying so I wonder we might want to actually host a copy of that list on git. That would require also having a maintenance script to update our copy of the list from time to time, tough...

**Comment by felipesanches** [comment]
This is an example of a silly broken build due to MS website failing to load properly:
https://travis-ci.org/googlefonts/fontbakery/builds/272476235

**Comment by graphicore** [comment]
It's not just travis, this also slows down fontbakery running as jobs/pods in the dashboard. I'm currently putting the download into the container image to speed this up: https://github.com/googlefonts/fontbakery-dashboard/blob/draganddrop/containers/worker-fontbakery/Dockerfile#L25

We'll likely see this coming up again, because my container fix is not optimal either :-)

**Comment by chrissimpkins** [comment]
Might check to see how frequently (or if) MS is updating the pulled data too.  We added a new Foundry ID ~2 months ago (verified as accepted) through MS based on a Font Bakery check and Font Bakery did not recognize it as valid as of my last check ~weekish or so ago.

**Comment by chrissimpkins** [comment]
This is the URL that they provided us to verify the data: https://www.microsoft.com/typography/links/vendor.aspx?VID=SRC

**Comment by chrissimpkins** [comment]
Unfortunately, they don't provide a non-200 response code if the vendor ID is not available via URL string either...

![screenshot at sep 06 11-53-12](https://user-images.githubusercontent.com/4249591/30121572-11f5e326-92fa-11e7-9a8c-674fc5a2a7d5.png)

**Comment by davelab6** [comment]
We should cache the file locally with prominent notices that this is a downstream cache

**Comment by anthrotype** [comment]
sorry but how often do you think this MS vendor list is going to be updated? More than once or twice a year? Seriously, is this worth attempting to reach out to the network every single time one runs fontbakery?!
Why can't you just periodically check it's up-to-date and have a script that updates the cached data file?

**Comment by felipesanches** [comment]
yes, I pondered about that... But my conclusion was that always fetching the data is cheap and in case it fails it is also harmless now (it was bad before).

**Comment by anthrotype** [comment]
you just covered it with a try/except pass. @graphicore also expressed concerns that it slows things down having to download it at every run. nevermind, i'm not even using this.

**Comment by felipesanches** [comment]
well... If the performance hit is unaceptable, then it is also pretty much safe to delete that portion of code and do it manually from time to time. 

I tend to prefer an automated reminder even if it costs a tiny bit of time per run.

**Comment by graphicore** [comment]
> my conclusion was that always fetching the data is cheap

In my case it's not cheap. In the dashboard we'll probably be spinning up thousands of workers on demand (it's not fully decided if and how we do this eventually). If I can get around this http-request I'm very happy. But I can look for a solution when it's about time.

Could we switch it off by default, but on if a specific environment variable is set? We'd ask all contributors to set this environment variable in their `.bashrc` in our README.md under install notes.

> I tend to prefer an automated reminder even if it costs a tiny bit of time per run.

* Ideally we have a cron job, that from time checks the url and time issues a PR in case, like a customized [pyup-bot](pyup.io). But, pyup is not customizable.
* We could do it in travis, but that's a hack, especially because we won't get notifications if nobody PRs us.

Combining this, we'd get a usable hack for free: we could use pyup to monitor our dependencies and have it make PRs, then travis checks the PRs and fails if the vendorlist is outdated :-D It's a bit sneaky though.

There are concerns about pyup #1523

There's also [dependabot](https://github.com/marketplace/dependabot), Open Source is for free. I did not look into details there though.

**Comment by anthrotype** [comment]
Travis CI has cron jobs
https://docs.travis-ci.com/user/cron-jobs/

**Comment by graphicore** [comment]
> Travis CI has cron jobs

Amazing! :1st_place_medal:
