### ISSUE TITLE
correct minimum freetype requirement for Fontval.

### ISSUE THREAD

**Issue by HinTak** [googlefonts/fontbakery#1567]
See https://github.com/googlefonts/fontbakery/issues/1524#issuecomment-327589508

The passage:

"If your vanilla system freetype is used instead, then all FontValidator tests will still be run, except for the hinting validation ones."

is wrong. A few of the table tests requires FreeType 2.6.1 minimum. That's called the "ComputeMetrics Patch".

You know you could just use the supplied binary. For the Nth time.

**Comment by felipesanches** [comment]
I won't officially use the supplied binary because it lacks corresponding source code. **Users can always setup their system with any third-party build of FontValidator, of course.** But that's not what I'll run on Travis for testing FontBakery, because I can't blindly trust binaries without source code.

Also, the prebuilt custom freetype in this repo (https://github.com/googlefonts/fontbakery/tree/ede92e09b96d51caf56cc01b5fd7c3554782cf0f/prebuilt/custom_freetype) was built from the tagged **2.6.4** release (which is greater than 2.6.1 ...) and the full corresponding source code for that is available here: https://github.com/felipesanches/freetype2/commit/1ceb2b5178ce7677f3f4a071fb8bd8800d086e32

**Comment by felipesanches** [comment]
You say "correct minimum requirement" in the issue title. If that's wrongly stated somewhere, we can fix the info. Otherwise, this is a non-issue and thus should be closed.

**Comment by HinTak** [comment]
Well, now you are asking people to trust your repo instead of mine :).

**Comment by felipesanches** [comment]
I can't trust code that I can't read. Please stop flooding the issue tracker.
