### ISSUE TITLE
Reinstate and test for all command line tools

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1576]
A user wrote to me, 

> I’ve just updated Fontbakery and I seem to have lost a bunch of functions? Am I being stupid? Need the vertical metrics tools

- [x] We should add back all the previous tools
- [x] We should have tests to ensure we don't introduce such regressions

**Comment by graphicore** [comment]
Yeah, I think we did not loose them: https://github.com/googlefonts/fontbakery/blob/master/bin/fontbakery-fix-vertical-metrics.py

It's rather that they are missing in setup.py: https://github.com/googlefonts/fontbakery/blob/master/setup.py#L76


I still think setting up fontbakery is messy, using `pip install` and `pip install -r requirements.txt` is very confusing. We don't suffer this problem as developers because we use `pip install -e .` in the repository and that doesn't need the setup.py `scripts` setup.

Eventually, I'd like to see all `fontbakery-`scripts from the `bin` directory in `Lib/fontbakery/commands` each exporting a plain `main` function. Then, we also wouldn't copy so many files into the users PATH.

**Comment by felipesanches** [comment]
Done!

This will cause the next release to contain all scripts and we'll never again ship with missing scripts because now the setup.py automatically detects and installs all fontbakery-*.py files from the bin directory.

**Comment by davelab6** [comment]
AWESOME
