### ISSUE TITLE
Fix ERROR on ligatures conditional

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1596]
in a few rare occasions, we get an ERROR on the ligatures conditional (which is required in tests such as com.google.fonts/test/064, the caret positioning test). This happens on only 7 of the 2400 TTFs in Google Fonts collection:

![screenshot at 2017-09-29 21 27 53](https://user-images.githubusercontent.com/213676/31041318-94548486-a569-11e7-82c4-95d88bb20baa.png)

The actual error is this:
![screenshot at 2017-09-29 23 01 57](https://user-images.githubusercontent.com/213676/31041355-425f948a-a56a-11e7-9389-ca011a83904a.png)

The condition implementation fails at line 2291: 
https://github.com/googlefonts/fontbakery/blob/527dda3e1e5b3364512852a6d63dd7745273a6cc/Lib/fontbakery/specifications/googlefonts.py#L2287-L2300

Interestingly, when trying to use ttx to inspect the file contents I get a similar error, which makes me believe this is a case of corrupted TTF files:
![screenshot at 2017-09-29 23 01 33](https://user-images.githubusercontent.com/213676/31041363-6697f626-a56a-11e7-9725-c51b41ed8c87.png)

This may also be a fontTools bug. Can you confirm that, @behdad ?

**Comment by felipesanches** [comment]
Some example of an offending file from the Google Fonts collection are:
* ofl/bhavuka/Bhavuka-Regular.ttf
* ofl/seoulhangang/SeoulHangang-Medium.ttf
* ofl/seoulhangang/SeoulHangang-Light.ttf

**Comment by davelab6** [comment]
Given the errors happen directly when TTX'ing the fonts, I propose to update the checker runner so that if fontTools fails to unpack a font, that is a FAIL of the check, not an ERROR, because its not a problem with our code, its a problem with the font that this check has uncovered. 

I see in the runner's output the string, `unpack requires` - perhaps you can find that string in the error and if found, return a FAIL?
