### ISSUE TITLE
Restrict non-ASCII check for just a few of the name table entries ?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1663]
```
>> com.google.fonts/test/074 with ((u'font[5]', '/Users/marc/Documents/googlefonts/fonts/ofl/sourceserifpro/SourceSerifPro-SemiBold.ttf'),)
   Are there non-ASCII characters in ASCII-only NAME table entries ?
 * FAIL: There are 2 strings containing non-ASCII characters in the ASCII-only NAME table entries.

   Result: FAIL
```

This is not a helpful fail message. There are 2 strings, great - but what are the strings? what are the non-ascii characters?

Also, I thought we agreed a long time ago that our "is this thing OK in the font file?" methods are named "checks" and our "is this code giving the expected results" methods are named "tests". Is that true? If so, then `com.google.fonts/test/074` is named wrong.

**Comment by m4rc1e** [comment]
I really question this test

What's wrong with including non ASCII characters in every name record apart from the Postscript name record and a few others which the MS spec mentions?
https://www.microsoft.com/typography/otspec/name.htm#langIDs_platID1

Here's the test
```
def com_google_fonts_test_074(ttFont):
  """Are there non-ASCII characters in ASCII-only NAME table entries ?"""
  bad_entries = []
  for name in ttFont["name"].names:
    # Items with NameID > 18 are expressly for localising
    # the ASCII-only IDs into Hindi / Arabic / etc.
    if name.nameID >= 0 and name.nameID <= 18:
      string = name.string.decode(name.getEncoding())
      try:
        string.encode('ascii')
      except:
        bad_entries.append(name)
  if len(bad_entries) > 0:
    yield FAIL, ("There are {} strings containing"
                 " non-ASCII characters in the ASCII-only"
                 " NAME table entries.").format(len(bad_entries))
  else:
    yield PASS, ("None of the ASCII-only NAME table entries"
                 " contain non-ASCII characteres.")
```

this checks all records 0-18 so in other words, our nametable cannot have any non ASCII characters.

There's no rational behind this test in the docstring either.

I'm guessing you've flagged this because of the Source Serif pr, https://github.com/google/fonts/pull/605?

The culprit in Source Serif Pro was Frank's full name, *Frank Grießhammer*

**Comment by felipesanches** [comment]
OK. So we have four tasks and one question here.

The question:
* Dave seems to also dislike "test" on the test id. UUIDs are supposed to be forever, even though we already considered changing our naming criteria a few times. I don't think we should bother with this now, since at some point we'll make a big chunk of naming changes at once (or maybe we'll never change UUIDs at all). This is not critically important, though. So I don't see why we should worry much about it.

The tasks:
- [ ] Actually output the offending strings when the check FAILs.
- [ ] Figure out whether we actually can't have non-ASCII chars in any of the name strings, or just a few. And possibly change the check implementation accordingly.
- [ ] Add rationale metadata
- [ ] rename all of the fontbakery check functions to have the keyword "check"in their function name instead of 
"test"

**Comment by felipesanches** [comment]
![screenshot at 2017-12-05 14 31 27](https://user-images.githubusercontent.com/213676/33618195-00ad8bc6-d9c9-11e7-9863-47859d122aa1.png)

**Comment by m4rc1e** [comment]
Why not mention the offending nameID record as well?

**Comment by felipesanches** [comment]
done :-)

**Comment by felipesanches** [comment]
Regarding @davelab6 's question on nomenclature, yes we've been using the terms **check** and **codetest** in our chat sessions and on the issue tracker because it seems clearer and easier than my original proposal of **tests** and **self-tests** (respectively).

But on the codebase we still use "test" for all our font file testing routines as seen below:

![screenshot at 2017-12-05 14 39 48](https://user-images.githubusercontent.com/213676/33618729-7fdb817c-d9ca-11e7-9f16-7add97e271da.png)

I think that's acceptable as we've never got confused about the meaning of it.

**Comment by felipesanches** [comment]
Only remaining task here is to figure out whether we actually can't have non-ASCII chars in any of the name strings, or whether just a few entries have this restriction. And possibly update metadata and implementation accordingly.

**Comment by davelab6** [comment]
Semver takes care of the breaking of uid namespace. Please make the change.

The unidecode output produces lies.

I agree with Marc that requiring ascii everywhere is annoying. I believe
it's required by the OpenType spec for the ps nameID (6), and I believe I
requested it for copyirght nameID (0) because that string should be the
same in cff fonts which also has this requirement in the OpenType spec

**Comment by felipesanches** [comment]
> The unidecode output produces lies.

This is better, right?
![screenshot at 2017-12-05 18 48 18](https://user-images.githubusercontent.com/213676/33629972-e88bb4c2-d9ec-11e7-82ce-726c6e3d648e.png)

**Comment by davelab6** [comment]
> This is better, right?

Yes, that's a little better, although

- [ ] I would prefer hex to decimal, eg `&#x00DF;`
- [ ] nameID 9 isn't one that is restricted to ASCII, only 0 and 6

**Comment by felipesanches** [comment]
nameID 9 on that screenshot is from before a commit where I restricted non-ASCII checks to nameIDs 0 and 6 only, so that is good now. I checked and that font file PASSes the check.

**Comment by graphicore** [comment]
About 2a8060b I dislike it a alot. It will cause me work to make the dashboard stuff compatible again and it ruins git blame. wtf, only for some cosmetic reason.

**Comment by felipesanches** [comment]
For a conceptual reason!

And @davelab6 was recurrently asking for it. And I agree that the new terminology makes sense.

**Comment by graphicore** [comment]
But how deep has this to go :-/

**Comment by graphicore** [comment]
Also, you don't do PRs anymore?

**Comment by felipesanches** [comment]
> I would prefer hex to decimal, eg &#x00DF;

well... that notation is what python gives us for free with:
```python
string.encode("ascii", errors="xmlcharrefreplace")
```

**Comment by felipesanches** [comment]
> Also, you don't do PRs anymore?

I do. All the time :-)
https://github.com/googlefonts/fontbakery/pull/1665

**Comment by davelab6** [comment]
> Also, you don't do PRs anymore?

Felipe makes PRs and IMMEDIATELY merges them, eg in this case  https://github.com/googlefonts/fontbakery/pull/1665, which is probably a bad thing. 

We should have a `.travis.yml` that checks if its been 24 hours since the PR was opened and refuses to merge it until then ;)

**Comment by davelab6** [comment]
> that notation is what python gives us for free with

Okay, its a minor thing, in a GUI it can be changed and the raw results its good enough

**Comment by graphicore** [comment]
> I do. All the time :-)

I see, I was looking for the "merge" commit message in the history.

**Comment by felipesanches** [comment]
well... no **immediately**. I do wait for Travis do run all tests and after it is good I merge (if a bug has been fixed).

**Comment by felipesanches** [comment]
> I see, I was looking for the "merge" commit message in the history.

I do use github's "rebase & merge" option on the PR UI.

**Comment by graphicore** [comment]
IC

**Comment by felipesanches** [comment]
keeps the history cleaner.

**Comment by davelab6** [comment]
> well... not **immediately**

Sure, but still too far for anyone to comment and improve it before it goes in :) 

> I do use github's "rebase & merge" option on the PR UI.

Yes, I like that :) 

Well, mybe we should revert 2a8060b and leave it in an open PR for @graphicore to merge when he is ready with the downstream dashboard changes, so that it can be done together. 

Also above, I said, 

> Semver takes care of the breaking of uid namespace. Please make the change.

Indeed instead of "Please make the change" I should have said "Please prepare to make the change" - since the prior sentence indicates that I had in mind that this change should be made when we go to v1.0.0

**Comment by davelab6** [comment]
@felipesanches If you haven't read www.semver.org it would be good to do so :)

**Comment by graphicore** [comment]
> keeps the history cleaner. 

But it removes all reference to the PR (and thus the place to discuss issues with it)

**Comment by felipesanches** [comment]
yes, I know semver.

**Comment by felipesanches** [comment]
> But it removes all reference to the PR (and thus the place to discuss issues with it)

Absolutely all my commits include an issue number identification so that the place for discussion is always traceable. The issues themselves also **always** have references to their related pull requests.

**Comment by graphicore** [comment]
> The issues themselves also always have references to their related pull requests.

lol, didn't work for me just now.

> Well, mybe we should revert 

Keep it! seems like it has not so much impact as thought it would have.

**Comment by felipesanches** [comment]
thanks, @graphicore :-)

**Comment by davelab6** [comment]
> lol, didn't work for me just now.

Maybe particular to this issue, in that its a bit noisy, but it look OK to me:

<img width="816" alt="screen shot 2017-12-05 at 22 37 25" src="https://user-images.githubusercontent.com/261579/33643411-e26ba154-da0c-11e7-9b23-51e14492bbe8.png">

> seems like it has not so much impact as thought it would have.

OK great :)

**Comment by felipesanches** [comment]
thanks, @davelab6 

you're good with that decimal xml syntax?

**Comment by davelab6** [comment]
Yep
