### ISSUE TITLE
Update travis file to ensure PRs have time for community review

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1667]
In https://github.com/googlefonts/fontbakery/pull/1665 I said,

> we could have a .travis.yml that checks if its been 24 hours since the PR was opened and refuses to merge it until then

**Comment by felipesanches** [comment]
Oh, Dave! That would be problematic I think... Not all issues require a quarantine. Actually most of my PRs are pretty straightforward. Let's adopt a common sense guideline instead of enforcing a rigid scheme via Travis ?

**Comment by felipesanches** [comment]
I'd suggest that I voluntarily leave PRs open for things that are non-trivial and that may impact other people's work.

**Comment by felipesanches** [comment]
But I'd remain rebasing and merging all other PRs (the majority them) right after they pass the code tests on Travis.

**Comment by davelab6** [comment]
What is the purpose of a PR if no one else will review it? Just commit to
master directly

**Comment by felipesanches** [comment]
PRs trigger travis. That's the whole purpose.

**Comment by felipesanches** [comment]
It is safer and more prudent for me to wait for travis with my code sitting on a PR and merge only after I have confirmation that it works well on the travis testing environment, instead of pushing directly to master.

I do also often run pytest locally, but I like double-checking it with the remove travis build jobs to make sure I don't end up in a "works **only** for me" situation.

**Comment by davelab6** [comment]
Ah, right, makes sense. If this isn't helpful then lets close it :)
