### ISSUE TITLE
com.google.fonts/check/018 should detect abbreviations

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1688]
## Observed behaviour

```
>> com.google.fonts/check/018 with ((u'font[0]', '/home/nikolaus/Downloads/Ubuntu GF Font/Ubuntu-R.ttf'),)
   Checking OS/2 achVendID.
 * WARN: VendorID 'DAMA' and corresponding registered name 'Dalton Maag Limited' does not match the value that is currently set on the font nameID 8 (Manufacturer Name): 'Dalton Maag Ltd' [code: mismatch]
 * WARN: VendorID 'DAMA' and corresponding registered name 'Dalton Maag Limited' does not match the value that is currently set on the font nameID 8 (Manufacturer Name): 'Dalton Maag Ltd' [code: mismatch]

   Result: WARN
```

## Expected behaviour

The check should detect "Ltd" as an abbreviation for "Limited"

## Resources and exact process needed to replicate

Download and check the GF release of Ubuntu.

**Comment by felipesanches** [comment]
Please consider updating the font metadata in your files instead.

**Comment by sladen** [comment]
Since 'Limited' and 'Ltd' appear in roughly enough proportion in the the vendor listed derived from:
* https://www.microsoft.com/typography/links/vendorlist.aspx
it would likely save time and hassle if "Limited"/"Limited."/"Ltd"/"Ltd." where treated equivalently for the purposes of evaluation.

Background: @felipesanches: the workplan here is to build an equivalent to the binary Ubuntu in GF from source form, and preferably keep FB happy too (FB is designed to help onboard, not hinder).

**Comment by felipesanches** [comment]
i have the impression that this was already fixed. Can any of you confirm, please?

**Comment by felipesanches** [comment]
yes. This was already fixed in the past when we dropped the portion of the check routine that compared the vendor-id with the manufacturer name (nameid 8).
