### ISSUE TITLE
[Specifications][googlefonts]: Fonts have consistent underline thickness?: No rational given

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1692]
In the Googlefonts spec we have [com_google_fonts_check_008](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/googlefonts.py#L286-L308) which checks that the underline thickness is the same across the family (it doesn't care about positioning).

There is no rational given for this check. I also couldn't find any [Ms recommendation](https://www.microsoft.com/typography/otspec/recom.htm) for why you'd want this.

Anyone have any idea why this is here?

I'm in favour of adding rational notes for every check this year. I'm also in favour of culling any checks we all agree are unnecessary.

**Comment by felipesanches** [comment]
TO-DO: I'll try to look up the git history and read the commit log messages from when this check was added. It may clarify the original rationale behind it.

**Comment by sladen** [comment]
Required quite a bit of digging because the test has been moved and renamed, but following back ends up at:
* `git show e7bd125d`

on the basis of:
* googlefonts/fontbakery/issues/635

Which points to a Twitter message originating from David Lemon, manager of the Adobe Type group:
* https://twitter.com/typenerd1/status/690361887926697986

An a minimum, this little piece of archaeology should probably added as a comment in the source.

**Comment by felipesanches** [comment]
Awesome! Thanks :-)

**Comment by m4rc1e** [comment]
Thanks @sladen!

**Comment by felipesanches** [comment]
![screenshot at 2018-01-15 10 58 17](https://user-images.githubusercontent.com/213676/34943486-0614218a-f9e3-11e7-814b-1d5acdbb7e34.png)

**Comment by felipesanches** [comment]
I'm almost sure that "InD" in that tweet means Adobe InDesign.

**Comment by felipesanches** [comment]
So, I think all the rationale we've got behind this up to know is something like this:

```
Adobe InDesign relies on the value of Underline Thickness being consistent across all fonts in a family. Otherwise, text layout can get slightly broken.
```

Would anyone like to improve that text with further info? Or can I commit this?

**Comment by m4rc1e** [comment]
```
Dave C Lemon, Adobe Type Team recommends setting the underline thickness
to be consistent across the family, https://twitter.com/typenerd1/status/690361887926697986

If thicknesses are not family consistent, words set on the same line which
have different styles look strange.
```

**Comment by felipesanches** [comment]
Great! Thanks.

**Comment by yanone** [comment]
I've run into this check, as well.

> Dave C Lemon from the Adobe Type Team recommends setting the underline
thickness to be consistent across the family,
https://twitter.com/typenerd1/status/690361887926697986
> If thicknesses are not family consistent, words set on the same line which
have different styles look strange.

Really? 
If you set it the same thickness across all weights of a family, _all_ weights (minus one if lucky) look strange.
Please reconsider this.

**Comment by laerm0** [comment]
Agreed with @yanone. The spec for this needs to have some more flexibility.

**Comment by xotypeco** [comment]
to point out: this is a tweet from 2016. Dave has since retired and deleted his Twitter account, so following this Adobe recommendation could possibly not be relevant to what InDesign's type engine does nowadays.

also agree with @yanone. consistent underline weight will result in underlines looking wrong in many cases across a single family.
