### ISSUE TITLE
fontbakery main executable not recognized in Powershell/cmd.exe because of missing .py suffix

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1738]
## Observed behaviour

In cmd.exe and Powershell, scripts like `fontbakery-check-googlefonts.py` can be invoked either with or without suffix, but the main `fontbakery` can't.

## Expected behaviour

Running `fontbakery` should work on Windows.

## Resources and exact process needed to replicate

Renaming the script to `fontbakery.py` makes it work as expected.

**Comment by anthrotype** [comment]
I don't know why fontbakery doesn't simply use `entry_points = {'console_scripts': ['myscript=mylib.module:main']}`:
http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point

this is the most portable way to make python executable scripts

**Comment by madig** [comment]
Smells like low-hanging fruit. Just the thing for me!

**Comment by anthrotype** [comment]
I believe Windows support hasn't been much of an issue so far, as most fontbakery users and developers are macOS or Linux users.

**Comment by madig** [comment]
DaMa uses Windows for most work, so we can contribute Windows testing :)

**Comment by anthrotype** [comment]
Maybe it's also because fontbakery was originally a collection of standalone scripts that only later has grown into a library, but some of its functionality is still outside the `fontbakery` module and inside the `bin` scripts.

Btw, that `bash_completion` thing is never going to work on Windows, but that's ok.

**Comment by anthrotype** [comment]
you could make a ` fontbakery.cli` module with the contents of the current `bin/fontbakery`, and a single console_scripts entry_point called just `fontbakery`, with each argparse subcommand calling functions from other sub-modules (one for each current `bin/` script). And you won't need to call the scripts as subprocesses as you do now.

(Note: i'm not a fontbakery developer and I'm not familiar with it's codebase. This are just my 2c. Please defer to @felipesanches @graphicore @m4rc1e & co.)

**Comment by felipesanches** [comment]
@madig yeah, I've seen the messages here. I'm just unsure about what to do in this case, sorry.

**Comment by m4rc1e** [comment]
FB used to be just a collection of standalone scripts. We did use setup.py's script entry points at that time.

[bin/fontbakery](https://github.com/googlefonts/fontbakery/blob/master/bin/fontbakery) controls which script gets executed from a user's input. This is similar to Cosimo's suggestion.

> Renaming the script to fontbakery.py makes it work as expected.

@felipesanches can't we just do this? I don't know why it doesn't have an extension to being with.

**Comment by madig** [comment]
I suppose using setup.py's `console_scripts` can make the different bin/fontbakery* scripts go away? That'd be cleaner.

**Comment by felipesanches** [comment]
I would delegate a final decision on this to @graphicore since he created this subcommands mechanism we're currently using and he could perhaps have some good arguments in favor o keeping it that way. What do you thing, Lasse?

**Comment by graphicore** [comment]
> I would delegate a final decision on this to @graphicore 

This subcommands mechanism is the way it is because of the historical fontbakery structure. We also had many more scripts in `bin` when this was created. Many moved now to https://github.com/googlefonts/tools/tree/master/bin

> I don't know why fontbakery doesn't simply use entry_points = {'console_scripts': ['myscript=mylib.module:main']} […] this is the most portable way to make python executable scripts

This was staright forward. We had more urgent tasks than diving into into python packaging details. Maybe now is a good time for that, just hoping to answer your " I don't know why …".

>>    Renaming the script to fontbakery.py makes it work as expected.
> @felipesanches can't we just do this? I don't know why it doesn't have an extension to being with.

If that really **just works** I don't see why we shouldn't do it. It's like 2 minutes. We could also just make a `ln -s  fontbakery.py fontbakery` in `bin` (or create an alias) and nothing would have changed for the rest of us. 

> I suppose using setup.py's console_scripts can make the different bin/fontbakery* scripts go away? That'd be cleaner.

To make these scripts go away we should beforehand analyze our needs. I see a half better half worse situation arising that also costs work. E.g. at the moment we also integrate `fontbakery-*.sh` scripts and may or  want to have   So either we get our requirements straight or the least invasive, least work intense path is good enough. more discussion at #1745

**Comment by anthrotype** [comment]
> just hoping to answer your " I don't know why …"

**Comment by anthrotype** [comment]
> just hoping to answer your " I don't know why …"

thanks Lasse, that answers it perfectly. I didn't mean to push you in the other direction.
Just wished to point out what you already knew, that the distutils scripts are less portable than the console_scripts wrappers installed from python wheels. Whatever works best for your guys.

**Comment by graphicore** [comment]
>  I didn't mean to push you in the other direction.

All good. Thanks!

**Comment by madig** [comment]
Closed by #1745.
