### ISSUE TITLE
Purpose of FontbakeryCallable._ignore_mandatory_args?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1910]
I'm trying to understand how Fontbakery works internally so I'm refactoring classes by myself. I stumbled over the titular variable that doesn't seem to be used outside the class definition. What gives?

**Comment by graphicore** [comment]
It was added in "Fix oldstyletest" 9c6060678e60c9071bcbf375bb0e4b326f6c694a (`git-blame` did help me find this; btw. one of the reasons why I don't like the idea of running everything through a code formatter.)

Since `Lib/fontbakery/testadapters/oldstyletest.py` is no longer in use and removed, this can also disappear.

 `oldstyletest.py` was an adapter to transition between fontbakery pre-checkrunner to fontbakery post-checkrunner, to make it smooth. @felipesanches decided pretty quickly though to port all legacy to new style checks.

**Comment by felipesanches** [comment]
yeah! :-D

**Comment by madig** [comment]
> (git-blame did help me find this; btw. one of the reasons why I don't like the idea of running everything through a code formatter.)

See the thread https://twitter.com/llanga/status/996506438188126209.

> Since Lib/fontbakery/testadapters/oldstyletest.py is no longer in use and removed, this can also disappear.

Ok.
