### ISSUE TITLE
FontbakeryCallable: optional/mandatory arguments split necessary?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1913]
`mandatoryArgs` isn't referenced anywhere and `optionalArgs` appears only in CheckRunner._get_args() -- where the docstring says that optional arguments aren't supported?

**Comment by graphicore** [comment]
The comment says (emphasis mine):

> **iterargs** can't be optional arguments

because basically an empty iterable argument (= empty list) wouldn't cause any executuion of that check and this not call `_get_args` in the process.

`mandatoryArgs` is used as part of `args` in `FontbakeryCallable`

```
@property
  @cached_getter
  def args(self):
    return self.mandatoryArgs + self.optionalArgs`
```

**Comment by madig** [comment]
Okay, so I misunderstood the docstring. However: `mandatoryArgs` isn't used outside FontbakeryCallable. Can a check have a default argument and if so, why would it have one?

**Comment by graphicore** [comment]
> Can a callable have a default argument

quite, it's treated like a python function.

> if so, why would it have one

To make a callable more compatible with a normal python function, or the other way around, to use an existing python function or check that has optional arguments. I was not thinking about concrete use cases here, just making it complete: functions have optional arguments, inspection returns optional arguments, why castrate it by not allowing them.

A use case could be unit testing, e.g. to inject an alternative object for a file system API. Pre-existing functions from other modules/specs as conditions or checks that define optional args, a spec that doesn't define a certain `expected_value` for any reason but another spec does and a check that works in both cases.

The interesting thing in your observation is, that in the meantime, I introduced `Spec.test_dependencies` which uses `dependencies = list(check.args)` and `dependencies += condition.args`. There we should use `dependencies = list(check.mandatoryArgs)` and `dependencies += condition.mandatoryArgs` otherwise, there's no way to **NOT** get optional args into the DI-namespace. The current behavior (force optional args to exist) should be optional, It seems right to only check for `mandatoryArgs` here and unlock the feature again.
