### ISSUE TITLE
Test check 001 (Checking file is named canonically): needs an update for variable fonts 

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#1937]
FontBakery gives me a FAIL result when checking variable fonts:

```
>> com.google.fonts/check/001 with (('font[0]', 'MarkaziText-VF.ttf'),)
   Checking file is named canonically.
 * FAIL: Style name used in "MarkaziText-VF.ttf" is not canonical. You should rebuild the font using any of the following style names: "Thin", "ExtraLight", "Light", "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black", "Thin Italic", "ExtraLight Italic", "Light Italic", "Italic", "Medium Italic", "SemiBold Italic", "Bold Italic", "ExtraBold Italic", "Black Italic".

   Result: FAIL
```

I looked at the FontBakery source and couldn't find anything that anticipates a variable font as input for this test.

**Comment by davelab6** [comment]
Yeah, FB does not currently have VF checks. I think Felipe is going to cut a new release this week, and then the next milestone was "super families" - eg "FAMILY" and "FAMILY Condensed" or "FAMILY SC" - and so VFs can be a natural part of that since a single VF would map to several such 'sibling' families. 

The most simple VF check will be as you say, to check the filenames are 'canonical'. I propose this naming scheme:

    FAMILY-Roman-VF.ttf
    FAMILY-Italic-VF.ttf
