### ISSUE TITLE
Weight Class checks for 100 and 200 should warn only

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1948]
## Observed behaviour

https://github.com/googlefonts/fontbakery/blob/46e2973e6f34c9c2d908812e2a774b5dc832bc1c/Lib/fontbakery/specifications/os2.py#L80-L100

Checking the current version of Hepta Slab ([source file](https://github.com/mjlagattuta/Hepta-Slab/blob/f5fb4d79a2ae503b1b62c4bba754f1ed1e0a2723/sources/Hepta-Slab.glyphs), needs to be generated, no binaries published yet), this check FAIL'd because the Thin and ExtraLight were 100 and 200, which we learned from IBM Plex is actually valid for TTFs but not OTFs; so the os2 check should be updated to distinguish OTF from TTF and only WARN about those 2 values in a TTF, such that Hepta doesn't FAIL this project.

Also the info should tell GlyphsApp users to set a Instance Custom Parameter for the Thin and ExtraLight styles to 250 and 275, so that if they do export an OTF then it will not blur on Windows.

**Comment by davelab6** [comment]
Check 071 is weirdly duplicating this and giving an INFO result on Hepta right now

**Comment by felipesanches** [comment]
This is taking longer than usual because the code in this check is more complex than actually needed.

If I recall correctly, at some point in the past we've got people complain about Google-Fonts specific requirements in the generic os2.py module. Then Lasse created a mechanism for the same check to behave differntly depending on which spec imports it. So the dependency injection mechanism would be used to modify the check requirements.

I would like to revert that because it makes the code very confusing to deal with. I'd prefer to have 2 separate checks in cases like this if needed, so that the code is simpler and easier to understand/debug/test.

Having said that, in this specific instance of the problem (and I think that it is the single place where the mechanism is currently used), one of the 2 specs simply never runs the check since on of the conditions (`expected_os2_weight`) is always falsy (None).

So, for now I'll simply move the check entirely to the googlefonts spec and remove the fancy mechanism.
