### ISSUE TITLE
com.google.fonts/check/080: Designer key must be short name

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1996]
A short name isn't possible if a family has multiple authors. The GF api does allow for multiple authors, https://fonts.google.com/specimen/Oswald

![screen shot 2018-08-03 at 11 52 04](https://user-images.githubusercontent.com/7525512/43639298-aa6d6138-9713-11e8-89f6-b0a7fcf6032b.png)

https://github.com/google/fonts/blob/master/ofl/oswald/METADATA.pb#L2

Found in https://github.com/google/fonts/pull/1634

**Comment by davelab6** [comment]
Agree, the current check should be prefaced by segmenting the string (by comma space, `, `) into a list of strings, then check each one.

**Comment by felipesanches** [comment]
The current implementation seems to suggest we were not willing to accept a list of names in this field.

As it lacks comments or a rationale description, it is unclear what was the reason for that. Assuming Google Fonts does not currently require that field to be a single designer name I can change the check implementation so that it only bothers about too long individual names.

I would still appreciate a rationale for this, though. What kind of problem is caused by a name longer than a certain (arbitrary?) length?

**Comment by felipesanches** [comment]
This is the current implementation:
![screenshot at 2018-08-14 18 56 49](https://user-images.githubusercontent.com/213676/44120886-5ef993cc-a00d-11e8-989a-b5a197d237b4.png)

**Comment by felipesanches** [comment]
I believe that this check is simply non-sensical, so I'll drop it. (deprecate it)
