### ISSUE TITLE
Check 044 is always an error

### ISSUE THREAD

**Issue by laerm0** [googlefonts/fontbakery#2006]
## Observed behaviour

Check 044 always produces this error:

```>> com.google.fonts/check/044 with ((u'font[0]', 'Topmarks-Bold.ttf'),)
   Checking font version fields (head and name table).
 * FAIL: head version is ('1', u'00099'), name version string for platform 1, encoding 0, is ('1', u'001') [code: mismatch]
 * FAIL: head version is ('1', u'00099'), name version string for platform 3, encoding 1, is ('1', u'001') [code: mismatch]

   Result: FAIL
```

It does this on a fresh, unedited font directly out of Glyphs. I think this output looks good.

**Comment by felipesanches** [comment]
![screenshot at 2018-08-08 17 16 24](https://user-images.githubusercontent.com/213676/43861944-f16bd2d0-9b47-11e8-9d05-ff2766fcc7cb.png)

**Comment by chrissimpkins** [comment]
The name id5 record specifies the version string as follows:

> The string must contain a version number of the following form: one or more digits (0-9) of value less than 65,535, followed by a period, followed by one or more digits of value less than 65,535. Any character other than a digit will terminate the minor number. A character such as “;” is helpful to separate different pieces of version information. 

so `1.00099` is a possible valid minor version value and should not be rounded at three digits.  Maybe best to cast the major and minor strings to int values (this achieves a test that there are no non-integer characters in the major/minor version number parts of the string), test that both major value and minor value are < a value of 65,535 (range validity test), and perform integer equality comparison between head.fontRevision record & name id5 records if all values fall in a valid range assuming that these tests are not implemented already?

In source I mean something along these lines understanding that the function shown above is not intended to perform QA tests but to parse major, minor values as strings:

```python
major, minor = version_string.group(1).split('.')

# version character validity test during int cast attempt
try:
    major_int = int(major)
    minor_int = int(minor)
except Exception:
    # raise error

# version number validity test
if major_int > 65534:
    # raise error
if minor_int > 65534:
    # raise error
...

head_version = (major_int_head, minor_int_head)
name_version = (major_int_name, minor_int_name)

# head.fontRevision definition == name ID5 record definition
if not head_version == name_version:
   # raise error
```

**Comment by chrissimpkins** [comment]
Directly testing the unsplit MAJOR.MINOR string parsed from name id5 vs MAJOR.MINOR in head table record avoids the entire issue for the comparison check.  It might be this simple for that test instead of getting bogged down in the 16.16 int value testing.

**Comment by felipesanches** [comment]
@laerm0 can you send me a font file that fails, please?

**Comment by felipesanches** [comment]
We already have a code test for this check so it will help us avoid regressions.

I have just split the code-test implementation so that one test validates the parse_version_string function and the other tests check/044

**Comment by felipesanches** [comment]
This is the current code-test and it passes:
![screenshot at 2018-08-08 20 32 40](https://user-images.githubusercontent.com/213676/43869693-5b7d0282-9b63-11e8-89d5-2c77a5b5f06d.png)

Since it passes, it means that @laerm0's font files are expected to be good and they're a new test case we should add. Or that the files are indeed bad.

**Comment by felipesanches** [comment]
I think that the problem here is that `test_font["head"].fontRevision` is a float and the rounding issues happen when converting to a string.

**Comment by felipesanches** [comment]
yes, I have expanded the tests to add a test case inspired on @laerm0's issue that fails with the current check/044 implementation:

![screenshot at 2018-08-08 20 51 12](https://user-images.githubusercontent.com/213676/43870242-1729d1fc-9b66-11e8-929a-41da07af1eb4.png)

**Comment by felipesanches** [comment]
hmmm... today I added a test case inspired on @laerm0's font files but now I see my implementation ws bad, so I am still investigating this.

**Comment by chrissimpkins** [comment]
I think that you may be right Felipe.  fontTools is returning a string for name.id5 and a float (converted from a 16.16 fixed value using the fontTools fixedTools library) for the head.fontRevision record.  Perhaps those fixed/float roundtrips are leading to the problem here?

Here is where fontTools compiles to and decompiles from 16.16 fixed values for the head.fontRevision record:

https://github.com/fonttools/fonttools/blob/c895f4f4a23235688ef95ca83ae60f7d175e673a/Lib/fontTools/ttLib/tables/_h_e_a_d.py#L16

It uses the sstruct class to pack and unpack the head table and the 16.16 values are converted to float values during this decompile processing:

https://github.com/fonttools/fonttools/blob/3a97f425b850bd0cca482491ec6fd0327c75842f/Lib/fontTools/misc/sstruct.py#L19-L23

The float --> fixed point and fixed point --> float conversions are here (pack):

https://github.com/fonttools/fonttools/blob/3a97f425b850bd0cca482491ec6fd0327c75842f/Lib/fontTools/misc/sstruct.py#L71

and here (unpack):

https://github.com/fonttools/fonttools/blob/3a97f425b850bd0cca482491ec6fd0327c75842f/Lib/fontTools/misc/sstruct.py#L93

This may be the workaround that you need (Py3.7):

```
>>> from fontTools.misc.fixedTools import floatToFixed

# define a string vs. a float that are the same "value"
>>> v1 = "1.001"
>>> v2 = 1.001
>>> type(v1)
<class 'str'>
>>> type(v2)
<class 'float'>

# convert to fixed value for the comparison
>>> v1_fixed = floatToFixed(float(v1), 16)
>>> v2_fixed = floatToFixed(v2, 16)
>>> v1_fixed == v2_fixed
True

# define a string vs. a float that are different "values" by padded zeroes
>>> v3 = "1.010"
>>> v4 = 1.001

# convert to fixed value for comparison
>>> v3_fixed = floatToFixed(float(v3), 16)
>>> v4_fixed = floatToFixed(v4, 16)
>>> v3_fixed == v4_fixed
False
```

The above should eliminate the need to parse out the MAJOR and MINOR version strings in order to perform the comparisons and eliminate the issue with the different data types.

**Comment by felipesanches** [comment]
@laerm0 sent me one of his files that are failing. Looking up the data with ttx I see that the fontRevision value is actually `1.00099`!

![screenshot at 2018-08-08 23 48 22](https://user-images.githubusercontent.com/213676/43875095-cdc5be18-9b7e-11e8-892d-73c2f1c93de0.png)

**Comment by chrissimpkins** [comment]
hahaha! Bizarre.  And name.id5 is "Version 1.001"?

**Comment by felipesanches** [comment]
yes

![screenshot at 2018-08-08 23 59 28](https://user-images.githubusercontent.com/213676/43875526-42abba10-9b80-11e8-9fd3-89264c384d32.png)

**Comment by chrissimpkins** [comment]
Well, you can safely say that it isn't a Font Bakery problem then :)

That ttx report is also converting a fixed ---> float ---> string.  If you directly access the head.fontRevision data in the font with fontTools do you get the float `1.001`?  If so, there is no problem and you can use the approach that I suggested above.  If not, then this may be a compiler issue?

**Comment by felipesanches** [comment]
@schriftgestalt, I think this is a bug in Glyphs

**Comment by felipesanches** [comment]
@schriftgestalt, could you help us figure out how to best inform our users regarding the procedures to work around this bug and/or to manually fix the problem in their font files?

**Comment by madig** [comment]
Some discussion about this on the fontTools issue tracker: https://github.com/fonttools/fonttools/issues/944

**Comment by chrissimpkins** [comment]
> Maybe just be pragmatic and round fontRevision to 3 digits?

`decimal.quantize` will achieve @madig's suggestion:

```python
>>> from decimal import Decimal
>>> d = Decimal(float("1.001"))
>>> d
Decimal('1.000999999999999889865875957184471189975738525390625')
>>> dq = d.quantize(Decimal('1.000'))
>>> dq
Decimal('1.001')
>>> d2 = Decimal(float("1.010"))
>>> d2
Decimal('1.0100000000000000088817841970012523233890533447265625')
>>> dq2 = d2.quantize(Decimal('1.000'))
>>> dq2
Decimal('1.010')
```

For all practical purposes this works because no one ever has used 65k+ minor versions in the history of typeface development, but the test creates a standard outside of the OT specification for the MINOR value (and MINOR is a term that isn't even in the OT spec, there are no semantics involved in the OT specification for version numbers).  So, someone could create a valid font versioned `1.65534" and your testing would lead to this:

```python
>>> d3 = Decimal(float("1.65534"))
>>> d3
Decimal('1.6553400000000000336086714014527387917041778564453125')
>>> d3.quantize(Decimal('1.000'))
Decimal('1.655')
```

which describes a different MINOR version than the author specified.

A practical standard for semantic font versioning is warranted. I tried to get a conversation started with the OpenFV repository but it fizzled...   :)

**Comment by moyogo** [comment]
There’s a recommendation on the [Recommendations for OpenType Fonts page](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#head-table) regarding the head table revision:
> Although historical usage of the fontRevision value is varied, the recommended use of the field is to set it as a Fixed 16.16 value, and to report it rounded and zero-padded to three fractional decimal places. Examples: Decimal 1.5 is set as 0x00018000 and is reported as “1.500”; decimal 1.001 is set as 0x00010041 and is reported as “1.001”.

**Comment by schriftgestalt** [comment]
(I’m out of office until later this week)

I read the whole thread but didn’t get the part where Glyphs does the wrong thing?

One thing I liked to suggest to change ttx to handle most of the 16.16 version fields as two 16bit major/minor fields. The float conversation is just to annoying.

**Comment by madig** [comment]
@chrissimpkins Err, you mean the OT standard should be changed? I think the issue is that to round correctly, the version number has to be quantized to be a power of 2 that fits into a 16.16 integer. My math for this would need some brushing up though...

**Comment by chrissimpkins** [comment]
@madig can you post that first link that included the comments from Peter Constable?  I read it on my phone but didn’t pay attention to the repository that it was on.  His comments there were pertinent to the discussion.

**Comment by felipesanches** [comment]
Thank you all for the insightful input provided in this thread!
