### ISSUE TITLE
new check: Font binaries should not contain VTT Talk sources

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2059]
Issue #2048 is caused by an invalid charactere in a block of VTT Talk source code embedded in the font file. This made me figure out that we need a check to ensure font files meant to be published do not contain VTT Talk sources, as this only takes up space but have no practical use on a released font file.

**Comment by ctrlcctrlv** [comment]
I think I disagree with this change, but then again I can see why it was done.

VTT Talk information is useful not to users but to people who work on fonts.

It's not quite incorrect to have it there. It should be WARN not FAIL.

**Comment by felipesanches** [comment]
VTT Talk information should not be in production binary files. If kept, it should be on project source files, instead of bloating the final binaries.

**Comment by ctrlcctrlv** [comment]
I'm not so clear on what the difference between FAIL/WARN is, I guess :)

**Comment by felipesanches** [comment]
A **FAIL** is something that must be addressed. A **WARN** is something you should consider because it may be a good thing to address.

**Comment by ctrlcctrlv** [comment]
So to be certain FontBakery is not a general purpose tool, it's for QA for Google Fonts? I'm not being facetious, I really am unsure of its purpose now that you say this. Or is it a general purpose tool for making fonts as small as possible _for use as web fonts_? Because having the TSI* sources in the fonts for desktop distribution still seems fine, even preferred to me, as it backs them up and for debugging lets you know exactly what instructions are in a build.

**Comment by felipesanches** [comment]
The check we're talking about here, **check/vttclean**, is part of the `googlefonts` profile and so it is a vendor-specific requirement that is only meant to be addressed by fonts being prepared for onboarding on the Google Fonts collection.

Checks on the Universal profile, on the other hand, are those that are currently considered "best practices agreed upon on the broad type design community".

And checks on the OpenType profile enforce things defined on the OT spec.

https://github.com/googlefonts/fontbakery/blob/a75e5bf8854d10ce21d6a57c189bf90a86048085/Lib/fontbakery/profiles/googlefonts.py#L4045

![Screenshot from 2022-05-08 23-01-38](https://user-images.githubusercontent.com/213676/167328266-9adce09c-12fa-4857-a1d9-b00044e39219.png)

**Comment by felipesanches** [comment]
Having said that, the FontBakery project is flexible to move checks to different profiles whenever we figure out that's the best thing to do. For instance, checks that were initially vendor-specific may move to the `universal` profile if multiple vendors decide to adopt it. And checks frmo `universal` profile may move to vendor-specific profiles if disagreement surfaces that they shouldn't really be in `universal`.

**Comment by felipesanches** [comment]
Read more about profiles at our docs at: https://font-bakery.readthedocs.io/en/stable/

**Comment by ctrlcctrlv** [comment]
Thanks a lot, I get it now, how this project is structured. I appreciate the free education, really! :o)

**Comment by felipesanches** [comment]
you're welcome!

**Comment by twardoch** [comment]
Also, one can create inherited profiles that also exclude some checks, for example here:

https://github.com/googlefonts/fontbakery/blob/main/Lib/fontbakery/profiles/adobefonts.py

This is useful for many scenarios, not just of you’re a different vendor, but also depending on where in the pipeline you’re running bakery. For example, if bakery is integrated with a font editor so that it runs right after the editor builds the font, then that font editor’s profile might use most of Google Fonts’ checks but exclude some, like the VTT tables check — reasonable because when you’re exporting fonts from a font editor, one of the goals of the export might be to prep fonts with some stub VTT data with the goal of actually being refined with VTT. 

And a font editor courtly reasonably use two different profiles — one for “devel/debug” export and one for “distrib” export.
