### ISSUE TITLE
Rename 'specifications'?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2091]
Bike shed alert!

![rowlinson-6-x-3-double-door-overlap-bike-shed-910](https://user-images.githubusercontent.com/261579/46987498-6ca84500-d0c2-11e8-91ee-1c65fd7e5fdb.jpg)

Like we had to settle on the distinction between 'checks' and 'tests', I think it gets a bit verbose to talk about "format specifications" (OT, UFO, etc) and our own "check specifications", which are simply sets of checks; I think it would be better to just have "specifications" referring to the former, and some other term...

* sets, check sets (I like this, but see next line)
* groups, check groups (not sure, maybe this is for a set of checks that is a subset of the parent object this list considers, even more so than above)
* profiles, check profiles (I like this)
* themes, check themes (hmm, not quite right)
* rolls, check roll (like voting rolls... must be the season... and a pun on the baking theme :) 
* bags, a big bag 'o' checks... (nah)

**Comment by graphicore** [comment]
> * groups, check groups (not sure, maybe this is for a set of checks that is a subset of the parent object this list considers, even more so than above)

We have already `Section` for that *"subset of the parent object"*.

I like "check profiles" most from your suggestions. How about just "checklists"?

**Comment by felipesanches** [comment]
An off-topic side thought here: while I understand the need for specific purpose specifications (or profiles), sometimes I think there should be a "universal collection of checks". That would be like the gold-standard of font checking, instead of the Google-flavour or Adobe-flavour or DaltonMaag-flavour of font-checking...

Then all vendor-specific profiles would include this common ground and build from there. Hopefully trying to keep the vendor-specific additions as minimal as possible. That way FontBakery's mission would be to improve this vendor-agnostic collection of font checks.

I know this consideration is off-topic here. But perhaps this thought can help us find a name that would also make sense in that scenario of a "universal font QA profile/spec/whatever".

**Comment by felipesanches** [comment]
also it is a bit weird that one cannot simply do `fontbakery *.ttf`. Instead one has to choose a specification. I think that can be unintuitive for new users. And also results in longer command lines such as `fontbakery check-googlefonts *.ttf`

I would imagine that calling fontbakery without specifying a specific specification (LOL) would cause the default "universal font QA" collection of checks instead of vendor-specific ones.

**Comment by felipesanches** [comment]
> We have already Section for that "subset of the parent object".

I have the impression that we either did not understand the usefulness of a Section as a mechanism to split a specification in parts, or that maybe that's not really much useful. The fact is that we haven't yet used more than a single Section per specification.

Should we drop that feature to simplify the infrastructure code? Or should we start using that?
If you think this will lead to a longer conversation, feel free to open a new issue to have a dedicated discussion about that.

**Comment by felipesanches** [comment]
From all terms suggested by Dave, the one I most liked was "profiles". The only potential nomenclature problem would be when discussing performance or memory-usage profiling. But that's not a big deal because it would be the kind of conversation that would only happen among us developers. So I think check profiles is good :-)

**Comment by davelab6** [comment]
I like checklist. Can it really be just a list of check IDs, with a
persistent disk representation as a plain text file with one check id per
line; and that filename (before the extension separator) of the txt file is
a valid ID so you can do nesting? Maybe a dict or tuple for the naming of
the [list]? :)

In terms of naming i think Section is fine for group and set, although if
nesting is really simple as above then I think it may not be needed. Lists
lists lists, let's try not to reinvent Lisp :)

Felipe, I initially think the golden one must be the OpenType Specification
one, because that's what truly everyone must agree on and be as a primary
concern, before going into their distributor-profile specific concerns. But
perhaps you are right that we should have a "best practices" checklist that
is all the stuff we know isnt specific to Google but just seems like a good
idea for everyone, like say underline values being the same across styles
in a family. However, I can see that the GF checklist is "opinionated" with
"one right way" on things where the wider type community has several
clusters of ways to do things; eg underline values could be uniform, or,
set to specific values for each style, but not left to editor defaults...

I also fear that still some of the GF checklist may be really OpenType
stuff...

Anyway, adefault checklist is a very good idea, too, as long as it's clear
to users that they are using the default one and that others are available.
Again I think initially that should be the ot spec checklist.

And yes I am in favor of even shorter shorthand commands, like gf or ot :)

**Comment by madig** [comment]
```
fontbakery *.ttf  # common profile
fontbakery --profile google *.ttf  # google profile
```

**Comment by davelab6** [comment]
fontbakery -p g *.ttf  # google profile short hand

**Comment by felipesanches** [comment]
yeah... ideally we could have both. This looks good.

**Comment by felipesanches** [comment]
`-p g` is very cryptic. But I can see that it may be practical for a user who knows what's being done.

But then, maybe the short one should be `-p gfonts` instead. (bikeshedding...)

**Comment by madig** [comment]
Having `-p` and `--profile` is idiomatic, but I wouldn't abbreviate `google`. 5 letters just aren't worth the cryptography.

**Comment by felipesanches** [comment]
yes, that's exactly what I meant. We agree :-D

**Comment by felipesanches** [comment]
The profile name would likely be exactly the name of the python source file. So where we nowadays have `Lib/fontbakery/specifications/googlefonts.py` we would then have `Lib/fontbakery/profiles/google.py`

**Comment by davelab6** [comment]
Sounds good. Bash completion is good enough anyways.

**Comment by graphicore** [comment]
> Or we revamp the CLI again.

Maybe `if the first arg is not a known command: command = 'check'`

**Comment by madig** [comment]
Todo: check if argparse supports that kind of thing.

**Comment by davelab6** [comment]
Good stuff
