### ISSUE TITLE
“Abstract” vs “concrete” requirements in setup.py and requirements.txt

### ISSUE THREAD

**Issue by cjchapman** [googlefonts/fontbakery#2174]
Currently `requirements.txt` has this version of `lxml`:
```
lxml==3.5.0
```
...but that version is three years old. The current version is 4.2.5.

**Comment by davelab6** [comment]
Change it to 3.5 or later?

**Comment by felipesanches** [comment]
https://caremad.io/posts/2013/07/setup-vs-requirement/

This article argues that we should prefer using `==` because that ensures we are shipping the thing we tested during development. So it would be better to change to `==4.2.5` and do the same to the other entries (replace any `>=` by `==`) and then make sure it passes all code-tests on travis with that selection of dependencies.

Running on newer versions of libraries may cause bugs that we did not catch with our test suite.

**Comment by davelab6** [comment]
Sounds good to me to keep == but then we need some kind of release
preflighting utility script for you to run that will remind you if anything
got stale

**Comment by chrissimpkins** [comment]
https://pyup.io/ will submit pull requests on the repo with new releases of all Python dependencies as they are released or it can be configured to submit all updated dependencies on a set schedule.  It pins the current modified release version in requirements.txt in the PR.  Shouldn't be necessary to create a prompt from scratch as long as you don't mind the PR maintenance.

**Comment by davelab6** [comment]
Love it

**Comment by chrissimpkins** [comment]
Most of the setup process is automated.  Just make sure that the requirements.txt file is up to date and pyup will submit an initial PR on the repo with the configuration file, then get ready to open up the firehose :)  Cosimo generally sets it to weekly updates (and introduced me to pyup).  I have followed suit with that schedule.  Real-time PR submissions at dependency releases gets tedious for maintainers.  It will close outdated PR's when a new dependency version is released over an existing open PR so you can let them sit there until you are ready to deal with them, but this may cause quite a bit of traffic in this project where there are a significant number of Python dependencies.

**Comment by anthrotype** [comment]
The issue here really boils down as to whether fontbakery is primarily a “library” or an “application”, borrowing the terms from the above mentioned article from Donald Stufft.
If it is both, then it needs to maintain the flexibility of setup.py (only abstract dependencies), while at the same time devise a way to distribute the application to production environments with concrete, exact versions of dependencies.
In fontmake I experimented with shiv, a tool that creates self-contained zipapps bundling a python application with its entire virtual env of dependencies, which only need python3 installed to run. I automatically publish this fontmake.pyz apps on the github releases page when I push a new tag.
You could also use pyinstaller and not even require python to be installed. But that’s more heavy weight, in my opinion, and you can assume that a font dev machine will have python3 nowadays.

**Comment by anthrotype** [comment]
Another way to ensure reproducibility would be to install fontbakery not as `pip install fontbakery` off PyPI, but instead git clone the fontbakery repo (or download/unzip the tarball) then cd into it and `pip install -r requirements.txt -e .` (you could add the final `-e .` as the last line of your requirements.txt file, so you only need to do `pip install -r requirements.txt`).
We actually use this simple approach in the noto-source repo.

**Comment by anthrotype** [comment]
Before others mention it, there is also this new pipenv tool which is supposed to solve this sorts of issues, but I haven’t really used myself so don’t feel confident recommending it to others.
https://github.com/pypa/pipenv

**Comment by anthrotype** [comment]
Perhaps to distribute fontbakery as standalone application with deterministic dependencies and simplify installation instructions, you could use Homebrew (which is also available for Linux as linuxbrew). You could automate updating the homebrew formula at every release by running some CI script. The black autoformatter does that, for example.

**Comment by felipesanches** [comment]
thanks for the feedback, @anthrotype. I will read it all carefully and then decide what to do.

**Comment by felipesanches** [comment]
I hope this is good enough for this Monday's release. What do you think, @anthrotype?
