### ISSUE TITLE
GF Check 116 should include option for UPMs with powers of 2, not only UPMs of 1000

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2185]
## Observed behaviour

Google Fonts check 116 is:

```
"Is font em size (ideally) equal to 1000?"
```

However, the MS Typography OpenType [`head` table spec](https://docs.microsoft.com/en-us/typography/opentype/spec/head) says:

> **unitsPerEm:** Set to a value from 16 to 16384. Any value in this range is valid. In fonts that have TrueType outlines, a power of 2 is recommended as this allows performance optimizations in some rasterizers.

Most type design advice suggests drawing at UPM 1000, and it makes sense to advise that for type on Google Fonts, as well. However, It is very common for TTF fonts to have a UPM of 2048, and the spec confirms that it may actually be slightly better for TTFs to be in a power of 2.

## Expected behaviour

I propose that we update the check:
- If the font has a UPM that is _either_ 1000 _or_ a power of 2 (128, 256, 1024, 2048), this check should be a "Pass"
- If we still wish to recommend that fonts at a power of 2 be changed to 1000 for ease of collaboration, this could instead be an "Info" flag

The new text might read something like:

```
"Is font em size (ideally) equal to 1000 or a power of 2 between 16 and 16384 (e.g. 2048)?"
```

It is a bit of a mouthful, but I believe the increased accuracy would make this a more useful check.

**Comment by davelab6** [comment]
I don't think we want above 2048, because higher upm increases filesize without benefit. 

In Amstelvar it's 2000 to get less rounding errors while keeping upm arithmetic possible for humans, and I think we should standardize on that for all VFs.

**Comment by thundernixon** [comment]
I'm with you on avoiding anything above 2048. Maybe this could be

```
"Is font em size (ideally) equal to 1000 or a power of 2 between 16 and 2048?"
```

16 would be extremely low, but I could maybe see it being used for pixel fonts.

**Comment by davelab6** [comment]
Yep, sounds good.

**Comment by davelab6** [comment]
So a FAIL if outside 16, 32, 64, 128, 256, 500, 512, 1000, 1024, 2000,
2048, and a WARN if outside 2000?

**Comment by m4rc1e** [comment]
Just came across this issue for a font which has a upm of 2,000. I agree with your above values.

Imo, this test is pretty pointless. It's nice to know that a font has a upm which is consistent with other fonts. However, there's nothing wrong with having a font which has a upm of 512 or even 500.

Turn this into just a warn please.

**Comment by davelab6** [comment]
For VFs I want to fail at anything but 2000, though, because with VFs we
have an opportunity to set standards that will juice collaboration

**Comment by davelab6** [comment]
With 1000 being standard, when you open a font to work on it, you have a sense of what 10 or 100 UPM units means in typography. 

Since TT outlines are all int only, no floats, then instances in a VF suffer rounding compromises, and therefore a 1000 UPM is to small because it forces too many such compromises. 

Therefore 2000 is a good 'new VF standard', because 2000 is a simple 2x conversion from existing fonts drawn on a 1000 UPM, and anyone who knows what 10 units can do for 1000 UPM will know what 20 units does too.

Since we ARE converting almost all fonts to VF, I don't even see an issue even with fonts only available on a UPM that is a power of 2; there will be some rounding, but since the whole design is being finely checked, any issues can be corrected.

A FAIL is just, like, Font Bakery's opinion, man ;) We can always override and accept FAILs, and many checks - like this one - should probably be in the gf-glyphs-scripts checker so that these things are caught early.

**Comment by felipesanches** [comment]
This affects two checks:
* **[com.google.fonts/check/043]:** `"Checking unitsPerEm value is reasonable."` (opentype FB-profile)
* **[com.google.fonts/check/116]:** `"Is font em size (ideally) equal to 1000?"` (googlefonts FB-profile)

**Comment by felipesanches** [comment]
I made the check from the OpenType profile (check/043) only FAIL when a upm value is actually invalid according to the spec.

And I reimplemented the check from the Google Fonts profile (check/116) to have the stricter set of rules to be enforced on gfonts.

**Note:** I really like the "profiles" nomenclature (instead of talking about "FB specifications")!

**Comment by davelab6** [comment]
For 0.7 we should do the rename to profiles and prioritize all checks better
