### ISSUE TITLE
com.google.fonts/check/011 is too terse

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2196]
## Observed behaviour

From http://35.225.170.228/report/d8819464-9208-46cd-9151-903dfd0f4b93 I see

```
com.google.fonts/check/011 Fonts have equal numbers of glyphs?

FAIL  None has 281 glyphs while Light has 282 glyphs.
FAIL  Medium has 281 glyphs while Light has 282 glyphs.
```

## Expected behaviour

- [x] Tell me which glyph is missing! (I guess this maybe what @madig meant in #1685)
- [x] while I'm looking at `Family-Light.ttf` I see `None has` which is bad

**Comment by felipesanches** [comment]
@davelab6 "None" is likely caused by a non-canonical font name. I can add a conditional to filter that out. But I would like to be sure that's the real root cause of the problem.

Can you tell me where are the font files that were used in that drag-n-drop dashboard run? I would like to replicate the issue here.
