### ISSUE TITLE
New check: Does METADATA.pb parse correctly?

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2248]
## Observed behavior

If the `copyright` field of `METADATA.py` contains any double quote marks `"`, this substring is incorrectly interpreted as its own metadata field.

**Example**

In Encode Sans, the copyright field was:
```
Copyright 2018 The Encode Project Authors (impallari@gmail.com), with Reserved Font Name "Encode Sans".
```

This caused all Metadata checks to fail with the message: "**ERROR** The condition <FontBakeryCondition:family_metadata> had an error: ParseError: 14:105 : Message type "google.fonts.FontProto" has no field named "Encode"."

(I know that most fonts aren't supposed to have Reserved Font Names, but Encode Sans is an exception to this).

However, if I change the copyright field to:
```
Copyright 2018 The Encode Project Authors (impallari@gmail.com), with Reserved Font Name 'Encode Sans'.
```
...with single quotes, the FontBakery error is not triggered. 

## Expected behavior

I would expect `FontProto` to handle or escape either type of quotes inside substrings. 

This probably isn't the highest-priority issue, and it's easy enough to get past as a FontBakery user. However, it was confusing at first, and seems likely to confuse others in the future.

## Resources and exact process needed to replicate

The errors can be seen by running FontBakery on [the latest Encode Sans Regular VF file](https://github.com/thundernixon/Encode-Sans/tree/94094a0f33b01cc255db2b9ea5cca1eb5f271c0d/fonts/encodesans).

**Comment by felipesanches** [comment]
This really seems to be an invalid syntax problem. Since the copyright field is a string using the double-quote delimiter, the same char(double quotes) should not be used in the string itself, unless it was escaped.

The METADATA.pb file must be fixed.
But I agree that this should not have caused an ERROR, but a FAIL instead. I think that for this kind of problem a check_metadata_parses check would be very helpful.

**Comment by felipesanches** [comment]
This was also requested at #2200

**Comment by felipesanches** [comment]
Also, this could be acchieved by wrapping the body of the metadata condition with a try block and returning None in the case of a parsing error exception. Then this would avoid all checks that depend on Metadata from running if it is not parsing correctly.

The check that ensures it parses correctly would then invoke the condition method in order to report that.

**Comment by thundernixon** [comment]
Okay, that makes sense. The add_font.py script may do this correctly. For now, it doesn't yet work for variable fonts, so I was generating it by hand, and just copying in values. Thanks for the quick response!
