### ISSUE TITLE
[code-test] com.google.fonts/check/name/license_url - "License URL matches License text on name table?"

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2310]
<img width="642" alt="captura de tela 2019-01-31 as 11 03 02" src="https://user-images.githubusercontent.com/213676/52055895-d05a5f00-2547-11e9-828e-117af0810c99.png">

**Comment by vv-monsalve** [comment]
On last FB checks performed with v.0.7.28 this Warn has been reported:
<details>
<summary>⚠ <b>WARN:</b> License URL matches License text on name table?</summary>

* [com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url)
<pre>--- Rationale ---

A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry
of the name table.

The source of truth for this check is the licensing text found on the NameID 13
entry (LICENSE DESCRIPTION).

The string snippets used for detecting licensing terms are:
- &quot;This Font Software is licensed under the SIL Open Font License, Version 1.1.
This license is available with a FAQ at: https://scripts.sil.org/OFL&quot;
- &quot;Licensed under the Apache License, Version 2.0&quot;
- &quot;Licensed under the Ubuntu Font Licence 1.0.&quot;


Currently accepted licenses are Apache or Open Font License.
For a small set of legacy families the Ubuntu Font License may be acceptable as
well.

When in doubt, please choose OFL for new font projects.


</pre>

* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=1, enc=0, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=1, enc=0, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=1, enc=0, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=1, enc=0, name=14] [code: http-in-license-info]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=14] [code: http-in-license-info]
* ⚠ **WARN** For now we're still accepting http URLs, but you should consider using https instead.


</details>

The Warn and the rationale were not really clear especially given the tested fonts had the traditionally used "http://scripts.sil.org/OFL" value on LicenseURL custom parameter, and despite that, the Warn wasn't on previous FB versions.

## Expected behavior

Having a clearer or simpler explanation of what has changed, particularly the change to htpps. Maybe just moving above the line: _"For now we're still accepting http URLs, but you should consider using https instead"_ leaving the detailed explanation on licensing and name ID13 below.

P..S. Not quite sure if this is strictly related to the purpose of this Issue, but I preferred to comment this here before opening a new issue

**Comment by m4rc1e** [comment]
Many issues are reported involving these checks. They definitely need some tlc.

Neither of the checks should depend on one another. I'd prefer it if we just had a single license check which checked both records at the same time. should make our lives much easier.
