### ISSUE TITLE
VendorID check fails if URL not available

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2359]
## Observed behaviour

Someone wrote me privately,

> I tried out fontbakery today (out of sheer curiosity) and I noticed that it complained about my VendorID saying it is not valid (while it was registered last year). In my vendor entry there's no URL though, maybe that's the reason?

## Expected behaviour

VendorIDs without URLs should still be accepted, but perhaps a WARN should be returned reminding the vendor to register a URL with Microsoft.

**Comment by felipesanches** [comment]
The code-test that I implemented today ensures that a vendor id without a URL will be properly parsed from the HTML o Microsoft's website. I did not change the check implementation in order for this new code-test to pass, so it means the implementation was not flawed in that aspect.

So there must be some other reason for the vendor ID not being recognized. I guess that's because our cache was a bit outdated. I have updated the cache and now hopefully the vendor ID will be recognized. @davelab6, please ask the user.

In order to make sure we always keep it up-to-date I have added a note to the release instructions at https://font-bakery.readthedocs.io/en/latest/maintainer/maintainer-notes.html#updating-the-distribution-package

I presume these measures fixed the problem, so I will close this issue. If the problem persists, please re-open it.
