### ISSUE TITLE
Add GlyphsApp advice to com.google.fonts/check/usweightclass

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2423]
## Observed behaviour

FiraCode had an issue in which it's Light default instance wasn't being reflected in the OS/2 table:

> 🔥 <b>FAIL:</b> Checking OS/2 usWeightClass.</summary>
> 
> [com.google.fonts/check/usweightclass](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/usweightclass)
> 🔥 **FAIL** OS/2 usWeightClass expected value for 'Light' is 300 but this font has 400.

In https://github.com/googlei18n/fontmake/issues/540, I discovered that it is necessary to set the `Axis Location` custom parameter in the FiraCode GlyphsApp source.

## Expected behaviour

Some FontBakery checks, such as [com_google_fonts_check_usweightclass](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/profiles/googlefonts.py#L759) suggest fixes for GlyphsApp users. This is very helpful, and it's something we could do in this OS/2 check, as well.

We could include advice something like this:

> 🔥 <b>FAIL:</b> Checking OS/2 usWeightClass.</summary>
> 
> [com.google.fonts/check/usweightclass](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/usweightclass)
> 🔥 **FAIL** OS/2 usWeightClass expected value for 'Light' is 300 but this font has 400. GlyphsApp users should set a Custom Parameter for 'Axis Location' in each master to ensure that the information is accurate built into variable fonts.

**Comment by felipesanches** [comment]
This was a quite simple issue to fix. Sorry that it took so long, @thundernixon

**Comment by anthrotype** [comment]
actually, i'm afraid it's not that simple, as I have also attempted to explain in the linked fontmake issue.

Yes, adding "Axis Location" custom parameter to all masters (assigning a user-space location when that is different from the internal design location) effectively also sets the OS/2.usWeightClass to the generated master TTFs, including the default master that is going to be used as the base font when building up the variable font in fonttools.

But it also has other effects. In glyphsLib (i.e. the library that is responsible for converting the Glyphs source file to a set of master UFOs + designspace document, which are then used to build the interpolatable master TTFs and finally variable font), the presence of "Axis Location" custom parameters (which were introduced relatively recently in Glyphs.app) triggers an alternative code path which has some limitations and may not always be the best thing to do.

Before these "Axis Location" master custom parameters were introduced, the user-space location of the masters were inferred from the instances' user-space locations. E.g. if an instance has the same internal design location as one master, then the instance's user-space location is used for the master as well (e.g. instance is "Bold" so its OS/2.usWeightClass is 700, hence also the corresponding master is understood as having OS/2.usWeightClass=700).

The mapping from user-space to internal design locations is exported in the DesignSpace document's axes `<map>` elements, which are used to build the variable font's "avar" table. The latter allows to specify a non-default coordinate normalization from user coordinates (fvar's) to internal normalized coordinates (-1..0..+1 scale used by variation tables).

Now, it's good to be able to assign explicit user-space coordinates to the _masters_ using "Axis Location" custom parameters, so that they don't have to be inferred from the instances. This allows to use a master without needing to have a corresponding named instance at the same coordinate.
But this new method only allows to assign user-space coordinates to the masters, and not also to the intermediate steps in between the masters as the other method (that infers from the instances) allowed.

In Noto sources, we do not use "Axis Location" custom parameters for two reasons: 1) these mostly predates the introduction of this new custom parameter in Glyphs.app; 2) we have intermediate steps in between masters to which we have to assign some user-space coordinates that are not identical to the linearly-interpolated coordinates that would be computed if the expilict mappings weren't there.

The situation with Fira Code is a bit different from Noto in this sense that its default master is not Regular (wght=400) but Light (wght=300). Thus the variable font which is built off that will inherit the default master's OS/2.usWeightClass.

We have suggested the Glyphs.app developer to introduce a new font-wide custom parameter called "Axis Mapping" that can translate more closely the DesignSpace axes maps, allowing to define arbiratry mappings within an axis range, and not necessarily tying these to the masters (nor having to infer them from instances).

https://github.com/googlefonts/glyphsLib/issues/483

Actually now I'm thinking that fontTools.varLib should set the correct OS/2.usWeightClass on the variable font if it was not already correctly set on the default master TTF, since it has all the information for that in the designspace document... I'll open an issue on fonttools repo about that.

**Comment by schriftgestalt** [comment]
I don’t fully understand the different code paths. But is seem to me that `Axis Location` could be used to set the axis ranges in the fvar table and the location+weight/width setting of the instances could be used to produce an avar table?

**Comment by anthrotype** [comment]
you're suggesting to sort of merge the two approaches. The problem with that is that it is possible to end up with a situation where the user-locations of masters (as defined by Axis Location) and instances (as defined by their Weight and Width classes for the first two registered axs) be different, when in fact these _must_ be the same whenever masters and instances are located on the same internal design coordinate along a given axis.

Having a separate "Axis Location" (and deprecating "Axis Location") would be better in my opinion.

**Comment by anthrotype** [comment]
BTW, the next version of fontTools will make sure that the OS/2 weight/width classes (and post.italicAngle) of the generated VF will be the same as the fvar.axes default coordinates respectively for wght, wdth and slnt axis.

https://github.com/fonttools/fonttools/pull/1652

I recommend Felipe to revert the change in https://github.com/googlefonts/fontbakery/pull/2555, because the recommendation may soon be outdated since there are plans of dropping the use of Axis Location. 
Also that fontbakery check itself doesn't have anything to do with variable fonts, but simply checks that a predefined style name matches the respective weight or width classes. Whereas Axis Location is specific to variable fonts, and it's just a side-effect that setting that parameter fixes the mismatch between style name and weight.
