### ISSUE TITLE
Need variable default presubmit checks

### ISSUE THREAD

**Issue by andyjgf** [googlefonts/fontbakery#2683]
## Observed behaviour

The default values of 100 for weight here:

https://github.com/google/fonts/commit/f4c4f1fcbc0d4ec0a194848c1d9683157e3e783e#diff-3ea59a8146af02854e2777c00c1c116f

Broke the Google Fonts data push:

Seeing this error: PublicSans-Italic[wght].ttf[Variable Font METADATA.pb weight class (100) isn't at the point nearest 'wght' default (400)

I changed the default to 400, which fixed things.

## Expected behaviour

This error should be caught before it gets to Google Fonts.

## Resources and exact process needed to replicate

I can help with testing on the Google Fonts side.

**Comment by m4rc1e** [comment]
This has happened before so I'd like some clarification.

**Current setup:**
When we run `gftools add-font` on a font family, it will set the weight values in the `METADATA.pb`  so they're the same as each font's `OS/2 usWeightClass` value. Since many variable fonts do not contain a Regular master, the default master is often a Thin or Light (this is the case for Public Sans). This means these fonts have a `usWeightClass` of 100 which then generates us a METADATA.pb weight of `100`.

So I'm wondering, should all variable font families set the METADATA.pb weight value to 400?

**Comment by nathan-williams** [comment]
I can only speak to how things are configured today. We have checks in place that require the default weight to be 400 if that is in the weight range, or else, the available fallback weight nearest to 400 (e.g. 100, 200, ... 900).

**Comment by m4rc1e** [comment]
Thanks @nathan-williams. Just for clarity, Rod recently [removed](https://github.com/google/fonts/pull/2212) the `default_value` from our VF  METADATA.pb files. Since these are now gone, I'm assuming that each METADATA.pb font's weight value should now be set to 400 since all our VFs do pass through 400?


e.g

```
  
name: "Kreon"
designer: "Julia Petretta"
license: "OFL"
category: "SERIF"
date_added: "2011-02-02"
fonts {
  name: "Kreon"
  style: "normal"
  weight: 300 <----------------------------- This should now be 400?
  filename: "Kreon[wght].ttf"
  post_script_name: "Kreon-Light"
  full_name: "Kreon Light"
  copyright: "Copyright 2018 The Kreon Project Authors (https://github.com/googlefonts/kreon)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
axes {
  tag: "wght"
  min_value: 300.0
  max_value: 700.0
}
```

**Comment by nathan-williams** [comment]
Sorry for the late reply. That's correct, Marc!

**Comment by davelab6** [comment]
The issue is that the "API default" is 400 but the 'zero origin' will often not be 400. 

https://github.com/googlefonts/gf-docs/tree/master/Spec#font-zero-origin

https://github.com/undercasetype/Fraunces/issues/174#issuecomment-612296158

**Comment by davelab6** [comment]
> all our VFs do pass through 400

That is not guaranteed; there are some families in the github.com/google/fonts repo today for which this is not true. 

Therefore as Nate said, the default weight should be 400 **if that is in the weight range,** or else, the available fallback weight (which means, a multiple of 100 between 100 and 900) nearest to 400.

**Comment by davelab6** [comment]
@m4rc1e what do you propose to resolve this issue? :)

**Comment by m4rc1e** [comment]
We could alter Fontbakery's metadata weight check so it doesn't use the usWeightClass value of the VF (current behaviour) but instead it uses 400 if the VF's wght range includes it or the closest value to 400 if it doesn't.
