### ISSUE TITLE
Failing License URL check with OFL License Set

### ISSUE THREAD

**Issue by coreywho** [googlefonts/fontbakery#2746]
## Observed behaviour
https://fontbakery.graphicore.de/report/7fa963bb-6a61-4f79-8da1-c6617669bce4

## Expected behaviour

I've checked the name table and NameID 13 is set to "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL"

NameID 14 is set to "https://scripts.sil.org/OFL"

## Resources and exact process needed to replicate

Uploaded an example for reference.
[Urbanist-Black.ttf.zip](https://github.com/googlefonts/fontbakery/files/4116769/Urbanist-Black.ttf.zip)

**Comment by felipesanches** [comment]
Apparently, you did not upload a license file to the FontBakery Dashboard.

**Comment by felipesanches** [comment]
I think there may be more going on here.

The check we're discussing here is **com.google.fonts/check/name/license_url** and it should not depend on the presence of a license file since it only validates whether or not fields in the name table are coherent ammong themselves.

**Comment by felipesanches** [comment]
Using your font file, I was unable to replicate the problem here.

This is what we see in the FontBakery Dashboard log:
![Screenshot from 2020-01-29 01-12-26](https://user-images.githubusercontent.com/213676/73327442-ce97aa00-4234-11ea-9151-79bb250d24eb.png)

And this is what I see when running FontBakery locally on your font file:
![Screenshot from 2020-01-29 01-13-57](https://user-images.githubusercontent.com/213676/73327450-d6efe500-4234-11ea-810b-2ebe668a7359.png)

**Comment by felipesanches** [comment]
oh wait! The check passes for me because I am using the development version in which the check was fixed to accept both http and https in license URLs. But the dashboard is using v0.7.17 which is the latest released version.

Running v0.7.17 here I was able to replicate the issue.

Since it is fixed already, it is only a matter of waiting until the v0.7.18 release (and have that integrated into the dashboard)

@graphicore please consider updating to fontbakery v0.7.18 next week once I release it.

**Comment by graphicore** [comment]
Thanks. @felipesanches sure, I will update.
