### ISSUE TITLE
Add Check (VF): All fonts in a family MUST have the same axes and supported ranges

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2810]
## Observed behaviour

Cabin was upgraded to a VF (https://github.com/impallari/Cabin/pull/20) but the variable font files in the family did not (as of 2020-04-01) have the same axes and supported ranges of those axes; because the legacy 'Cabin Condensed' family had no italics. 

We should have a GF profile VF check for this that FAIL's the current family.

**Comment by felipesanches** [comment]
The description is a bit unclear so I will try to write down here my understanding of the problem.

It seems to me that @davelab6 is asking for a new check with the following description:

"Ensure that the Roman and Italic variable font counterparts have the same set of axes and axis ranges"

Is that what you need, Dave?

Also, what's the reasoning for that requirement? Is that needed in order to build more consistent user interfaces for interaction with the VFs? Or some other google-specific rationale?

**Comment by eliheuer** [comment]
I think it's not just Roman and Italic, something like Compacta and Compacta Outline should also have the same axes and supported ranges, I think?

**Comment by m4rc1e** [comment]
Eli is correct.

**Comment by felipesanches** [comment]
great, thanks!

**Comment by felipesanches** [comment]
![Screenshot from 2020-04-03 03-37-06](https://user-images.githubusercontent.com/213676/78331450-6c249800-755c-11ea-8641-8a66ff99072f.png)
