### ISSUE TITLE
"Checking OS/2 usWeightClass." gives incorrect/outdated advice for Glyphs users

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2859]
## Observed behaviour

In https://github.com/google/fonts/pull/2438, I ran into this issue:

> 🔥 FAIL: Checking OS/2 usWeightClass.
>     com.google.fonts/check/usweightclass
> 
> 🔥 FAIL OS/2 usWeightClass expected value for 'Condensed Thin' is 250 but this font has 400. GlyphsApp users should set a Custom Parameter for 'Axis Location' in each master to ensure that the information is accurately built into variable fonts. [code: bad-value]

However, I have found that adding `Axis Locations` to masters _breaks_ axis mapping that is derived from the Instance data. That is, instances in the middle gain incorrect `wght` values like `790.0234`, etc.

In the current version of FontMake, the `usWeightClass` is being accurately set without Axis Locations specified.

See https://github.com/googlefonts/fontmake/issues/543#issuecomment-621951478 for a thread with details.

## Expected behaviour

At minimum, we should remove the incorrect suggestion, as it causes bigger issues.

**Comment by anthrotype** [comment]
it;s not that it is incorrect or outdated. It is still correct, the problem is using Axis Location on the masters (because only masters can have that parameter as far as I know) will create mappings for those, but will _not_ also create mappings for the instances' user:design maps, which means they will be linearly interpolated in-between those explicit mappings for the masters.

Without Axis Location params, fontmake will use the instances user and design locations to determine the mappings - but that also has a problem, because this solution only works for Weight and Width (for which instances have user-space values), but not for other axes.

In my view, we should deprecate Axis Location and only use the new Axis Mappings (a font custom parameter, thus not restricted to either masters only like Axis Location, or instances), and which can more easily translated into the equivalent Designspace axes map elements.

But from conversations with Georg it seems we have diverging interpretations of how the new custom parameter should be understood, which complicates the matter further as we can't go on and implement something that is at odds with the way Glyphs.app itself implements it..

Any help districtating this matter is appreciated.
Follow on https://github.com/googlefonts/glyphsLib/issues/568

**Comment by m4rc1e** [comment]
I recently updated this check in #2916 

I ended up removing the glyphsapp fix instructions because setting axis locations may not solve this issue.
