### ISSUE TITLE
New temporary check: Ensure VFs do not contain opsz or ital axes

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#2866]
We recently pushed a VF which contains an ital axis. This axis isn't supported yet in chrome. The opsz axis also has patchy support.

For the time being, we need to ensure that VFs do not contain either of these axes. Once browser support is better, we can disable this check.

Here's the initial google/fonts issue, https://github.com/google/fonts/issues/2445

For more info regarding ital and opsz browser support, see https://arrowtype.github.io/vf-slnt-test/

**Comment by m4rc1e** [comment]
Thanks!

**Comment by davelab6** [comment]
@m4rc1e What is your concern about optical size support?

**Comment by felipesanches** [comment]
@m4rc1e is on an European timezone and it is Friday night there already by now. So, please don't worry too much about this issue for now as we can expect Marc will likely clarify his reasoning early next week.

**Comment by felipesanches** [comment]
If I recall correctly, @tphinney also had questions about the reasoning behind this check.

**Comment by laerm0** [comment]
I'm curious as well.

**Comment by felipesanches** [comment]
@m4rc1e, @tphinney, could you add your thoughts here, please?

**Comment by m4rc1e** [comment]
Our api only support VFs which have 11 in their opsz range e.g 11-72, 9-48 etc. 12-72 wouldn't work. Blocking seems overkill so apologies for that.

If we do push new fonts which don't have the correct range. I simply remove the opsz axis in the METADATA.pb file. The api should eventually support all ranges.

I still think ital and slnt should be disabled since browser support is lacking.

**Comment by felipesanches** [comment]
> I still think ital and slnt should be disabled since browser support is lacking.

@m4rc1e, Is this still true nowadays?

**Comment by m4rc1e** [comment]
It's probably gotten better but many users may still be using the affected browsers.

**Comment by felipesanches** [comment]
@m4rc1e, I know it was a long time ago, but back in May, 2020 you said "Blocking seems overkill so apologies for that." right after I applied the `Blocked - waiting for some feedback` label. I would like to clarify that I use this label to signal that my work on a given issue is temporarily blocked while I wait for someone else to provide further info. It does not mean that I refuse to work on that or even that the implementation of the new check proposal is arbitrarily blocked.

I'm just saying this because I will probably continue using this label in other issues and I wanted to have its meaning explicitly clarified to avoid future confusion.
