### ISSUE TITLE
Lint codebase with pyre?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3014]
https://github.com/facebook/pyre-check/ might be helpful to catch some bugs

**Comment by graphicore** [comment]
I agree, but we'd have to use type hints for this, otherwise there's nothing to check. I think the default. not hinted type, is always `any`. I used type hints (checked with [`mypy`](http://mypy-lang.org/)) in `gftools packager` it's definitely helpful, especially when the linter runs in the editor and one gets direct feedback.

**Comment by simoncozens** [comment]
Duplicate(ish) of #1824.
