### ISSUE TITLE
Setting ligature caret position in Robofont?

### ISSUE THREAD

**Issue by sponcey** [googlefonts/fontbakery#3019]
This warn of the ligature caret position gives instructions of how to do this in Glyphs. Are there any open source examples of how to do this with projects built from .ufo's/Robofont? Maybe @thundernixon knows about this? ;)

> ⚠ WARN: Are there caret positions declared for every ligature?
> com.google.fonts/check/ligature_carets
> --- Rationale ---
> 
> All ligatures in a font must have corresponding caret (text cursor) positions
> defined in the GDEF table, otherwhise, users may experience issues with caret
> rendering.
> 
> If using GlyphsApp, ligature carets can be set directly on canvas by accessing
> the `Glyph -> Set Anchors` menu option or by pressing the `Cmd+U` keyboard
> shortcut.
> 
> 
> ⚠ WARN GDEF table is missing, but it is mandatory to declare it on fonts that provide ligature glyphs because the caret (text cursor) positioning for each ligature must be provided in this table. [code: GDEF-missing]

https://github.com/undercasetype/Fraunces/issues/220

**Comment by felipesanches** [comment]
Thanks for posting this issue, @sponcey! I fully agree that FontBakery should include tips for multiple font editors. I dislike making it GlyphsApp-biased, especially since Glyphs is proprietary. The reason we included this was because it is one of the most commonly used editors, even for libre fonts, which is a cultural contradiction from the point of view of the software freedom movement (which I am strongly aligned to), but it a sad reality of the type-design industry nowadays.

At least glyphs files can be perfectly compiled into font binaries with a fully-free toolchain (**fontmake** and auxiliary post-processing scripts like the ones offered by **gftools**).

At first, I'd add multiple instructions to check rationales, but later we could consider auto-detecting which font editor was used on a given project and then give the user the appropriate instructions.
