### ISSUE TITLE
Escaped strings metadata.pb check fails badly if there is no metadata.pb

### ISSUE THREAD

**Issue by tphinney** [googlefonts/fontbakery#3095]
## Observed behaviour

If there is no metadata.pb file, the escaped strings check fails with a TypeError (NoneType)

>  >> com.google.fonts/check/metadata/escaped_strings
>     Ensure METADATA.pb does not use escaped strings.
>     with GoogleMaterialIcons-Bold.ttf
> 
>       Rationale:                                                                
>       In some cases we've seen designer names and other fields with escaped     
>       strings in METADATA files.                                                
>       Nowadays the strings can be full unicode strings and do not need          
>       escaping.                                                                 
> 
>     * ERROR: Failed with TypeError: expected str, bytes or os.PathLike object, not NoneType
>            File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fontbakery/checkrunner.py", line 366, in _exec_check
>              for sub_result in result:  # Might raise.
>            File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fontbakery/profiles/googlefonts.py", line 4911, in com_google_fonts_check_metadata_escaped_strings
>              for line in open(metadata_file, "r").readlines():
>          
> 
> 
>     Result: ERROR

## Expected behaviour

No TypeError; maybe an error or warning that there is no METADATA.pb file

## Resources and exact process needed to replicate

I believe you can get this on any source without the expected file. If not, I can do some digging.

**Comment by aaronbell** [comment]
I ran into this issue as well.

```
def com_google_fonts_check_metadata_escaped_strings(metadata_file):
    """Ensure METADATA.pb does not use escaped strings."""
    passed = True
    for line in open(metadata_file, "r").readlines():
        for quote_char in ["'", "\""]:
            segments = line.split(quote_char)
            if len(segments) >= 3:
                a_string = segments[1]
                if "\\" in a_string:
                    passed = False
                    yield FAIL,\
                          Message('escaped-strings',
                                  f"Found escaped chars at '{a_string}'."
                                  f" Please use an unicode string instead.")
    if passed:
        yield PASS, "OK"


@check(
    id = 'com.google.fonts/check/metadata/designer_profiles',
    conditions = ['family_metadata']
)
```

It appears the check does not evaluate if there is a METADATA file present. 

I guess my question would be—is a METADATA.pb file required?

**Comment by felipesanches** [comment]
yes, a METADATA.pb is required on the `googlefonts` profile.

**Comment by aaronbell** [comment]
A follow up question. In reviewing the Google Fonts spec, it seems that the [METADATA file is not necessary for an upstream repository](https://github.com/googlefonts/gf-docs/tree/master/Spec#repository-structure) and is rather only needed for the google/fonts repository when the font is being pushed to prod. 

Given that fontbakery can (and often is) used by folks just testing their fonts, rather than being at the 'push to prod' stage, would it make sense to check for other indicators that the font is being prepped for production, such as the presence of the `ofl` / `ufl` / `apache` folders? Or perhaps removal of the `documentation` folder? 

Or perhaps there is some other way to help inform folks of the `FAILS` related to being at a development stage vs a production stage?

**Comment by felipesanches** [comment]
Nowadays the `googlefonts` profile contains checks aiming at preparing a font family for inclusion in the collection and, for that reason, it requires these "production stage" files such as `METADATA.pb` and `DESCRIPTION.en-us.html`.

We do not have a profile focused on "development stage of a font that will later be submitted to the Google Fonts collection". Not sure if we should. In general I believe that things should ideally be fixed as soon as possible, during development, instead of being left to be addressed only on the last minute on the "final production stage".

**Comment by aaronbell** [comment]
> In general I believe that things should ideally be fixed as early as possible, during development, instead of being left to be addressed only on the last minute on the "final production stage".

For sure. That's why I figure it is useful to have the checks earlier in the process rather than at the last minute :). For reference, the reason why I ask is because I'm running fontbakery on upstream font repositories to make sure that I've corrected any issues in the font file itself. If I didn't understand that there's a difference between upsteam repository requirements and prod requirements, I might get confused why I'm getting a fail even though I'm following the [guidance in the Google Spec](https://github.com/googlefonts/gf-docs/tree/master/Spec#upstream-repo-structure).

**Comment by felipesanches** [comment]
I've just fixed the problem. It was a rather simple solution, but since this seems to affect many users in their continuous integration setups, I will cut a new release to ensure work can continue without further disruption from this bug.
