### ISSUE TITLE
[googlefonts] new check: mandatory avar table

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3100]
In this twitter conversation @davelab6 wished for a fontbakery check on the `googlefonts` profile to make **avar** table mandatory:
https://twitter.com/davelab6/status/1331698384743387138

![Screenshot from 2020-11-25 17-40-21](https://user-images.githubusercontent.com/213676/100279540-85dc7a80-2f45-11eb-8866-23bdc6dffe02.png)

**Comment by felipesanches** [comment]
Any further thoughts here, @simoncozens? We'd need to craft a more detailed rationale text to justify the strong requirement. How can we word this as a new policy for the Google Fonts collection? It should be written in a way that sounds convincing to the type-designers reading it, instead of sounding like an arbitrary requirement.

**Comment by davelab6** [comment]
"All high quality variable fonts include an avar table to correctly define axes progression rates. For example, a weight axis from 0% to 100% doesn't map directly to 100 to 1,000, because a 10% progression from 0% may be too much to define the 200, while 90% may be too little to define the 900."

**Comment by tiroj** [comment]
How are 'mandatory' and 'strong requirement' defined for Google Fonts?

I can imagine variable fonts in which an avar table would not be a technical requirement based on how they are designed and intended to function, and hence in which an avar table would, at best, provide redundant data. For example, a font that only contained a wdth axis might not need an avar table, since the percentage scale of width variation is linear.

That said, I would expect almost any implementation of wght axis to require avar to handle non-linear progression of cardinal instances in the design space, and opsz often benefits from more rapid variation at smaller sizes, getting slower as the size increases.

**Comment by felipesanches** [comment]
I've implemented the check, as requested by @davelab6 so I'll close this issue. Maybe Dave could help answer @tiroj 's question at https://github.com/googlefonts/fontbakery/issues/3100#issuecomment-733967171?

**Comment by davelab6** [comment]
https://twitter.com/TiroTypeworks/status/1332399952383729664?s=19 is a good illustration of what a weight axis may be mapped as

@felipesanches limiting the check to only VFs with a list of known avar'able axes, weight slant and opsz to start, would be good

I'm not sure about width being linear. Maybe if there's only a width axis by itself.

**Comment by RosaWagner** [comment]
I don't know what to think of the mandatory avar table. Some designers chose a linear interpolation, and that's it. Also, sometimes we can't do otherwise because of the regressions it can cause to change the interpolation pace. It looks more like a design decision than a production decision and therefore would make more sense as a `warn` in my opinion. 

The rational could need more in-depth on:
- how to add an avar table. I am not sure myself actually: is it calculated from the axis mapping parameter? *
- and how to make a distribution which results in a non-linear distribution of weight (etc) like explained in this Glyphs tuto : https://glyphsapp.com/learn/multiple-masters-part-3-setting-up-instances 

* If yes, it should be mentioned that wether it is in a Glyphs (Axis Mapping custom parameter in font info) or a designspace file: the first value ("input") is the actual `user value` (aka `us-weight class`, 400 for Regular), and the second value ("output") is a linked designspace coordinate value (the one chosen to define the location of an instance).

**Comment by twardoch** [comment]
avar is mostly relavant if the font contains the wght axis. 

If the font does not contain wght but other axes like wdth or opsz, there is usually no reason for a mandatory avar. Linear progression of wdth is fully normal, and for opsz it also is often correct. The same is true for ital and many custom axes.

**Comment by twardoch** [comment]
Even with weight and opsz, if the range of the axis is small, avar may not be necessary. E.g. if tht weight only goes from 700 to 900 (in a heavy display face à la Modak), or if the opsz goes from headline to poster in a display didone. 

Not all VFs will have wght that goes from 100 to 900 :)

**Comment by yanone** [comment]
Adding an opinion: the toolchain doesn’t create an `avar` table for fonts with linear instance progression. This should be detected by fontbakery and passed, if found to be the case.

**Comment by twardoch** [comment]
Avar is a particular correction mechanism, in a way it's a bit like kerning. Making avar mandatory is like making kerning mandatory. Yes, often missing kerning is a bug but sometimes it's intent. Same with avar.

It’d be sensible if fontbakery made specific checks for wght axis, I'll draft it up.

**Comment by felipesanches** [comment]
@davelab6 what do you think? (I'm asking because you're the person who originally proposed this check)

**Comment by felipesanches** [comment]
Current rationale text for this checks starts with `"Most variable fonts should include an avar table to correctly define axes progression rates."`

At https://github.com/justvanrossum/nabla/issues/25#issuecomment-1215650287 @davelab6 said:

 > @justvanrossum yes, that's fair, since the description is "most" not "all" then FAIL is heavy handed.

So, I will make this a WARN.
