### ISSUE TITLE
com.google.fonts/check/unitsperem_strict make less strict

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#3139]
I've probably missed the discussion on this check but I don't think it should fail fonts.

This test fails for https://github.com/google/fonts/pull/2924 since it has a upm of 750? there's nothing wrong with this.

I also don't think checking for powers of 2 is useful in 2020.

Having a upm above 2048 is fine. The file size increase is marginal.

Please set this test to a warn.

**Comment by davelab6** [comment]
@tphinney also found this, his icon font got a WARN result from `com.google.fonts/check/unitsperem` and a FAIL result from `com.google.fonts/check/unitsperem_strict`, when his font's UPM is 960 and that is intentional. 

I don't really remember why we added the 2nd stricter check. I think that's what happened. 

But in any case, we ought to have only 1 check for this... So I think it should only FAIL in really weird values, like say under `500` and over `4096`.

I expect this should be a very fast check to fix up for @felipesanches :)

**Comment by felipesanches** [comment]
* **com.google.fonts/check/unitsperem** belong to the `opentype` profile and checks for the bare minimum set of recommendations of upm values based on the OpenType spec.
* **com.google.fonts/check/unitsperem_stricter** is a vendor-specific check on the `googlefonts` profile and it adds a set of other requirements for upm values based on Google Fonts policy. It evolved gradually with many iterations adding requirements (or recommendations) based on comments by @davelab6 and other team members.

`opentype` profile: com.google.fonts/check/unitsperem
----

**Rationale:**
According to the OpenType spec:

The value of unitsPerEm at the head table must be a value between 16 and 16384. Any value in this range is valid.

In fonts that have TrueType outlines, a power of 2 is recommended as this allows performance optimizations in some rasterizers.

But 1000 is a commonly used value. And 2000 may become increasingly more common on Variable Fonts.


`googlefonts` profile: com.google.fonts/check/unitsperem_strict
----

**Rationale:**
Even though the OpenType spec allows unitsPerEm to be any value between 16 and 16384, the Google Fonts project aims at a narrower set of reasonable values.

The spec suggests usage of powers of two in order to get some performance improvements on legacy renderers, so those values are acceptable.

But values of 500 or 1000 are also acceptable, with the added benefit that it makes upm math easier for designers, while the performance hit of not using a power of two is most likely negligible nowadays.

Additionally, values above 2048 would likely result in unreasonable filesize increases.

**Comment by felipesanches** [comment]
An additional way of understanding what a check does is by looking at its test-code. I try to make code tests as readable as possible. Here's a selection of many good and bad upm values for testing (and the reasoning for each):

![Screenshot from 2021-05-27 03-17-56](https://user-images.githubusercontent.com/213676/119775757-6db8ca00-be9a-11eb-97fa-d21caf7c2413.png)

**Comment by davelab6** [comment]
I guess the `com.google.fonts/check/unitsperem` result should be the lowest possible priority of WARN result. Its extremely minor if its not a power of 2. The FAIL should only be outiside 16 and 16384; so the `FAIL_VALUES.extend()` should be `WARN_VALUES.extend()` I think.

**Comment by felipesanches** [comment]
I had a video call with @tphinney this week in which he made a few suggestions regarding this check:

**SUGGEST:** WARN but not FAIL most values from 500 to 2048? 
TPhinney suggests we only FAIL: all values <500, all values >4096

He also said there can be weird reasons for oddball values, but in Google Font submissions, unusual values are quite possibly mistakes, so we definitely want to at least WARN.

**TODO:** Thomas to check on 4K coordinate limitations with PS outlines (which also would affect TT output on some PostScript Level 1 devices, which converted TT>PS in the output path)

**Comment by felipesanches** [comment]
Also, we should consider renaming this `googlefonts` check to **com.google.fonts/check/unitsperem** and make it override the one from the `opentype` profile.

**Comment by davelab6** [comment]
Sgtm

**Comment by felipesanches** [comment]
unfortunately, it seems that our overriding mechanism currently only supports changing the log level of check messages, but not providing a completely new implementation.

I am investigating how to make this work. I may need to make modifications to the overriding code to be able to do so.

**Comment by graphicore** [comment]
> unfortunately, it seems that our overriding mechanism currently only supports changing the log level of check messages, 

Yes, that's fully intentional. That thing was meant for simple stuff only, where the check stays essentially the same.

>but not providing a completely new implementation.

If you don't want a check, don't add it to the profile.

So, instead of trying to replace one with another. Don't add the one and instead only add the other.

**Comment by felipesanches** [comment]
> If you don't want a check, don't add it to the profile.
> So, instead of trying to replace one with another. Don't add the one and instead only add the other.

I am not sure how to add everything form a child profile, except for a few checks that I will provide an alternative implementation. Also, is there something bad about reusing the check id, since it is effectively a substitution of the checking criteria?

**Comment by graphicore** [comment]
> I am not sure how to add everything form a child profile, except for a few checks

`profile.auto_register` has a `filter_func` argument.

> Also, is there something bad about reusing the check id, since it is effectively a substitution of the checking criteria?

Yes, because it is another check it should have another id, no matter if it is a substitution or replacement or whatever its function is. The discussion about the uniqueness of check-ids is somewhere in the issue tracker.

**Comment by simoncozens** [comment]
I think this is done; we have a unitsperem in opentype and our own stricter one in googlefonts. As usual please feel to reopen if I've misunderstood.
