### ISSUE TITLE
FAIL if alternate caron is incorrect

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3308]
`Lcaron`, `dcaron`, `lcaron`, `tcaron` should NOT be composed  with quoteright or quotesingle or comma or caron(comb). It should be composed with a distinctive glyph which doesn't look like an apostrophe: preferably caroncomb.alt (eventually caroncomb.alt.case for `Lcaron`). 

**sources**
https://ilovetypography.com/2009/01/24/on-diacritics/
http://diacritics.typo.cz/index.php?id=5
https://www.typotheque.com/articles/lcaron

You can find a case of `Lcaron` using a component made with `comma` here:
https://github.com/ThomasJockin/QuicksandFamily/tree/3d1e9808cb8594744d031e733a982d985bd4f126

In this tricky case, `caroncomb.alt` is a copy of the contours of `quotesingle`. So name and usage is correct but not the shape:
https://github.com/Etcetera-Type-Co/Tourney

**Comment by felipesanches** [comment]
> You can find a case of Lcaron using a component made with comma here:
> https://github.com/ThomasJockin/QuicksandFamily/tree/3d1e9808cb8594744d031e733a982d985bd4f126

I am trying to implement this check.
I followed the URL you posted but I think it is a bit ambiguous because I don't know if you are talking about the static TTF files in that specific commit or talking about the VF TTF, or even the source files in that repo.

Inspecting the static TTF of the Regular I see an **Lcaron** which does not use components, which makes me believe that's not what you were referring. Nevertheless, how should we deal with cases like this?

![Screenshot from 2021-05-26 01-01-33](https://user-images.githubusercontent.com/213676/119600685-ef86f580-bdbd-11eb-868f-baa00c6ff91c.png)

**Comment by RosaWagner** [comment]
Ah in this case, they decomposed `L` in `Lcaron` in the sources, so the entire glyph is decomposed during export. `tcaron` will have the issue we are looking for. Although for this build they didn't use the flatten component flag, and the said component will be `caronalt` (wrong name but not that important imo), which is made with a component of `comma`. 

Deeply sorry for this confusion.

Now, if we do have the case of decomposed outlines… I don't know. The most occurring case remains components in variable fonts and static ttf, and it is already helpful if we can check for that because it is happening often.
