### ISSUE TITLE
Add check for `chws`/`vchw` features

### ISSUE THREAD

**Issue by kojiishi** [googlefonts/fontbakery#3363]
The [chws_tool](https://github.com/googlefonts/chws_tool) adds [`chws`]/[`vchw`] GPOS features to fonts. It'd be great if we can check existence of these features for CJK fonts.

Note that the features are applicable only for CJK fonts. Also some CJK fonts (e.g., monospace) are not applicable.

I'm happy to come up with the rules to need the features, but @rsheeter suggested checking the features when the previous releases of the fonts have the features would be useful.

[`chws`]: https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-chws
[`vchw`]: https://docs.microsoft.com/en-us/typography/opentype/spec/features_uz#tag-vchw

**Comment by simoncozens** [comment]
I've implemented this, but with the following notes for posterity:

* The check just tests whether those two features are present in the GSUB/GPOS tables. We could be more specific and just check if it's in GPOS, but I haven't done that.
* I've made it a WARN, rather than a FAIL, because this feature is very rare, and I'm not even sure that any browsers support it yet.
* Yes, it should only apply to monospaced fonts, but monospaced has two meanings here: CJK fonts which are stylistically monospaced - i.e. "typewriter" fonts - should *not* have these features; however, CJK text fonts may be *technically* monospaced - i.e. designed on an em-square and so have fixed-size glyphs - still need to be adjusted with negative half-em aki using this feature. (See [this note](https://www.w3.org/TR/jlreq/#h-note-51)). As we can't really tell the difference between stylistically monospaced and technically monospaced fonts, I've just applied it to all fonts. Hopefully since it's only a WARN, the designer can see the message and decide what is appropriate.
