### ISSUE TITLE
reevaluate profile and log level for check/layout_valid_feature_tags

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3368]
@khaledhosny has some reasonable concerns explained in more details at https://github.com/googlefonts/fontbakery/pull/3359#discussion_r661882381

**Comment by simoncozens** [comment]
With respect to the specific issue here, I think we should probably just add `HARF` and `BUZZ` to the allowed feature tags list, because if someone is using those tags they clearly know what they're doing. I still believe that, in the general case, using tags which no shaping engine applies is a clear mistake.
