### ISSUE TITLE
UX Writing: Relabel fail to caution to reassure users

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3379]
In https://github.com/googlefonts/fontbakery/pull/3359#discussion_r668363459 @khaledhosny says "actual bugs" - but this assumes a single universal profile, that's like OTS or MSFV. 

The point of fb vendor profiles is that the font is assumed valid and has no "actual" bugs (as the OpenType spec profile covers that); these checks are for more opinionated ways of doing things specific to that vendor. But the same word "fail" is used for both kinds of profiles, which implies this incorrect assumption. 

The point of the most serious negative result is that the user almost certainly has to change something, but the word "fail" isn't always an accurate way to label that status.

In the UK if you get stopped by the police they can give you a **"warning"** and let you go but if they arrest you, the lightest sentence is a **"caution"** - which requires (an admission of guilt ;p and) no lawyers or judge or whatever else, the police authority can administer it directly. 

So, please change fail to caution in the reporters (the view, not the model, in MVC terms), for all the vendor profiles, or even by default, so the label for the OpenType spec profile (and the internal code) remains with fail.

**Comment by felipesanches** [comment]
I don't think the matter is so simple.

@khaledhosny seems to dislike the opinionated checks on the `googlefonts` profile and even mentions "dubious rationales". Merely rewording won't make the problem go away.

I'm a bit reluctant to embrace such a shallow fix. On the contrary, I think we've got a good opportunity of learning from Khaled on how to improve the tool. That's why I asked him to consider posting individual issues for the rationales he considers "dubious". These issues would then be starting points for conversations that can lead to actual improvements.
