### ISSUE TITLE
Discourage DSIG table presence

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#3398]
## Observed behaviour

fontbakery issues a FAIL message for fonts without `DSIG` table (`com.google.fonts/check/dsig`).

## Expected behaviour

Do nothing, don’t even issue a WARN or INFO, `DSIG` table is unused; MS Office used to require it to enable OpenType features for so-called simple scripts but does not do any more and not everyone is building such fonts. 

## Resources and exact process needed to replicate

Any font produced in the last millennium that did not add `DSIG` table to make fontbackery FAIL go away.

**Comment by simoncozens** [comment]
I remember rumours that MS Office Mac still does?

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/fontbakery/issues/1845#issuecomment-568022943

**Comment by davelab6** [comment]
> 
Any font produced in the last millennium that did not add `DSIG` table to make fontbackery FAIL go away.

LOL

In fact, I think we should flip the check to WARN people if a DSIG is found at all, and tell them to remove it.

**Comment by davelab6** [comment]
This is relatively high severity because it is so annoying :)

**Comment by felipesanches** [comment]
The rationale in this check currently says:

----
Microsoft Office 2013 and below products expect fonts to have a digital signature declared in a DSIG table in order to implement OpenType features. The EOL date for Microsoft Office 2013 products is 4/11/2023. This issue does not impact Microsoft Office 2016 and above products.

This checks verifies that this signature is available in the font.

A fake signature is enough to address this issue. If needed, a dummy table can be added to the font with the `gftools fix-dsig` script available at https://github.com/googlefonts/gftools

----

I'm OK with changing the check to reflect a new policy of removing the table from all fonts even if there's still ~1,5 year until the EOL date for Office 2013. Sounds like a reasonable time to do so now.

**Comment by felipesanches** [comment]
For now, a WARN, but by November 2023 we should finally make this a FAIL.
