### ISSUE TITLE
Don’t be too exact about URL strings

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#3399]
## Observed behaviour

In https://github.com/google/fonts/pull/3602#issuecomment-888601854 multiple checks are `FAIL`ing because https is used instead of http:
* `com.google.fonts/check/name/license`
* `com.google.fonts/check/metadata/valid_copyright`
* `com.google.fonts/check/font_copyright`

## Expected behaviour

Accept https.

## Resources and exact process needed to replicate

https://github.com/google/fonts/pull/3602

**Comment by felipesanches** [comment]
please re-run checks on that family using the latest version of Font Bakery and reopen the issue is the problem persists. That report is from 23 releases ago (from December 2019).

And some time ago I remember that I have fixed exactly that kind of problem. I'd be glad to address the issue, of course, if it's confirmed that some checks still misbehave on the latest version of Font Bakery.
