### ISSUE TITLE
Maybe use Adobe's pyots instead of ots-python?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3522]
@anthrotype suggested it at https://github.com/googlefonts/ots-python/issues/14

**Comment by anthrotype** [comment]
if it aint broke dont fix it?

**Comment by felipesanches** [comment]
well... my understanding was that this would free you from the task of maintaining ots-python

**Comment by anthrotype** [comment]
sure but how often does OTS get updated? It takes us 2 minutes to bump the version embedded ots binary. What I like about that googlefonts/ots-python package is that it builds one wheel per platform, instead of one per python version in turn multiplied by the number of platforms. It's also much simpler to maintiain, it simply calls ots-sanitize as a subprocess, delegating all the logic to the latter. Unless one can't spawn subprocesses for whatever reason and must link to the C++ api directly, then I don't see urgency to switch

**Comment by anthrotype** [comment]
Also I remember Josh said they only build and publish wheels for Mac and Linux, but not for Windows.

**Comment by felipesanches** [comment]
yeah, makes sense!

ok cool then ;-)
