### ISSUE TITLE
com.google.fonts/check/fontbakery_version is always skipped

### ISSUE THREAD

**Issue by saltcandy123** [googlefonts/fontbakery#3576]
Hi! I'm a new user of Font Bakery and I found something unexpected.

## Observed behaviour

When checking a font with check-universal, `com.google.fonts/check/fontbakery_version` is always skipped as `No applicable arguments`.

## Expected behaviour

`com.google.fonts/check/fontbakery_version` should be always tested regardless of what kind of files are specified.

## Resources and exact process needed to replicate

I used the following commands:

```bash
pip install "fontbakery==0.8.6"
fontbakery check-universal font.ttf -c com.google.fonts/check/fontbakery_version -l PASS
```
I saw Font Bakery 0.8.1 correctly tests the check (and results in FAIL because it's not the latest version).
However, Font Bakery 0.8.2 and 0.8.6 (the latest version at present) skip the check.

**Comment by miguelsousa** [comment]
@felipesanches I can take on this one.

**Comment by felipesanches** [comment]
great, thanks! :-)

**Comment by miguelsousa** [comment]
@felipesanches AFAICT this bug was introduced in #3432, more specifically in this commit 91b1b307a096d9cd3f81756d65b951f8eef70409.
I can make the check run by adding `font` as the argument to the check's method, which currently has none.
https://github.com/googlefonts/fontbakery/blob/b8f283281e1d98e75682d5688665d1819e39ac2f/Lib/fontbakery/profiles/universal.py#L333

Does this sound like the right way to fix it?
