### ISSUE TITLE
RFN Exception allow-list?

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3589]
Should we have an allow-list of fonts projects where RFN is okay? 
(like the ones already published with it and the ones which benefit from an agreement with GF (government fonts etc))

cc @davelab6

**Comment by felipesanches** [comment]
I think that's a good idea!

**Comment by felipesanches** [comment]
@RosaWagner, could you provide an initial listing of such cases?

**Comment by RosaWagner** [comment]
- ABeeZee
- Lexend
- Readex Pro
- Public Sans (version with RFN not yet onboarded but there is an agreement if I recall)
- STIX Two Text
- STIX Two Math

Are the ones that come to mind, and then all the ones that FAIL the RFN test in google/fonts repo.

ABeeZee mentions its own name as RFN, but was published like that years ago. The other ones actually respect the RFN, they are published under another name than the actual one mentioned. But honestly I don't understand all the legal thing under that, I couldn't tell you if we could allow RFN systematically in the second case.

**Comment by felipesanches** [comment]
I've generated this list with:
```fontbakery check-googlefonts -c rfn  ../../github_google/fonts/*/*/*.ttf -l SKIP | grep .ttf | cut -d/ -f7 | cut -d- -f1 | cut -d[ -f1 | sort | uniq | while read name; do echo \* $name >> rfn-families.txt; done;```

We'll need to double check if that's correct, because it would a way too long list of exceptions, with 430 family names in it...

* ABeeZee
* Abel
* AbrilFatface
* Acme
* Actor
* Adamina
* AdventPro
* AguafinaScript
* Akronim
* Aladin
* AlfaSlabOne
* Alike
* AlikeAngular
* Allan
* Allerta
* AllertaStencil
* Almendra
* AlmendraDisplay
* AlmendraSC
* Amarante
* Amethysta
* Andika
* Antic
* AnticDidone
* Arapey
* Arbutus
* ArefRuqaa
* Arizonia
* Artifika
* AsapCondensed
* AsapVFBeta
* Asset
* Assistant
* Asul
* AtomicAge
* Aubrey
* AutourOne
* Average
* AverageSans
* AveriaGruesaLibre
* AveriaLibre
* AveriaSansLibre
* AveriaSerifLibre
* Balthazar
* Basic
* Baumans
* Belgrano
* Belleza
* BenchNine
* Bentham
* BilboSwashCaps
* BlackOpsOne
* BM
* Bonbon
* Boogaloo
* BowlbyOne
* BowlbyOneSC
* Brawler
* BreeSerif
* BubblegumSans
* BubblerOne
* Buenard
* Butcherman
* CabinSketch
* Cagliostro
* Cambo
* CantoraOne
* Capriola
* Carme
* CarroisGothic
* CarroisGothicSC
* CevicheOne
* ChangaOne
* Chango
* ChauPhilomeneOne
* ChelaOne
* Chenla.ttf
* Chicle
* CinzelDecorative
* Coda
* Combo
* Comfortaa
* ConcertOne
* Condiment
* Content
* ContrailOne
* Convergence
* Cookie
* Copse
* Corben
* Courgette
* Coustard
* Creepster
* CreteRound
* CrimsonText
* CroissantOne
* Cuprum
* Cutive
* DancingScript
* DavidLibre
* DeliusSwashCaps
* DeliusUnicase
* DellaRespira
* DenkOne
* Dhyana
* Diplomata
* DiplomataSC
* DMSans
* DMSerifDisplay
* DMSerifText
* DonegalOne
* DoppioOne
* Dorsa
* DrSugiyama
* Eater
* Electrolize
* Elsie
* ElsieSwashCaps
* EmblemaOne
* EncodeSans
* EncodeSansCondensed
* EncodeSansExpanded
* EncodeSansSC
* EncodeSansSemiCondensed
* EncodeSansSemiExpanded
* EricaOne
* Esteban
* EuphoriaScript
* Ewert
* FasterOne
* FaunaOne
* Federant
* Federo
* Felipa
* Fenix
* FingerPaint
* FjallaOne
* Flamenco
* FredokaOne
* Fresca
* Fruktur
* FugazOne
* Gabriela
* Gafata
* Galdeano
* Geo
* Geostar
* GeostarFill
* GermaniaOne
* GildaDisplay
* GoblinOne.ttf
* GochiHand
* Gorditas
* Graduate
* GravitasOne.ttf
* Grenze
* Gruppo
* Gudea
* Habibi
* HammersmithOne
* Handlee
* HappyMonkey
* Harmattan
* HeadlandOne
* HennyPenny
* HermeneusOne
* HerrVonMuellerhoff
* Homenaje
* Iceberg
* Iceland
* IMFeDPsc28P.ttf
* IMFeENit28P.ttf
* IMFeENrm28P.ttf
* IMFeENsc28P.ttf
* IMFeFCit28P.ttf
* IMFeFCrm28P.ttf
* IMFeFCsc28P.ttf
* IMFeGPit28P.ttf
* IMFeGPrm28P.ttf
* IMFeGPsc28P.ttf
* IMFELLDoublePica
* IMFePIit28P.ttf
* IMFePIrm28P.ttf
* IMFePIsc28P.ttf
* Imprima
* Inder
* IstokWeb
* JacquesFrancois
* JacquesFrancoisShadow
* Jaldi
* JockeyOne
* JosefinSans
* JosefinSlab
* JotiOne
* Julee
* JuliusSansOne
* Junge
* Kantumruy
* KarlaTamilInclined
* KarlaTamilUpright
* KaushanScript
* Kavoon
* KdamThmor
* KeaniaOne
* KellySlab
* Kenia
* KiteOne
* KottaOne
* Kreon
* KronaOne
* LateefRegOT.ttf
* Lato
* LeckerliOne
* Lekton
* Lemon
* Lexend
* LexendDeca
* LexendExa
* LexendGiga
* LexendMega
* LexendPeta
* LexendTera
* LexendZetta
* LibreBaskerville
* LifeSavers
* LilitaOne
* LilyScriptOne
* Lobster
* LobsterTwo
* LondrinaOutline
* LondrinaShadow
* LondrinaSketch
* LondrinaSolid
* Lora
* Lusitana
* Lustria
* Macondo
* MacondoSwashCaps
* Mada
* Mallanna
* Mandali
* MarcellusSC
* MarckScript
* MarkoOne
* Marmelad
* Marvel
* Mate
* MateSC
* MavenPro
* MavenProVFBeta.ttf
* MedulaOne
* MeieScript
* MergeOne
* Merienda
* MeriendaOne
* Merriweather
* Metamorphous
* Metrophobic
* Miama
* Milonga
* Mina
* MissFajardose
* ModernAntiqua
* Molengo
* Molle
* MonsieurLaDoulaise
* Montaga
* MontserratSubrayada
* MountainsofChristmas
* MrBedfort
* MrDafoe
* MrDeHaviland
* MrsSaintDelafield
* MrsSheppards
* NATS
* Neuton
* NewRocker
* NewsCycle
* Niconne
* NixieOne
* Norican
* Nosifer
* NosiferCaps
* NoticiaText
* NovaCut.ttf
* NovaFlat.ttf
* NovaOval.ttf
* NovaRound.ttf
* NovaScript
* NovaSlim.ttf
* NovaSquare.ttf
* NTR
* Numans
* Offside
* OFLGoudyStMTT
* OFLGoudyStMTT.ttf
* Oldenburg
* Oranienbaum
* Orbitron
* Orienta
* Overlock
* OverlockSC
* Ovo
* Oxygen
* OxygenMono
* Paprika
* PasseroOne
* PassionOne
* PathwayGothicOne
* Pattaya
* PatuaOne
* Pecita.ttf
* Peddana
* PetitFormalScript
* Piedra
* PinyonScript
* PirataOne
* Plaster
* Play
* PlayfairDisplay
* PlayfairDisplaySC
* PoetsenOne
* PollerOne.ttf
* Poly
* Pompiere
* PontanoSans
* PortLligatSans
* PortLligatSlab
* PressStart2P
* ProstoOne
* Pushster
* Quando
* Quantico
* Quattrocento
* QuattrocentoSans
* Quicksand
* RacingSansOne
* Raleway
* RalewayDots
* Ramaraja
* Rambla
* RammettoOne
* Ranchers
* Rationale
* RaviPrakash
* Revalia
* RopaSans
* Rosarivo
* RougeScript
* Rufina
* Ruluko
* RussoOne
* Sail
* SairaCondensed
* SairaExtraCondensed
* SairaSemiCondensed
* Salsa
* Sanchez
* Sancreek
* Sansation
* Sarina
* Scheherazade
* ScheherazadeNew
* Sedan
* SedanSC
* Sevillana
* SeymourOne
* Share
* ShareTech
* ShareTechMono
* Shojumaru
* ShortStack
* Siemreap.ttf
* Simonetta
* Sintony
* SirinStencil
* Sniglet
* Snippet.ttf
* SnowburstOne
* SofadiOne
* Sofia
* SonsieOne
* SourceCodePro
* SourceSans3
* SourceSansPro
* SourceSerif4
* SourceSerifPro
* Spinnaker
* Spirax
* SquadaOne
* SreeKrushnadevaraya
* StalinistOne
* Stoke
* Strait
* Strong
* Sumana
* SupermercadoOne
* Suranna
* Suravaram
* Tauri
* Telex
* TenaliRamakrishna
* TextMeOne
* Tharlon
* Tienne
* Timmana
* TitanOne
* Trochut
* Trykker
* Tuffy
* TulpenOne
* Underdog
* UnicaOne
* UnifrakturCook
* UnifrakturMaguntia
* Unlock
* VampiroOne
* Varela
* VarelaRound
* VastShadow
* Vidaloka
* Viga
* Voces
* Volkhov
* Voltaire
* Warnes
* Wellfleet
* WendyOne
* WireOne.ttf
* YesevaOne

**Comment by RosaWagner** [comment]
For several years the RFN was standard in the OFL and we can't remove it without the consent of all the authors. So every time we upgrade one of those fonts we have the related fails.

**Comment by felipesanches** [comment]
So this is the green light for me to add this entire exceptions list to the check, right?
So that at least we won't have new cases of RFN usage.

**Comment by felipesanches** [comment]
Corresponding to the long list of family names at https://github.com/googlefonts/fontbakery/issues/3589#issuecomment-1028327930, this is the summary of the **name/rfn** check, prior to adding the exceptions allow-list:

![Screenshot from 2022-02-03 18-17-15](https://user-images.githubusercontent.com/213676/152432335-293bcad0-2c85-4b80-bb9b-7ff3d6d56c5f.png)

The **metadata/reserved_font_name** check has similar results without the allow-list:
![Screenshot from 2022-02-03 18-34-48](https://user-images.githubusercontent.com/213676/152432768-bb20be74-3719-4f67-8696-68d0542dbf4a.png)

**Comment by felipesanches** [comment]
And this is with the exceptions allow-list.

 **com.google.fonts/check/name/rfn**:
![Screenshot from 2022-02-03 19-52-29](https://user-images.githubusercontent.com/213676/152442797-be81c76d-16af-41d1-b0cd-71f7b0fdd249.png)

**com.google.fonts/check/metadata/reserved_font_name**:
![Screenshot from 2022-02-03 19-51-39](https://user-images.githubusercontent.com/213676/152442812-af6f81df-85b5-4b71-bf8f-d244b9927fb7.png)

**Comment by felipesanches** [comment]
I did not include "Lexend", "Readex Pro", "Public Sans" and "STIX Two" because they're not currently on the google/fonts repo. It will be nice to exercise with them, case by case, the workflow of either explicitelly expanding the exceptions list or getting authorization to remove the Reserved Font Name clause.

**Comment by RosaWagner** [comment]
Oh wow that was fast! We should remember to update Dave on that one when he is back to office. 

> It will be nice to exercise with them, case by case, the workflow of either explicitelly expanding the exceptions list or getting authorization to remove the Reserved Font Name clause.

Yes, especially for expanding the exception list. But FYI Lexend, STIX and Readex Pro are in the repo with a RFN (but the RFN mentioned in the OFL.txt is not the actual name of the font, that is what I meant).

- stixtwomath
- stixtwotext
- lexend
- lexenddeca
- lexendexa
- lexendgiga
- lexendmega
- lexendpeta
- lexendtera
- lexendzetta
