### ISSUE TITLE
new google fonts check: ensure families can render language sample text

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#3605]
We recently added a [lang package](https://github.com/googlefonts/gftools/tree/main/Lib/gftools/lang) which is used to generate the new language fields in each [metadata.pb](https://github.com/google/fonts/blob/main/ofl/abel/METADATA.pb) file. We must check that the fonts can render each language's sample text, https://github.com/googlefonts/gftools/blob/main/Lib/gftools/lang/languages/aa_Latn.textproto.

These sample texts are a new feature. I think they work correctly for noto, https://fonts.google.com/noto/specimen/Noto+Serif+Kannada.

**Comment by felipesanches** [comment]
can we create a separate python package containing those textproto files? Just like we did for glyphsets.

gftools is too big to be added as a fontbakery dependency

**Comment by m4rc1e** [comment]
Agreed but we'll need to coordinate this first with the internal team.

I know this is a hack but for gftools, I use a [script](https://github.com/googlefonts/gftools/blob/main/update_data.sh) which pulls the data I need from google/fonts.

**Comment by felipesanches** [comment]
OK. I will start prototyping this by:

* creating a separate python package for the language data on my own github account (not **yet** to be hosted on the googlefonts organization).
* Then I'll publish it on pypi and use it in fontbakery to implement this new check.
* Then I'll send a PR to gftools to also use this new package. So that you can review and give some feedback.
* Finally I'll ask @davelab6 to accept migrating the repo from `felipesanches/languages` to `googlefonts/languages`.

All of this will happen without touching the language files currently hosted at google/fonts repo, so it should not affect internal Google Fonts team usage of those files. In the future we can keep track of those files and keep the separate module in sync, or the internal Google team may actually start using the module, removing the files from the google/fonts repo. In both scenarios, all is good, I think.

**Comment by felipesanches** [comment]
The repo with my initial implementation of the module is here:
https://github.com/felipesanches/languages

Sample usage:
```python
from languages import lang_support
langs = lang_support.LoadLanguages()
numerals = langs["yi_Hebr"].exemplar_chars.numerals
assert numerals == '- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9'

scripts = lang_support.LoadScripts()
assert scripts["Tagb"].name == 'Tagbanwa'

regions = lang_support.LoadRegions()
br = regions["BR"]
assert br.name == 'Brazil'
assert br.region_group == ['Americas']

font = TEST_FILE('nunito/Nunito-Regular.ttf')
supported = lang_support.SupportedLanguages(font)
langs = [supported[i].name for i, _ in enumerate(supported)]
assert len(langs) == 225
assert 'Lithuanian' in langs
```

**Comment by felipesanches** [comment]
A python module called "languages" already exists: https://pypi.org/project/Languages/

So I'll have to give it a different name. I may use something like `GFLanguages`. Any other suggestions?

**Comment by felipesanches** [comment]
https://pypi.org/project/gflanguages/0.1.0/

**Comment by felipesanches** [comment]
![Screenshot from 2022-02-18 04-24-55](https://user-images.githubusercontent.com/213676/154637074-9782e74e-a4e6-47e0-ba86-c951d8c59702.png)

![Screenshot from 2022-02-18 04-25-22](https://user-images.githubusercontent.com/213676/154637069-7f8fedbf-a791-4ddf-a41b-2139e0c725b7.png)
