### ISSUE TITLE
Move UFO dependencies to `extras_require` ?

### ISSUE THREAD

**Issue by miguelsousa** [googlefonts/fontbakery#3715]
Font Bakery started as a tool to test font binaries and nowadays it can also validate UFO font sources. This new functionality is great but it comes with its own set of dependencies.

The way it's currently setup, UFO dependencies (e.g. ufo2ft, ufolint, defcon, etc.) are always installed, even if you only want to use Font Bakery for checking font binaries.

I'd like to propose to move all of the UFO dependencies to a new [extras_require](https://github.com/googlefonts/fontbakery/blob/4da55fcdd974425b032db85172158a3aea48cf40/setup.py#L91-L100) named **ufo**, and I'm open to take on the dev work.

From a user perspective the only thing that'll change is having to invoke the new extra when installing Font Bakery,

    python -m pip install "fontbakery[ufo]"

**Comment by felipesanches** [comment]
sounds reasonable.

Be sure to also update the ReadTheDocs documentation to describe this. And also the continuous integration setup should enable UFO support so that all code-tests are run.

If you want me to make any of these additional adjustments, feel free to reassign the issue to me once you're done.
