### ISSUE TITLE
Remove `ufo_sources` profile from the list of imported checks into the Universal profile

### ISSUE THREAD

**Issue by miguelsousa** [googlefonts/fontbakery#3724]
This is somewhat related to #3715 

Currently, [the `ufo_sources` checks are imported into the Universal profile](https://github.com/googlefonts/fontbakery/blob/3e08267464055a9fe6922d4460e7bb47dd74235e/Lib/fontbakery/profiles/universal.py#L13-L17), essentially making them "universal" as well.

The UFO checks are not necessary for workflows that only care about running Font Bakery on font binaries.
I'd like to propose taking them out of the universal imports.

**Comment by felipesanches** [comment]
The scope of the universal profile is: "quality checks for universally accepted good practices."
Not everybody uses an UFO workflow, but for those who do, the things the checks validate are universally accepted.

If you are working exclusively with font binaries, those UFO checks will be automatically skipped because Font Bakery is smart enough to detect that. The same is also valid for other file types such as designspaces, that you mentioned at #3725 

An alternative could be to define profiles by file type, but that was not the way the project was structured. Profiles are instead defined by vendor-specific needs versus universally agreed upon checks.

**Comment by miguelsousa** [comment]
OK. Thanks for the explanation.
