### ISSUE TITLE
Fontbakery Technical Report

### ISSUE THREAD

**Issue by ThanosPoulakidas** [googlefonts/fontbakery#3804]
Hello,

I think I am having a problem with my uploaded files and I am having difficulties in finding the solution.
By checking the Fontbakery Tests, it doesn't show my font and I don't how to fix this.

Link to my repository
https://github.com/ThanosPoulakidas/Geom

Link to the first opened issue
https://github.com/google/fonts/issues/4525

**Comment by simoncozens** [comment]
Hi Thanos, I'm very sorry about the delay in replying. Something is failing in your build process which means that the fontbakery pages are not being rebuilt. Unfortunately I can't see the logs for your build because they have now expired. Next time you make changes to Geom, please create an issue in your own repository and tag me (@simoncozens) there and I'll try to see what's failing.
