### ISSUE TITLE
Universal / check if math signs have same width

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3832]
This is common practice to have:

- math signs are sharing the same width
- preferably the same width as tabular figures
- preferably across all masters of the same family

The math signs:
+ − × ÷ = ≠ > < ≥ ≤ ± ≈ ~

This practice comes probably from the will to avoid additional tabular math signs knowing that their design can easily share the same width. Would be quite useful to have a check warning in case of inconsistency. At east it would make my life easier that's for sure.

I would say WARN, not fail.

I would like more input to know if there is more to add to the list, or if there is something against such a check; @vv-monsalve @tphinney @twardoch @tiroj ?

**Comment by tiroj** [comment]
Yes, a WARN would be appropriate. There are potentially a _lot_ of math operator symbols that could be included in such a check, but most of these are unlikely to occur except in specialist math fonts like STIX Two Math and Cambria Math. [There are also a lot of math symbols that are not usually tabular width, and a bunch that might be tabular in some designs but don’t need to be.] In terms of characters that are likely to occur in a large number of fonts, because of their presence in some basic character sets, I would include the not logical or negtation sign: ¬

I did a quick check in STIX Two Math, and these are all the math symbol characters that we chose to make the common advance width of the basic arithmetic operators:

+ < = > ¬ ± × ÷ ∈ ∉ ∋ ∌ − ∓ ∔ ∝ ∟ ∠ ∡ ∢ ∷ ∸ ∹ ∺ ∻ ∼ ∽ ∾ ∿ ≁ ≂ ≃ ≄ ≅ ≆ ≇ ≈ ≉ ≊ ≋ ≌ ≍ ≎ ≏ ≐ ≑ ≒ ≓ ≖ ≗ ≘ ≙ ≚ ≛ ≜ ≝ ≞ ≟ ≠ ≡ ≢ ≣ ≤ ≥ ≦ ≧ ≨ ≩ ≭ ≮ ≯ ≰ ≱ ≲ ≳ ≴ ≵ ≶ ≷ ≸ ≹ ≺ ≻ ≼ ≽ ≾ ≿ ⊀ ⊁ ⊂ ⊃ ⊄ ⊅ ⊆ ⊇ ⊈ ⊉ ⊊ ⊋ ⊏ ⊐ ⊑ ⊒ ⊢ ⊣ ⊤ ⊥ ⊨ ⊰ ⊱ ⊲ ⊳ ⊴ ⊵ ⊹ ⊾ ⋇ ⋍ ⋐ ⋑ ⋕ ⋖ ⋗ ⋚ ⋛ ⋜ ⋝ ⋞ ⋟ ⋠ ⋡ ⋢ ⋣ ⋤ ⋥ ⋦ ⋧ ⋨ ⋩ ⋳ ⋵ ⋶ ⋸ ⋹ ⋻ ⋽ ⟀ ⟃ ⟄ ⟓ ⟔ ⥶ ⥸ ⥹ ⥻ ⥾ ⥿ ⦓ ⦔ ⦕ ⦖ ⦛ ⦜ ⦝ ⦞ ⦟ ⦠ ⦡ ⦢ ⦣ ⦤ ⦥ ⦨ ⦩ ⦪ ⦫ ⧣ ⧤ ⧥ ⧺ ⧻ ⨢ ⨣ ⨤ ⨥ ⨦ ⨧ ⨨ ⨩ ⨪ ⨫ ⨬ ⨳ ⩦ ⩧ ⩨ ⩩ ⩪ ⩫ ⩬ ⩭ ⩮ ⩯ ⩰ ⩱ ⩲ ⩳ ⩷ ⩸ ⩹ ⩺ ⩻ ⩼ ⩽ ⩾ ⩿ ⪀ ⪁ ⪂ ⪃ ⪄ ⪅ ⪆ ⪇ ⪈ ⪉ ⪊ ⪋ ⪌ ⪍ ⪎ ⪏ ⪐ ⪑ ⪒ ⪓ ⪔ ⪕ ⪖ ⪗ ⪘ ⪙ ⪚ ⪛ ⪜ ⪝ ⪞ ⪟ ⪠ ⪡ ⪢ ⪦ ⪧ ⪨ ⪩ ⪪ ⪫ ⪬ ⪭ ⪮ ⪯ ⪰ ⪱ ⪲ ⪳ ⪴ ⪵ ⪶ ⪷ ⪸ ⪹ ⪺ ⪽ ⪾ ⪿ ⫀ ⫁ ⫂ ⫃ ⫄ ⫅ ⫆ ⫇ ⫈ ⫉ ⫊ ⫋ ⫌ ⫏ ⫐ ⫑ ⫒ ⫓ ⫔ ⫕ ⫖ ⫟ ⫠ ⫡ ⫢ ⫤ ⫦ ⫧ ⫨ ⫩ ⫪ ⫫ ⫳ ⫴ ⫵ ⫶ ⫹ ⫺ 〒

Some of these symbols have variant forms, including some that have Unicode variation selector sequences defined (so typically implemented in a format 14 cmap subtable); other variants might be mapped in Stylistic Set features. Some of this set would typically also have math layout ssty feature variants, which would also be expected to have common widths but not the same common widths as the default glyphs (ssty variants are optical size designs for use in superscript and subscript positions in equations; typically they come in two variants for multilevel equations).

**Comment by tphinney** [comment]
I definitely agree that a check is worthwhile and that there are a bunch of symbols that could benefit from it
It seems reasonable to me that the worst output should be WARN
But as to the question of which characters to include, I would defer to @tiroj as far more knowledgeable than I (and likely the most knowledgeable person on this subject, in your cc list)

**Comment by vv-monsalve** [comment]
Also agree on the worth of including the check and the WARN log level status result.
As per the characters included, taking the STIX Two Math project and the set provided by @tiroj as a reference could be a good starting point. The check could evolve from the feedback it may receive.

**Comment by felipesanches** [comment]
![Screenshot from 2023-01-26 15-26-50](https://user-images.githubusercontent.com/213676/214876558-d3aa05a9-ed94-4cb4-a143-7694d18f2c88.png)
