### ISSUE TITLE
com.google.fonts/check/whitespace_widths rationale

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3843]
## Observed behaviour

com.google.fonts/check/whitespace_widths is missing a rationale.

## Expected behaviour

One thing we recently discovered is that if the space and nbspace glyphs have different widths, then Google Workspace has problems with the font. That should be added to the rationale for this test.

**Comment by felipesanches** [comment]
Do we have a more detailed description of "it has problems with the font"? What kind of problems?

**Comment by simoncozens** [comment]
It doesn't onboard it. I'm not sure. Apparently it was in an email that went around this week but I didn't receive it. :-/ @RosaWagner?

**Comment by RosaWagner** [comment]
nbspace is used to replace the space character in multiple situations in documents; such as the space before punctuation in languages that do that*. It avoids the punctuation to be separated from the last word and go to next line. This is automatic substitution by the text editors, not by fonts. It is also used by designers in text composition practice to create nicely shaped paragraphs. If the space and the nbspace are not the same width, it breaks the text composition of documents. 

Probably for these reasons, one of the conditions for a font to get into Workspace is to have this check passing. I don't know how much it is looked at from the eng team but yeah, it was in the email thread and so the rationale should reflect the importance of this check that we tend to ignore. 

* If a french designer passes by: I know the thin space should be used instead of the nbspace, but that is not how office text editors work.

**Comment by felipesanches** [comment]
This check is currently part of the `OpenType` profile, but it seems to me that it should instead be moved to `Universal` profile. (or is it google-specific?)

**Comment by felipesanches** [comment]
The rationale being proposed here seems Google-specific. But the check was part of FontBakery for so many years in the OpenType profile and nobody ever complained about it, which makes me thing perhaps most people are OK with this validation of whitespace glyphs widths, even though it lacked a detailed rationale text.
