### ISSUE TITLE
Encode unencoded glyphs as F0000 + hex(GID)

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#388]
I was chatting with @twardoch today about how glyph names are the 'primary key' for fonts, because in any contemporary font you have so many unencoded glyphs, accessed with OpenType Layout logic... But unencoded glyphs are tricky to precisely call, because OTL logic is per-font. I mentioned that I might like to use the Unicode Private Use Area to encode otherwise-unencoded glyphs. 

Adam kindly mentioned he already thought about this, and he concluded that the Private Use Plane A (Unicode Plane 15) is ideal for this, as its `U+F0000..U+FFFFD` so you can use a value of `F0000 + hex(GID)` to cleanly, logically, encode all unencoded glyphs. 

Let's do it!
- [x] add a "3.10" cmap subtable

**Comment by davelab6** [comment]
Per TypeThursday's Laura Worthington article we should do this, its important for casual users.

**Comment by anthrotype** [comment]
What's this article you are referring to?

**Comment by davelab6** [comment]
Oh its not out yet. Stay tuned.

**Comment by anthrotype** [comment]
ok. I hope you don't want to revive the idea of using PUA codes in released fonts...

**Comment by behdad** [comment]
> Oh its not out yet. Stay tuned.

lol.  Ping us when it is.  That said, people have had bad ideas forever; doesn't mean we should support them.  I'm more willing to implement a HarfBuzz tool to render arbitrary glyphs than to add a hack in fonttools.

**Comment by davelab6** [comment]
The issue is that a lot of text environments that users are using do not
support OTL; for text typefaces this isn't really an issue, but for display
types then users really do want that particular glyph from that particular
font, and for it to work everywhere. When composing a 3 word text, the
scenarios where PUA text doesn't make sense are less important.

**Comment by davelab6** [comment]
@anthrotype @behdad the article is at https://medium.com/type-thursday/casual-users-and-the-font-market-a1c5c2f19149

**Comment by twardoch** [comment]
I used to be anti-PUA for a long time but now I’m more inclined to support it, because the software makers have failed to support OpenType Layout for the last 15 years. 

However, I’m more inclined to use the Supplementary PUA plane because it creates another “soft” hurdle. 

I’m not much helped by PUA-less fonts if OpenType gets supported widely 20 years after I’m dead :) 

BTW, instead of PUA, I’d actually be happier to produce “[feature-frozen](https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze) TTCs” that at least expose the most important 1:1 GSUB font features (small caps, stylistic sets, oldstyle nimerals) via the cmap as supplementary font menu items (Source Han does this). It’s a cleaner solution than PUA, with little overhead, and it seems that most modern OSes and apps do support TTCs. CFF-based TTCs have much less backwards compatibility than TT-based TTCs, though.

**Comment by twardoch** [comment]
The problem with TTCs though is that hardly any commercial font distributor is equipped to carry/sell them.

**Comment by twardoch** [comment]
Of course I understand why Behdad **categorically** (LOL) rejects this. It essentially undermines the last ten years of his work. :) With HarfBuzz, Behdad actually has made OpenType Layout much more attainable towards “normal” software developers, and from a “hobby clone” project has turned HB into being on par with the reference inplementation, or at times, surpass it. 

The actual problem is actually the primitive UX behind font selection and glyph input. So perhaps PUA is really just a silly little fix that offers comparatively little benefit, while the downsides with overusing it are potentially large.

**Comment by davelab6** [comment]
I can see the case for pyfeatfreeze based TTFs... but will TTCs work for
users of https://en.wikipedia.org/wiki/Creative_Writer or
https://en.wikipedia.org/wiki/3D_Movie_Maker or whatever it is kids use
these days? And what about OTFs?

**Comment by twardoch** [comment]
Microsoft has been shipping Cambria only as TTC since 2007, and numerous Chinese fonts well before that. All their APIs support TT-based TTCs well. Only a small fraction very obscure apps that do their own font handling might have a problem. Cambria is a major font, default in many documents. I've never heard any problems related to this, not in printing or any noteworthy apps. Windows APIs handle this completely transparently. CFF--based TTC support is newer on Windows, not sure how new. 

OS X handles TTCs (both TT and CFF) since at least 10.7, maybe older. The OS X upgrade rate is much faster given thir upgrades were always cheap or, recently, free. Most Apple system fonts are TTC, some CFF-based, so Apple must be confident their APIs handle it well.

**Comment by twardoch** [comment]
By CFF-based TTC, I mean OTF-based. They have the same extension, .ttc.

**Comment by davelab6** [comment]
I agree, although the upgrade rate is slowed because of hardware
requirements; there are some minority of users stuck on 10.6 old hardware
(and I believe some are stuck out of choice thanks to allegiance to old
'trusty' FL5 versions... :)

I wonder what Laura thinks.

**Comment by twardoch** [comment]
@kenlunde might know what repercussions of shipping CFF-based TTCs are, given Adobe's decision to ship Source Han as CFF-based TTCs but also in several split forms.

**Comment by davelab6** [comment]
On 8 February 2016 at 15:00, Adam Twardoch <notifications@github.com> wrote:

> However, I’m more inclined to use the Supplementary PUA plane because it
> creates another “soft” hurdle.
>
>
What does this look like for the newbie customer described in the
interview?

**Comment by twardoch** [comment]
Ps. If Lato had small caps or another big 1:1 feature, I would have shipped it as featfrozen TTCs from day 1. But the number of OT glyphs in Lato is tiny so I didn't bother. If we ever add small caps, I'll make the official release as TTCs.

**Comment by kenlunde** [comment]
@twardoch: The only downside to shipping OTCs is that Windows doesn't support them. Adobe apps, CS6 and higher, installed on Windows support OTCs, but the font resource needs to be installed into the app's private font folder. OS X started to support OTCs from Version 10.8, if memory serves. It's a superb delivery format for [Source Han Sans](https://github.com/adobe-fonts/source-han-sans/tree/release).

**Comment by twardoch** [comment]
Laura is a somewhat special case. She makes calligraphic fonts where only 30% or less of the glyphs are encoded. People pay for her fonts, then cannot use it. 

The only opensource font of that kind that comes to my mind is Pecita, where users might want to insert glyphs individually. SPUA should not make it difficult to achieve the double-click-on-glyph-palette glyph insertion. But it'd be easier to track the SPUA character codes in documents in case someone wants to cleanse them later. 

The featfrozen TTC method, on the other hand, would give millions of LibreOffice/OpenOffice users access to full-blown small caps (also Microsoft Office!), and to other major features (oldstyle figures, significant stylistic sets). 

I personally consider featfrozen TTCs not a hack, because they don't "break" anything. The user just changes the font in the menu, like going to an italic. 

The reason I contributed my SPUA code was mostly to make special font versions for use in webfont specimens, or glyphmaps, where you really want to "look", display non-printing glyphs, or override script-specific shaping. That's what I do myself and how I use it. I never shipped an end-user font like this. 

Suggestion: the OFL version of the Noto fonts should not use SPUA, but the Apache 2 versions might, for all glyphs ;)

**Comment by twardoch** [comment]
Ah, so Windows still does not support CFF-based TTCs. Bugger :(

**Comment by davelab6** [comment]
Since this is about naieve users of crappy Windows apps (you know, the ones
they use to make T shirt designs and Blurb self-publishing books and so on)
then the lack of Windows support makes this a non-starter. However, perhaps
OTC isn't so important.

**Comment by behdad** [comment]
> Of course I understand why Behdad categorically (LOL) rejects this. It essentially undermines the last ten years of his work. :)

That's not the reason.  It's "this is font-dependent text encoding" and hence BAD.  But I see your point.

**Comment by adrientetar** [comment]
> its become important for casual users of desktop fonts.

And you're the one advocating for Google being exemplary on the Roboto repo&hellip; if current applications are incapable then make one that is. That's what I'm doing with font editors.

**Comment by davelab6** [comment]
This isn't about libre software, it is about proprietary software that will
never improve.

**Comment by adrientetar** [comment]
Way to give up Dave. Make it better than proprietary as Stallman said and ppl will use it.

**Comment by davelab6** [comment]
On 10 February 2016 at 04:09, Adrien Tétar <notifications@github.com> wrote:

> Way to give up Dave. Make it better than proprietary as Stallman said and
> ppl will use it
>
Now who is wearing the GNU T shirt? :)

**Comment by davelab6** [comment]
> It's "this is font-dependent text encoding" and hence BAD

This reminds me of XHTML vs HTML5. I understand it offends technical purity. But it hurts users from getting their jobs done and getting on with their lives, and is only a fallback for when OT isn't available.

**Comment by adrientetar** [comment]
> Now who is wearing the GNU T shirt? :)

I'm talking to you in your language. Look, existing font editors didn't work for me so I made one.

**Comment by davelab6** [comment]
You seem to still be missing my point: New software doesn't matter. This is
about entrenched existing proprietary software, which can not be patched,
or switched away from.

**Comment by twardoch** [comment]
Conceptually, I'm with Dave insofar that fonts in the SFNT container are an unusually broad in the sense of OS and app coverage and lifespan. Also, people are more likely to switch fonts than apps because apps are, well, more specific to their needs. 

Also: text encoding is not an "easy" thing. There are no perfect solutions. Since 2001 I kept asking the industry how OT features should be marked up in "rich text" and the answer came in 2011 with CSS font-feature-settings. That's because it wasn't obvious at all. And it still isn't perfect (in order to get just one different glyph, you needs to surround the character with a HTML span and apply a super-long CSS property, but this will likely segment the text run so that isolated character stops interacting with the rest of the line OT-wise. 

It's shit. :)

**Comment by davelab6** [comment]
> how OT features should be marked up

This is a great point, I've added it to the wikimedia page, https://meta.wikimedia.org/w/index.php?title=Future_Global_Font_Format_Requirements&type=revision&diff=15336305&oldid=14437375

**Comment by twardoch** [comment]
Supplementary Private Use Area-A is 65534 codepoints from U+F0000 to U+FFFFD, which means that practically all fonts can be encoded (as they can hold max. 64K glyphs). My idea to use it was that each glyph ID gets assigned a codepoint F0000 + GID, so something like “harfbuzz.js” could do all the GSUB+GPOS processing even if a browser doesn't support some shaping, and then such harfbuzz.js would emit a series of GIDs, and in order to display them, F0000 is added to each resulting GID and then the font’s cmap gets requested for such codepoint, which in turn let the browser actually display these glyphs. Since the F0000+ codepoints in the font corresponds exactly to the GID order, this can be stored very efficiently in the font’s cmap format 12, adding only a few bytes to the font regardless of its size. 

The BMP PUA (E000-F8FF) only allows for 6400 codes so it wouldn't be enough for some fonts. Plus some fonts have a legitimate “corporate” usage of the BMP PUA (SIL, MUFI), while SPUA is really obviously “last resort”.

**Comment by twardoch** [comment]
Ps. In my method, ALL glyphs are encoded in the SPUA, not just the “unencoded” ones. But if the SPUA codes are used, the OS/app shaper does not apply any shaping since it knows nothing of the script. This allows me to do my own external shaping (e.g. via said harfbuzz.js or another JS shaper). So in essence, this is a simple poor man’s API for glyph access in apps that can only talk to fonts via the cmap. It a decdnt web implementation, those SPUA codes could live in some shadow DOM or something, while proper selectable/searchable text woul live “on top”.

**Comment by twardoch** [comment]
...or via CSS generated content. People dealing with icon fonts (Bootstrap using Font Awesome etc.) have been using PUA in an elegant way that does not expose garbage to search. But it’s still fonts rather than SVG, so it’s fast, cacheable, works everywhere etc. 

It's essentially a debate about treating users as smart vs. stupid. I prefer to treat users as reasonably smart. Users obviously prefer to just type their text on the keyboard, and that'll use normal Unicode. They will resort to some glyph palette insertion or some fancy PUA codes only if they're really “desperate” i.e. when they really have no other choice.

**Comment by davelab6** [comment]
> They will resort to some glyph palette insertion or some fancy PUA codes only if they're really “desperate” i.e. when they really have no other choice.

Right, that is why Laura uses the BMP PUA, and I agree that this would be better for her (and generally.)

One remaining question for me is if this should be done for all fonts or only OT-intense display fonts.

**Comment by twardoch** [comment]
I don’t have an opinion on that. 
However, I want to add one thing: in early OpenType days, Adobe used a portion of the BMP PUA as a “corporate use area”, where they standardized certain codes for things like small caps, oldstyle numerals or certain ligatures. So, an oldstyle “3” orva smallcap “A” always had a certain code regardless of the Adobe font used. Now that **was** a bad idea because this practice created an **illusion** that these codes had some claim of universality, or longtime relevance. So they stopped using PUA after a few years. 

But with purely font-specific encoding, I don’t see this as a problem. If you have a series of SPUA codepoints assigned to correspond to GIDs in a specific font, then everyone agrees that no machine “knows”, or is expected to know, what any of these codepoints “mean”. As long as all sides agree that no presumptions can be made, I think it’s fine. 

In Adobe’s case U+F761 was semi-standardized as “smallcap A”, and all their early OTFs used U+F761 as small-cap A, so the danger was that some apps might start expecting that U+F761 just “means smallcap A”. But with the purely GID-oriented SPUA, U+F0761 will mean something else with every single font. So it really is “private”, and substituting fonts will yield unecpected results. 

Which is fine because users will more likely not except any stability of this encoding and will use it mostly as an input mechanism for specific glyphs in very specific situations — often with the goal being print, or laser cut, or automated engraving. Most of these laser cut or engraving apps have no OT features UI and never will be. 

So SPUA entry may be the **only** way for the user to get work done. If the user could find a better method, they’d already be using it.

**Comment by davelab6** [comment]
> As long as all sides agree that no presumptions can be made, I think it’s fine.

I worry that glyphs/fontmake might create predictable map from common unicodes to GID ordering...

**Comment by felipesanches** [comment]
I risk saying something stupid here, but if a strict mapping should not be infered to be normative, then can't these tools randomise mappings on purpose?

**Comment by davelab6** [comment]
> randomise mappings on purpose?

That seems wise, to mitigate the practical problem with PUA text.

**Comment by kenlunde** [comment]
PUA Text: Hope for best, expect the worst.

**Comment by davelab6** [comment]
@kenlunde I understand the categorical criticism of this, but I'm curious what your advise is for Laura Worthington. What should she do to serve her customers?

**Comment by kenlunde** [comment]
@davelab6: I wrote the following at the bottom of page 162 of [*CJKV Information Processing*, Second Edition](http://oreil.ly/CJKV2E): "The use of PUA code points should be avoided at all costs, because their interpretation, in terms of character properties, and their interaction with legacy character set standards (in other words, interoperability) cannot be guaranteed."

With that said, [Laura's article](https://medium.com/type-thursday/casual-users-and-the-font-market-a1c5c2f19149#.yyr6a9ebi) suggests that PUA usage is a necessary evil in order to access glyphs that are not directly encoded. However, the main caveat is that the more an implementation depends on PUA code points, the more closed said implementation is.

**Comment by davelab6** [comment]
> the more closed said implementation is

I'm not entirely sure what you mean by 'closed,' please could you clarify? :) 

I am framing this as **fallback** to help users of implementations that are so poorly done that this is the only way to make the font useful. It isn't that implementations should depend on the PUA codepoints for providing large glyph sets to users, it is that they are oblivious to this need and PUA is a workaround for people who are held hostage by these implementations' incompetence.

**Comment by kenlunde** [comment]
@davelab6: What I mean by *closed* is that the implementation is closely tied to the PUA mappings of a particular font, and changing the selected font to anything else is virtually guaranteed to result in illegible text.

Furthermore, in the context of font fallback, I would claim that PUA usage is at least an order of magnitude more dangerous than environments that do not employ it, because it is not clear from which font (or fonts) the glyphs are being displayed.

Also, for fonts with glyphs that are not encoded and require OpenType feature support to access them, there may also be metrics-related dependencies that would likely be overlooked by simpler apps, meaning that even if a user is somehow able to enter a glyph via a PUA code point, the resulting glyph may not behave as expected, due to limitations in the simpler authoring app.

**Comment by davelab6** [comment]
Hmm. 

So, it seems that Laura should simply `pyfeafreeze` her font into a set of single-style font families, and I should set up a `freezemyfont.com` site to make it easy for regular people to freeze their libre OT fonts to use in such implementations, and maybe lobby Font Squirrel to add this to the Web Font Generator.

**Comment by khaledhosny** [comment]
Where is the glyph positioning of all this (so 60s) PUA talk, it is not like OpenType is only about glyph replacements. OK you are not building fonts that need mark positioning or all this fancy stuff, but what about kerning?

**Comment by kenlunde** [comment]
@davelab6: I am not sure what *pyfeafreeze* is and its ramifications. I have no strong objections to someone who feels the need to use PUA code points, and my point is that those who decide to go down that path simply need to understand the consequences, which is that nothing is guaranteed, and any oddball behavior is likely to be related to the decision to use PUA code points.

@khaledhosny: That was sort of my point, specifically that there is more to glyphs that merely having them encoded. Perhaps such an approach works for Western fonts, but I can pretty much guarantee that it will crumble when non-Western fonts enter into the picture.

**Comment by twardoch** [comment]
All OpenType substitutions and positioning happen on the glyph level. Principally, it doesn't matter which codepoints a glyph is invoked through. 

Of course since the OT Layout model relies on per-script shaping engines, reordering happens or certain features are automatically applied in a specific order when glyphs are invoked via their true Unicode codepoints. 

If the same glyphs are invoked via PUA, the shaper probably classifies them as "DFLT" script. Indeed if a PUA codepoint is inserted in the middle of "true" Arabic or Devanagari or even Latin or Cyrillic text, some OTL engines may interpret that single glyph inserted via PUA as a separate run, and then would not execute feature interactions with meighboring glyphs (kern, mark etc.). Which does indeed pose a problem. 

Other engines may fold that glyph into the dominant run and it will work. Inconsistent run itemization and inability to perform positionings or contextual substitutions across run boundaries is indeed a very weak aspect of OTL. 

But if the PUA-invoked glyphs end up to be in the same run, universally applied default features like kern or mark, and any explicitly user specified features, both GSUB and GPOS, will work. 

The pyftfeatfreeze method isn't problematic. It only remaps the "cmap" and typically does so within the same languagesystem, so the new default glyphs (assigned to Unicode codepoints) remain within the same script run, and everything works as it should, unless your features do really weird circular stuff. 

For example, if you have swash Arabic glyphs in the "swsh" feature inside the "arab" languagesystem, these glyphs would normally already partake in the init, medi, fina, isol, curs or mark features in the original font. If you freeze the swsh feature using pyftfeatfreeze, those swash glyphs get mapped as the default Arabic letters in the cmap table, but since they get classified as the Arabic run, are fed into the Arabic shaper and already partake in the "arab" features defined in the font, everything works as expected. 

Freezing "swsh" is sometimes even a **better** method than applying a user defined feature to one character via, say a span with a local style="font-feature-settings: 'swsh'" property, because doing the latter may force a run break (or generally cause the span to be rendered in a separate step), which also stops the interaction with the neighbors -- unless the higher-level text engine is smart enough to detect and ignore certain span changes or somehow fuses the line together before passing it to the OTL engine. 

Again, this is all shit. :)

**Comment by davelab6** [comment]
Khaled, non-OT implementations are TrueType implementations; thus they use
the KERN table. :)

Ken, please see
https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze

**Comment by davelab6** [comment]
On 11 February 2016 at 09:13, Adam Twardoch <notifications@github.com>
wrote:

> If the same glyphs are invoked via PUA, the shaper


Hmm. Do we have concrete examples of implementations that have an OT
shaper, but no UI for users to set/unset non-default features? (I'll ask
Laura on TypeDrawers about this.)

**Comment by twardoch** [comment]
@kenlunde pyftfeatfreeze is a [tool I published](https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze) which e.g. could turn the Source Han Sans superfont that uses the OT features to switch between SC, TC, J and K variants into a series of SC, TC, J and K fonts which all have the appropriate variants mapped in the cmap. In fact, after you published Source Han Sans, I realized that such an approach may no longer as frowned upon as it used to be by some people, and I finished and published the tool (I had a simple working version of it for a long time now).

**Comment by twardoch** [comment]
@davelab Start with Notepad. :) I supports calt (contextual alternates) but gives no way to override its results. Zapfino Extra LT Pro that I made in 2003 shows how this works -- you see substitutions happening as you type but if you finished typing, there is no way to pick another variant. And then virtually every Windows app that uses the standard GDI Windows text controls, any Photoshop clone, older versions of Word or Corel Draw, and tons of simple "add text to image" apps, or apps for vinyl sign cutting or CAD apps or motion graphics/video editing apps or apps that add subtitles or captions etc. All that uses the standard text stack on Windows.

**Comment by davelab6** [comment]
Right. I see why this is a really big problem :angry: 

Looking back at Laura's post on TD, she says that feeding the new hobbyist retail market PUA fonts is increasing their use and appreciation of fonts, that puts pressure on app developers to provide better typography features.... but the example is a glyph picker, not a real OpenType UI. I wonder if any apps have added OT UIs, so I've updated my question to Laura to be about that :)

**Comment by khaledhosny** [comment]
That swash example makes no sense at all, since you usually want to enable it for just part of the word (at least for Arabic), and you can’t do that with a “frozen” font. That is really just another hack suitable for certain fonts. That CSS font-features currently force run breaks is an implementation bug, Firefox, for example, apply many style changes across spans without breaking OpenType logic and it should do that for font features too (since HarfBuzz already support that).

**Comment by khaledhosny** [comment]
@dave I don’t see how kern table can handle all kinds of kerning supported by GPOS pain positioning, nor how it is certain that the kern table will be always supported in these situations.

**Comment by twardoch** [comment]
@khaledhosny Replace "swash" with any other, e.g. one variant letter accessible through ss02 that you want to appear consistently in your text, or a localized form. Though admittedly, pyftfeatfreeze does not currently allow to freeze a feature for only some glyphs.

**Comment by simoncozens** [comment]
I'm going to be dogmatic here and say that encoding stuff in the PUA for general-purpose fonts is a bad idea and if anything we should check that it's *not* happening. I understand that it's a necessarily evil for old applications which don't read the glyph table, but fontbakery is about *best* practices, not bad practices. If anyone still strongly insists that it should happen, feel free to ~fight me~ reopen the issue.
