### ISSUE TITLE
Installing build dependencies … error

### ISSUE THREAD

**Issue by Manoftype** [googlefonts/fontbakery#3893]
While installing FontBakery on Mac Monterey 12.5.1, I received an error when the system was installing opentype-sanitizer-8.2.1. The message was Installing build dependencies … error.
ERROR: Command errored out with exit status 1:

Then further on, when collecting packages for ninja, another error Building wheel for ninja (PEP 517).

Any suggestions or help would be appreciated.

**Comment by simoncozens** [comment]
Without seeing the actual error, it seems likely to be a problem in https://github.com/scikit-build/ninja-python-distributions; I suspect it's [this issue](https://github.com/scikit-build/ninja-python-distributions/issues/81) which has since been fixed in the latest release of the ninja Python wrapper. So it should work now. Please comment if not and I'll reopen and look into it more.
