### ISSUE TITLE
New checks: automated design checks

### ISSUE THREAD

**Issue by twardoch** [googlefonts/fontbakery#3945]
This is a larger-scoped proposal. 

Microsoft has published the Microsoft Character Design Standards, which mostly applies to Latin-script fonts:  

https://learn.microsoft.com/en-us/typography/develop/character-design-standards/ 

This is not a perfect, complete resource, but there could be more resources that we could collect. At least some of these recommendations could be turned into automated checks. 

To realize this well, I think we should establish a separate profile or checks class, and ideally provide a simple library that can be used in the checks that can expose some essential property of any glyph, for VF in requestable design space locations (e.g. neutral and all extrema).

A function could expose a simple-to analyze glyph contour, its extents (bbox), along with sidebearings and some vertical distances between important font metrics & the bounds. 
 
This could use the pen protocol, including easy usage of some pens like the https://github.com/robotools/fontPens/blob/master/Lib/fontPens/marginPen.py

This lib could ideally be able to interact with https://github.com/typesupply/glyph-nanny/ which would allow additional checks.

A great addition to such lib would be some way of autohinting to get a rough structure of a glyph (the stems).

With this kind of toolbox in place, tests could be created easily, without having to duplicate low-level code.

**Comment by davelab6** [comment]
I believe this is out of scope for Fontbakery, which is scoped to "technical, sfnt data" checks; but it is the scope of https://github.com/SorkinType/EQX - 22 minute introduction presentation at ATypI 2020 by Eben Sorkin: [youtu.be/L61M-rU43ec](https://youtu.be/L61M-rU43ec)

**Comment by EbenSorkin** [comment]
I had been discussing with Quinn the possibility of making a font, web or book resource with typical ( sans ) pen paths/heartlines and a set of pen overlays on them + known alternative skeletons. A plug in might be a nice way to go as well. Glyphs offer greyed-out references before you design a glyph which is cool but it is just one style and low contrast. I think FL probably does this too - no?

If someone made this it would not offer the same function as EQX. EQX  is for tracking and discussion of implementation between designers,managers and their experts ( and contains sets of interrogatory questions relevant to tracking progress ). However, it would be a way to see what different pens and their weight and contrast (or lack of contrast) might result in for unfamiliar letters and or for alternative construction of letters. 

In some ways it might be an ideal way of very rapidly giving styles to underserved scripts (like Adlam?). Or if not, it could be quite useful for providing examples to push a dialog about what design spaces are culturally worth exploring for those scripts, and what design issues need a type designer to resolve ( If someone was doing this for Latin the '&' would immediately be a recognizable problem). When I made a hyper-black set of Adlam numbers it kind of blew the minds of the Barry brothers. That really opened my eyes.

Anticipatable problems might include: 
• What counts as as an alternative construction? For capital A there are so many possibilities alone. LOL But regional/cultural differences for a given unicode code point would have to be dealt with.
• Some features of the extended or Global Latin need careful handling that a heavy weight pen doesn't offer such as : ⱥ ȡ ƙ ⱴ ƶ Ɣ.
• Serifs and other terminal types seem important and unless a mechanism exists to indicate what terminates as a serif or a tail of j or a hook/f termival or the resource could be misleading at times.

There was a cool project to extract heartlines that Lasse was doing ( my t shirt for that project has since died!) I wonder what the state of the art of that is now. 

Others seem to have been thinking about similar stuff: http://jips-k.org/full-text/532

**Comment by davelab6** [comment]
Metapolator.com was the project; @simoncozens has recently been looking at heart line derivativation

**Comment by simoncozens** [comment]
> I believe this is out of scope for Fontbakery,

I agree!
