### ISSUE TITLE
[:com.google.fonts/check/contour_count>] Warn for SoftHyphen is always reported, even when correct

### ISSUE THREAD

**Issue by glenda-tn** [googlefonts/fontbakery#4046]
## Observed behaviour

If there is NO contour in u00AD, softhyphen the warn is still reported. But this IS the expected behavior. What appears is both a Warn and PASS. In the toggle line, it appears as a warn when it should be a pass
![Screen Shot 2023-02-02 at 3 14 12 PM](https://user-images.githubusercontent.com/93950887/216472335-bdef29f5-feb8-4c18-9136-fd4243b46bbc.png)

> ⚠️ WARN
> This font has a 'Soft Hyphen' character (codepoint 0x00AD) which is supposed to be zero-width and invisible, and is used to mark a hyphenation possibility within a word in the absence of or overriding dictionary hyphenation. It is mostly an obsolete mechanism now, and the character is only included in fonts for legacy codepage coverage. [code: softhyphen]
> 
> ✅ PASS
> All glyphs have the recommended amount of contours

## Expected behaviour

The WARN should only appear if there is >0 contours in u00AD.
No WARN should appear when expected behavior is correct (i.e. no contour, zero width).

Note: If it is still a question to some whether or not an outline should appear, [Unicode 15](https://www.unicode.org/reports/tr14/tr14-49.html#SoftHyphen) was updated to clarify this.

> Unlike U+2010 HYPHEN, which always has a visible rendition, the character U+00AD SOFT HYPHEN (SHY) is an invisible format character that merely indicates a preferred intraword line break position. If the line is broken at that point, then whatever mechanism is appropriate for intraword line breaks should be invoked, just as if the line break had been triggered by another hyphenation mechanism, such as a dictionary lookup. Depending on the language and the word, that may produce different visible results…

**Comment by felipesanches** [comment]
I believe that the WARN is good since it is highlighting an aspect of the font to be taken into consideration, but not necessarily a problem to be fixed. I think we should keep the warning message, as it may be useful for other users to think about.

You may have gotten the impression that the warning message was related to the number of contours. But that's not the case. The warning is about the mere presence of the soft hyphen. Maybe the wording could be improved to avoid such confusion.

The original conversation that led to the inclusion of this WARN is here: https://github.com/googlefonts/fontbakery/issues/3486

**Comment by felipesanches** [comment]
Or, perhaps, I should move this WARN into an entirely new check. This would at least decouple it from the validation of number of contours, which may help in avoiding the confusion.

**Comment by glenda-tn** [comment]
I agree that it would be clearer if moved to a new check. At this point it is unrelated to the contour count. The Warns after the toggle arrow make users have to open it to see a list but it becomes a waste of time if the font actually passes the check.
