### ISSUE TITLE
[caretslope-mismatch] check is too strict

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#4076]
Just testing the caret rise / run check. 

🔥 FAIL hhea.caretSlopeRise and hhea.caretSlopeRun do not match with post.italicAngle. Got: caretSlopeRise 1000 and caretSlopeRun 176 Expected: caretSlopeRise 2000 and caretSlopeRun 346 [code: caretslope-mismatch]

Glyphs app is giving: 2000 / 352 
Fontmake: 1000 / 176 
Fontbakery: 2000 / 346 

I think they do all match 10° italic angle. But I am very lame with angle calculation stuff.

Since there are differences according to compilers to how caret slope/run is calculated, and differences in rounding, maybe the check should fail on a broader level such as:

- if font is italic and caretRise/caretRun = 1, then fail and give possible values
- if font is italic and caretRise/caretRun *result* is almost matching, then PASS

I may have say something stupid, but I hope the intention is transmitted correctly.

cc @yanone

**Comment by yanone** [comment]
Could you please post a font where you see the seemingly faulty Fontbakery FAIL and also state which version of Fontbakery you're using? Because that new check initially used to have a mistake in the calculation which later got found and corrected.

**Comment by RosaWagner** [comment]
version 0.8.11b0
https://github.com/Etcetera-Type-Co/Anybody

**Comment by yanone** [comment]
The ratio of _rise_ to _run_ is identical in the first two numbers given (Glyphs & Fontmake), only Fontbakery’s calculation is wrong.

If you update to the latest release of Fontbakery from last week (0.8.11), the FAIL is gone just like I hoped. Your Fontbakery has the outdated calculation that causes a FAIL.

The check allows for a 0.1° tolerance before complaining, in case someone got their calculations off by just a little bit. This should be enough to accommodate common rounding differences and has worked well since. I propose that we close this and revisit it again once we run into problems.

**Comment by RosaWagner** [comment]
perfect thank you! closing then.
