### ISSUE TITLE
Read install_requires in setup.py from requirements.txt

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontbakery#4148]
The `install_requires` in `setup.py` and `requirements.txt` are out of sync. My guess is that `requirements.txt` is always up-to-date and `setup.py` gets forgotten.

It would be nice to read `requirements.txt` into the `install_requires` variable in `setup.py`, which to my knowledge is common conduct.

I can prepare a PR if that's desired.

**Comment by miguelsousa** [comment]
That's definitely not desirable. You need to think of requirements.txt as the list of dependencies needed to run the tests, whereas setup.py specifies the dependencies needed to run the tool.

**Comment by anthrotype** [comment]
> read requirements.txt into the install_requires

don't 

https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#requirements-files

**Comment by felipesanches** [comment]
* `requirements.txt` have specific version used during development and for code-testing
* `setup.py` has the minimum requirements to be able to run the program. In general, versions are not specified unless there's a know bug or API change that the program has to work-around or comply with

**Comment by anthrotype** [comment]
if you really don't want to repeat yourself, and can live with the occasional breakage whenever some dependency gets updated, then you can only have install_requires but do not ever use exact pinned `==` versions inside install_requires otherwise installing fontbakery in the same environment alongside other python modules that require different (yet compatible) versions of the same module becomes impossible.

**Comment by anthrotype** [comment]
without concrete requirements.txt, the tests are run using whatever is the latest compatible version on pypi at the time the tests are run, which may be desirable from some point of view (some prefer to know earlier rather than later when it's too late and some user has been caught with that; in picosvg/nanoemoji we had long discussions with Rod about this and in the end I surrendered to this view, but I always get annoyed whenever I'm working on some feature in a PR and suddenly tests start failing for something completely unrelated.. Ok sorry for the detour)

**Comment by anthrotype** [comment]
I know Felipe closed this but very last one, I recommend you set up things like [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) or PyUP to automatically and periodically check for dependency updates, if you haven't already; you know what I mean, the bot opens a PR bumping each dep in the requirements.txt and if the test fails you know there's a problem

**Comment by miguelsousa** [comment]
[Renovate](https://github.com/apps/renovate) is even better, I think.
