### ISSUE TITLE
[web] Fix 404ing

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#611]
The web app should be fixed to prevent these spurious 404 messages:

<img width="1683" alt="screen shot 2016-01-08 at 13 54 00" src="https://cloud.githubusercontent.com/assets/261579/12206500/53233494-b60f-11e5-9285-e7f6c486d095.png">

- [ ] `404 - Not Found: //rawgit.com/felipesanches/scope-one/gh-pages/METADATA.new.json`

I think the build process might now create `METADATA.json.new` files? 

In any case, the file not existing is to be expected, since only the `METADATA.new` was created in the build process (as far as I can see in https://github.com/felipesanches/scope-one/tree/gh-pages)

A 2nd METADATA files was only useful for the http://googlefonts.github.io/fontbakery/#/felipesanches/scope-one/metadata page. So when it is not found, the web app should not throw an error, and on that page then simply only the `METADATA.json` should be shown. 

- [x] `404 - Not Found: ng-table/pager.html`

I don't know what this is about...

- [x] https://rawgit.com/felipesanches/scope-one/gh-pages/METADATA.json exists, so I also don't know why that 404'd

**Comment by felipesanches** [comment]
I'm investigating this one now...

**Comment by felipesanches** [comment]
When METADATA{.new}.json exists the 404 do not show up anymore. The issue is that we need to generate those JSON files frm Protobufs now.

Regarding the ng-table/pager.html , that is the template for the angular pagination widget. I'm not sure why we lack this file. It should come bundled with ng-table and thus I guess it would be available in the bower_components directory ?

I see that in our case pagination is disabled, so we should not really need this template. Though, there's a bug in the angular ng-table library related to this. There's some interesting insight on that (other people having the same problem of an HTTP request even when the template is not needed) here: https://github.com/esvit/ng-table/issues/338

**Comment by felipesanches** [comment]
And also here: https://github.com/esvit/ng-table/issues/6

In particular this comment seems pretty much relevant in our case: https://github.com/esvit/ng-table/issues/6#issuecomment-51468016

**Comment by davelab6** [comment]
Well, if we don't use it, we can just put a 0 byte file at that URL and
file an issue to fix it properly later - if at all.

I dont really like the idea of converting the PB to JSON. Just read the PB
file. I mean, its plain text, you could probably write your own parser in
less time than to integrate a library ;)

**Comment by felipesanches** [comment]
Regarding ng-table/pager.html 404:

One of my suspicions is that this may simply be a broken deploy of ng-table, as the template files are unavailable in our fontbakery gh-pages branch, while I can see the template files in the ng-table git repo here: https://github.com/esvit/ng-table/tree/master/src/ng-table

Maybe the template files should have been commited to our git repo as well? I see the ng-table files (mostly css and js) are in bower_components directory. Is this an issue with our bower setup? Does bower typically ship the template files as well? Maybe a previous developer forgot to commit the template files?

**Comment by davelab6** [comment]
Could be any of these things. Comment it out where it is used, and file an
issue to return to it?

**Comment by felipesanches** [comment]
well... it is used **everywhere** ! :-)

For all of the forms containing test results, metadata tests etc...

**Comment by felipesanches** [comment]
It seems to be a core widget in our web UI.

**Comment by felipesanches** [comment]
Alright! I got good news! :-D

I was bashing my head against the wall today trying to undertand what was wrong with ng-tables and now I figured out that the spurious 404 errors are caused by bad behaviour induced into the ng-tables module due to the failure to load the metadata/tests.json file from CoinyTests gh-pages. So it was very misleading.

So, there are 2 immediate conclusions here:
- [ ] We need to check why fontbakery did not automaticaly generate and commit metadata/tests.json into CoinyTests gh-pages
- [ ] ng-tables should be more robust and spit out a more meaningful error message. Maybe something like: "the table's data-set is void or coudn't be loaded".

**Comment by davelab6** [comment]
Great! Yes, please hammer on both in that order :)

**Comment by felipesanches** [comment]
Thanks for your patience, Dave!

I'll tackle both of these now :-)

**Comment by felipesanches** [comment]
gotcha!

https://travis-ci.org/felipesanches/CoinyTests#L1939-L1946

**Comment by davelab6** [comment]
Nice!

**Comment by felipesanches** [comment]
we have only a couple issues with 404 errors:

- [ ] In the "Setup" tab we get: "404 - Not Found: //rawgit.com/felipesanches/CoinyTests/gh-pages/build_info/data/pages/bakery-yaml/bakery_yaml.json"
- [ ] the webapp still requires both METADATA.pb and METADATA.new.pb to be available (otherwise it still misbehaves).

**Comment by davelab6** [comment]
Please keep hammering :)

**Comment by felipesanches** [comment]
I simply got rid of error logs in the UI since they are disruptive for demos, but not catastrophic for the whole app. I'll open an individual issue for actually fixing the missing bakery_yaml.json file.

https://github.com/googlefonts/fontbakery/commit/d0877cf98e9011210b5e9340b2a8f36e2e22f209
