### ISSUE TITLE
Integrate source-foundry/font-tests

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#652]
Integrate @chrissimpkins https://github.com/source-foundry/font-tests where it makes sense

**Comment by felipesanches** [comment]
* **test-glyphnumber.py**: "maxp" checks are already performed by fontforge
* **test-monospace.py**: isFixedPitch is already checked at "Checking if the font is truly monospaced"
* **test-monospace.py**: "advance width settings in [hmtx] table" are already checked at "Monospace font has hhea.advanceWidthMax equal to each glyph's advanceWidth ?"
* **test-version.py**: version strings are already checked at "Checking font version fields"

**Comment by felipesanches** [comment]
Here are the values tested by "test-metrics.py" (the ones with checkmarks already have checks in fontbakery):

# [head] table
- [ ] unitsPerEm

# [hhea] table
- [ ] descent
- [ ] ascent
- [ ] lineGap

# [OS/2] table
- [ ] capHeight
- [ ] xHeight
- [ ] typoAscender
- [ ] typoDescender
- [ ] typoLineGap
- [ ] winAscent
- [ ] winDescent
- [ ] strikeoutPosition
- [ ] strikeoutSize
- [ ] averageWidth
- [ ] superscriptXSize
- [ ] superscriptXOffset
- [ ] superscriptYSize
- [ ] superscriptYOffset
- [ ] subscriptXSize
- [ ] subscriptXOffset
- [ ] subscriptYSize
- [ ] subscriptYOffset

# [post] table
- [ ] underlinePosition
- [ ] underlineThickness
- [ ] italicAngle

**Comment by felipesanches** [comment]
Are there reasonable values we would expect to see in these fields? source-foundry/font-tests does check these against values provided by the user upon invokation, instead of expected values infered from other table entries:

# [OS/2] table
* capHeight
* xHeight
* strikeoutPosition
* strikeoutSize
* averageWidth
* superscriptXSize
* superscriptXOffset
* superscriptYSize
* superscriptYOffset
* subscriptXSize
* subscriptXOffset
* subscriptYSize
* subscriptYOffset

# [post] table
* underlinePosition

**Comment by chrissimpkins** [comment]
I believe that most of those will be very typeface dependent.  It might be possible to establish checks against extreme values if your goal is as a general font testing tool.  As I recall our testing tool was built for font specific testing (i.e. our own fonts with known values for each of these parameters).  The goal was to provide us with a way to test each new build for unexpected changes to expected values prior to release. 

@davelab6 thoughts?

**Comment by felipesanches** [comment]
Thanks for the feedback, @chrissimpkins !

Sounds like we've then covered all portions of these checks that make sense for FontBakery. These other ones seem really very dependent on the metrics of each specific typeface, so, there's not really a single reference to check against without explicit user input.

I'd rather not add checks for the extreme value ranges you suggest because we're ideally checking for things we know have become broken in fonts that @davelab6 has dealt with in the past. There's not much point in creating checks for bad things we haven't seen actually happening in at least a few font files. (Unless we consider it to be a problem that is very likely to occur.)

**Comment by chrissimpkins** [comment]
my pleasure! let me know if there is anything else that I can do.
