### ISSUE TITLE
Add an option to the report maker to reformat report output in "GHM" (Github Markdown)

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#727]
At #693 @davelab6 states the need for it. Could you please clarify the meaning of this task, Dave?

```
[backticks]
Coiny-Regular2911.ttf
NAMEID 1: "Coiny Regular"
NAMEID 2: "Regular"
NAMEID 4: "Coiny Regular"
NAMEID 6: "Coiny-Regular"
NAMEID 1: "Coiny Regular"
NAMEID 2: "Regular"
NAMEID 4: "Coiny Regular"
NAMEID 6: "Coiny-Regular"
NAMEID 16: "Coiny"
NAMEID 17: "Regular"
NAMEID 18: "Coiny Regular"
[backticks]
```

**Comment by davelab6** [comment]
An idea is to be able to have the checker output in GHM, so that it can be posted as-is as an issue on the developer's font repo issue tracker, and the source level resolution could be done by the developer. 

This GHM style output was only partially implemented in a few checks I think. 

Perhaps the checkers should be using the python std lib Logging module, and then outputting the log in various formats is easier.

**Comment by davelab6** [comment]
I'll review this

**Comment by felipesanches** [comment]
Recently I added the --ghm command line option that generates a full report in GitHub Markdown.
