### ISSUE TITLE
Port Mekkablue Preflight Checks to fontTools

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#735]
https://github.com/mekkablue/Glyphs-Scripts/blob/master/Test/Preflight%20Font.py has some good checks that we should run in a cross platform way

**Comment by felipesanches** [comment]
Not all checks in Mekkablue repo make sense for OpenType binaries, since they are originally targeting Glyphs project files instead:

* **checkForOpenPaths**: does not apply since all glyf table contour data are implicitly closed paths.
* **checkForPathDirections**: I did implement this by calculating the area of the glyphs (with fontTools AreaPen) and checking the numerical sign of the resulting value
* **checkForPointsOutOfBounds**: OK. Straightforward implementation.
* ** checkForIllegalGlyphNames**: Can be split in 3 checks (glyphname uniqueness, valid chars in glyphname and max allowed glyphname length) of which I think fontbakery only still does not check for max glyphname length.
* **checkForFontNames** and **checkStandardNames**: I still have to review these ones but it seems there may be a bit of overlap with existing fontbakery checks (as well as perhaps some checks we don't perform yet).

**Comment by felipesanches** [comment]
In the "check glyphs have unique names" implementation (as commited at https://github.com/felipesanches/fontbakery/commit/f87eff78a35c747af64b82e734e5ff62fe873023 above), I have added a reasonable special case to ignore multiple codepoints mapped to the same name when the name is **'.notdef'**.

Interestingly, this check catches an error in Carlito-Regular:

```
./fontbakery-check-ttf.py ~/Downloads/FONTS/Carlito/Carlito-Regular.ttf --ghm --verbose
[...]
INFO     OK: All glyph paths have correct directions!  
INFO     OK: All glyph paths have coordinates within bounds!  
INFO     OK: All glyphs have unique unicode codepoint assignments.  
ERROR    Glyph name 'uni0000' is attributed to more than a single codepoint: (0x0, 0xfe)  
INFO     OK: All glyphs have a codepoint value assigned.  
INFO     OK: No glyph names exceed max allowed length. 
```

**Comment by felipesanches** [comment]
I consider this issue ready for being closed. The corresponding pull request was just merged into master. Could you please reopen it if you'd like to ask for any further tweaks, @davelab6 ?
