### ISSUE TITLE
Ensure every tool has the same argparse arguments for the same things. 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#830]
https://github.com/googlefonts/fontbakery/blame/9518c59f85031f4904d5b0552730c59e711ac399/BRIEF.md#L24 says that all fontbakery tools will work in a similar/uniform way.

Concretely this means that every tool must have the same argparse arguments for the same things. 

That is currently not the case. 

For example, currently these 2 have `font` and `ttf_font`, and one has a help text and the other does not. 

https://github.com/googlefonts/fontbakery/blob/972da4505839332ff083843bc4e5556fc050109c/fontbakery-fix-ascii-fontmetadata.py#L52

https://github.com/googlefonts/fontbakery/blob/26bf4709c1714025e7c04c2fbb19f868081b5e32/fontbakery-fix-familymetadata.py#L9

In addition to font files as the main required input, the other common optional args will be `autofix` and `verbose`, which (per https://github.com/googlefonts/fontbakery/blame/9518c59f85031f4904d5b0552730c59e711ac399/BRIEF.md#L48) should be required to show the "OK" confirmations. 

To implement this and make sure it stays implemented I suggest that a Test Driven Development approach is required:

- [x] write a test that ensures that each executable tool has the args in an 'expected' list (font, verbose) and there are not any args that are not in an 'optional' list (autofix)
- [x] ensure this test runs via travis on all PRs 
- [x] fix the tools until the test passes

**Comment by davelab6** [comment]
> I only miss the ability to pass -o,--output (or maybe --prefix) to define the prefix of the markdown and JSON output files

Why is shell redirection insufficient for this?

**Comment by felipesanches** [comment]
Alright! There we go! 

https://github.com/googlefonts/fontbakery/commit/514d17de5de19f37eff2777e0066199b71bc8a0f
is an attempt at building the foundations of a command line arguments validator for fontbakery.

I have refactored most scripts so that they adere to a consistent coding style, but I haven't yet modified the set of arguments that each use.

There's also a test_args.py script that we'll likely use on Travis soon.

Next task here is to really consolidate which is the minimal set of mandatory arguments that we want to have accross the whole set of scripts and then adjust that in the checker script.

The checker script has 2 lists:
* mantatory_args
* optional_args

There's a few more info in comments in the patch itself.

**Comment by davelab6** [comment]
I reviewed that commit, looks fine; I think the tests should be added to travis and run via some typical python test runner like nose or whatever

**Comment by felipesanches** [comment]
The tests are already running on Travis, but not with nose or any testing framework. The test_args.py script is simply invoked via .travis.yaml setup.

**Comment by felipesanches** [comment]
Regarding testing, maybe fontbakery as a whole could benefit from a testing framework at some point, but that's not a top priority at the moment.

**Comment by felipesanches** [comment]
@davelab6 do you want to change the set of command line attributes used in each of the tools? Or are you already familiar with the way the commands work thus preferring to keeping them with the current command "signature" ?
