### ISSUE TITLE
Adopt Google Python Style

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#838]
At some point we should update the codebase to https://google.github.io/styleguide/pyguide.html - starting with the things that don't conflict with pep8

----
Update authored by @felipesanches on 2017 March 17:

This is the list of pylint errors/warnings that I will not fix:
* invalid-name '''Reason''': it dislikes short-names like '''f''', '''font''', etc that we use extensively throughout the codebase and I feel it is pointless to change that.
* bad-indentation '''Reason''': I do prefer 2-space indentation and I'll keep the codebase that way for now.

This is the list of issues I'll likely fix gradually (one at a time):
- [x] unused-variable
- [x] import-error
- [ ] fixme
- [ ] missing-docstring
- [x] redefined-outer-name
- [ ] too-many-locals
- [x] assignment-from-no-return
- [ ] too-many-branches
- [ ] too-many-statements
- [ ] bad-continuation
- [ ] unidiomatic-typecheck
- [ ] logging-format-interpolation
- [ ] too-many-nested-blocks
- [ ] superfluous-parens
- [ ] bare-except
- [ ] undefined-loop-variable
- [ ] too-many-instance-attributes
- [ ] old-style-class
- [ ] unnecessary-pass
- [ ] unused-argument
- [ ] consider-iterating-dictionary
- [ ] attribute-defined-outside-init
- [ ] too-many-boolean-expressions
- [ ] too-many-arguments
- [ ] wrong-import-order
- [ ] bad-whitespace
- [ ] pointless-string-statement
- [ ] pointless-statement
- [ ] redefined-builtin
- [ ] global-statement
- [ ] too-many-lines
- [ ] global-variable-undefined
- [ ] redefined-variable-type
- [ ] multiple-statements
- [ ] expression-not-assigned
- [ ] too-many-format-args
- [ ] deprecated-lambda
- [ ] broad-except
- [ ] no-self-use
- [ ] no-name-in-module
- [x] unused-import
- [ ] abstract-method
- [ ] no-member
- [ ] line-too-long
- [ ] trailing-newlines
- [ ] duplicate-code
- [ ] redefined-outer-name
- [ ] trailing-whitespace
- [ ] unused-variable
- [ ] logging-not-lazy
- [ ] undefined-variable
- [ ] protected-access
- [ ] anomalous-backslash-in-string
- [ ] wrong-import-position
- [ ] ungrouped-imports
- [ ] singleton-comparison
- [x] reimported
- [ ] misplaced-comparison-constant
- [ ] consider-using-enumerate
- [ ] used-before-assignment
- [ ] too-few-public-methods
- [x] multiple-imports
- [ ] dangerous-default-value
- [ ] unexpected-keyword-arg
- [x] import-error

**Comment by vmesel** [comment]
@felipesanches and @davelab6 why we don't try to use Google Linter for Python called YAPF? This maybe the solution to this item!

**Comment by davelab6** [comment]
@vmesel cool, I didn't know of that linter; how many errors does it report? :)

**Comment by vmesel** [comment]
I read some more details and its not actually a linter, it is a pep8 formatter. It gets your code and format for pep8.

**Comment by davelab6** [comment]
Such tools are useful for passing flake8 (https://github.com/googlefonts/fontbakery/blob/e3378ebf8b327c7ac15be2c78844357ba549e538/.travis.yml#L30)

**Comment by felipesanches** [comment]
@davelab6 Those specific flake8 errors are being explicitely ignored not because we're unable to fix them, but because at some point I decided that my codestyle is better than what flake8 expects to see in those particular cases.

**Comment by vmesel** [comment]
@felipesanches so why we dont create a new coding style, so we can get a pattern and a linter for checking the code?

**Comment by felipesanches** [comment]
@vmesel For the current code style, flake8 with those few specific --ignores does the job already.

What this issue is really about is adapting our codebase to a Google Python coding style. Not sure if there's any real technical benefit in doing it by itself. But given that FontBakery is a useful tool for people working on the Google Fonts project, I think it can be reasonable to have a codestyle that is more familiar to Google engineers.

**Comment by davelab6** [comment]
> I decided that my codestyle is better than what flake8 expects to see in those particular cases.

I would prefer no exceptions to pep8 but this is such a low priority thing I even wonder about just closing this issue :)

**Comment by felipesanches** [comment]
@davelab6 I am not working on this, precisely because it is extremely low-priority, but this issue could be a good task for @vmesel if he's interested in submitting a pull request.

**Comment by vmesel** [comment]
@felipesanches and @davelab6 do you know any linter for the Google Python Code Style?

**Comment by davelab6** [comment]
Nope

**Comment by davelab6** [comment]
@felipesanches I made this your top item in the 0.2.0 milestone ;)

**Comment by felipesanches** [comment]
I did run pylint on the fontbakery-check-ttf.py script and noticed that it complains about the 2 spaces indentation style I use. That's something I won't change at all. At least not now, as I truly prefer 2-space indentation over 4, or even 8. So, in order to ignore those, I figure one can run this:

pylint --disable=bad-indentation fontbakery-check-ttf.py

And the result is just a minimal set of issues:

```
************* Module fontbakery-check-ttf
W:127, 0: TODO: Not sure why these are disabled. I need to review this. (fixme)
C:  1, 0: Invalid module name "fontbakery-check-ttf" (invalid-name)
C:  1, 0: Missing module docstring (missing-docstring)
W: 32,25: Redefining name 'config' from outer scope (line 496) (redefined-outer-name)
R: 32, 0: Too many local variables (50/15) (too-many-locals)
C: 34, 2: Invalid variable name "fb" (invalid-name)
C:146,10: Invalid variable name "f" (invalid-name)
C:299, 4: Invalid variable name "is_listed_in_GFD" (invalid-name)
C:319, 8: Invalid variable name "is_listed_in_GFD" (invalid-name)
E:333, 8: Assigning to function call which doesn't return (assignment-from-no-return)
C:336,12: Invalid variable name "f" (invalid-name)
E:336,17: Instance of 'FamilyProto' has no 'fonts' member (no-member)
E:400,66: Instance of 'FamilyProto' has no 'name' member (but some types could not be inferred) (maybe-no-member)
W:407, 8: Unused variable 'remote_family' (unused-variable)
R: 32, 0: Too many branches (49/12) (too-many-branches)
R: 32, 0: Too many statements (248/50) (too-many-statements)
C:479, 0: Invalid constant name "parser" (invalid-name)
C:495, 2: Invalid constant name "args" (invalid-name)
C:496, 2: Invalid constant name "config" (invalid-name)

Global evaluation
-----------------
Your code has been rated at 8.85/10
```

I also dislike all of the invalid-name errors, so I would add it to the ignore list as well.

**Comment by felipesanches** [comment]
OK. By also ignoring invalid-name convention warnings, this is what I (supposedly) really gotta do for the check-ttf script:

```
************* Module fontbakery-check-ttf
W:127, 0: TODO: Not sure why these are disabled. I need to review this. (fixme)
C:  1, 0: Missing module docstring (missing-docstring)
W: 32,25: Redefining name 'config' from outer scope (line 496) (redefined-outer-name)
R: 32, 0: Too many local variables (50/15) (too-many-locals)
E:333, 8: Assigning to function call which doesn't return (assignment-from-no-return)
E:336,17: Instance of 'FamilyProto' has no 'fonts' member (no-member)
E:400,66: Instance of 'FamilyProto' has no 'name' member (but some types could not be inferred) (maybe-no-member)
W:407, 8: Unused variable 'remote_family' (unused-variable)
R: 32, 0: Too many branches (49/12) (too-many-branches)
R: 32, 0: Too many statements (248/50) (too-many-statements)

Global evaluation
-----------------
Your code has been rated at 9.19/10
```

**Comment by felipesanches** [comment]
OK. I removed flake8 and replaced it by pylint with a whole bunch of ignore statements. I've updated the description of this issue above to list each of the ignores and then gradually remove the ignores and fix them.

**Comment by davelab6** [comment]
@behdad do you have preferences for this?

**Comment by felipesanches** [comment]
@vmesel (or really anyone else interested in helping with small/quick chunks of code) There's plenty of low-hanging-fruit style work do be done here, if you feel like contributing. Take a look at the previous commits and you'll see a pattern:

* remove (on .travis.yml) a single pylint check from the list of ignored ones
* run it locally to see where that check fails with the current code (which script, which line, etc)
* implement fixes to not simply silence the errors/warnings but actually address the root cause for the issue (this is sometimes trivial, and sometimes may require deeper analysis)
* commit it and push
* take a look at the status on Travis to make sure the build continues green (that means the specific pylint issue was indeed properly fixed)
* check the corresponding check-mark at the top-comment in this issue.
* move on to the next pylint issue (it doesn't have to be done in order at all, choose anyone you feel like working on!)

This should work for the vast majority of the currently ignored pylint checks. For a few though, we may prefer to decide that we don't want to adhere at all. This is the case at the moment for the indentation style we use, for instance. These checks are listed in the WONT_FIX environment variable on the .travis.yml file.

There's a lot of stuff here and I acknowledge that it will likely lead to code quality improvements. But I think my time is better spent on other fontbakery issues at the moment. Also, it seems that now the setup is done and the problem is well described and pretty much ideal for external contributors who may be interested in helping the project. So I'll leave it as an ongoing effort open to whoever may be interested in helping with.

**Comment by felipesanches** [comment]
'''Note:''' The Travis automated checks will only run if you have an open pull request. So, you'll need to do open a pull request after the first commit you push. And then you can continue pushing to the same feature_branch until I decide to merge your contributions. Then a new pull request will be needed in case you feel like continue sending more contributions.

Travis automated checks show up at https://travis-ci.org/googlefonts/fontbakery/pull_requests

**Comment by felipesanches** [comment]
alright :-)

**Comment by felipesanches** [comment]
OK. I'll work a bit more today on this one before moving on to other issues.

**Comment by behdad** [comment]
> @behdad do you have preferences for this?

I couldn't care any less.

**Comment by behdad** [comment]
I suggest others not waste their time on this either.

**Comment by felipesanches** [comment]
Thanks for pointing that out, @behdad I'll move on then.

I gotta point out, though, that at least one bug was detected and fixed last Friday due to the above code changes guided by pylint warnings. So it is not really wasted time if some external contributors may want to put the effort. For that reason, I'll restrain from dealing with this issue now, but I'll keep it open.

Does it sound good, @davelab6 ?

**Comment by davelab6** [comment]
Sounds good.

**Comment by behdad** [comment]
I never said lint is not useful.  Linting to detect bugs is very good practice. Changing existing code for the sake of conforming to a stylesheet is waste of resources, in particular when there's so much font-related code that needs to be written...

**Comment by davelab6** [comment]
The intent is for the code here to be used in google3

**Comment by felipesanches** [comment]
Yep! I agree with both @davelab6's and @behdad's respective last comments here :-)

**Comment by felipesanches** [comment]
> I never said lint is not useful. Linting to detect bugs is very good practice. Changing existing code for the sake of conforming to a stylesheet is waste of resources, in particular when there's so much font-related code that needs to be written...

Actually, an idea similar to that one was also expressed by myself on a google-fonts mailing list message a few days ago, where I said:

"It is not a matter of simply shutting down warnings and errors, but instead an exercise on understanding why the lint-check exists at all and how to effectively improve the code quality by adhering in non-hacky manners."

**Comment by behdad** [comment]
> The intent is for the code here to be used in the GF API onboarding process

Still. Not a requirement. Third-party code doesn't have to comply with Google coding style.

**Comment by davelab6** [comment]
@graphicore @felipesanches @m4rc1e do any of you want to keep open or close this issue? 

Behdad makes a compelling case that we can forget this, if you all agree :)

**Comment by felipesanches** [comment]
yes, we can forget it!

**Comment by madig** [comment]
I'd put the errors/flags we (don't) want into `setup.cfg`, so flake8 and pylint pick them up as you edit the source.
