### ISSUE TITLE
GPOS kerning check does not handle extension lookups

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#844]
With https://github.com/khaledhosny/mada, I get:
```
ERROR    GPOS table seems to be corrupted.  
```
But the font includes pair positioning lookups, I think that is because it is failing to account for extension lookups in https://github.com/googlefonts/fontbakery/blob/master/fontbakery-check-ttf.py#L1976.

**Comment by davelab6** [comment]
(Its better to link to a specific commit's line number than the master's line number, because as the file changes, the link gets stale. I believe a good 'static' link to this code is https://github.com/googlefonts/fontbakery/blob/ced628d4af8b7db22f9bc348efd46721fddaeedb/fontbakery-check-ttf.py#L2037-L2038 :) 

@felipesanches do you understand how to fix this? If no, we will need to postpone it.

**Comment by felipesanches** [comment]
With current fontbakery and with the TTF files downloaded from the Mada-1.2 release on GitHub, I actually get the other error message:

```
ERROR    GPOS table lacks kerning information
```

@khaledhosny Could you, please, point me to the place where I can download the TTF files that result in the "corrupted" error message?

**Comment by khaledhosny** [comment]
I don’t get the GPOS is corrupt error any more, but the error about kerning is still wrong since the has pair positioning lookup in a kern feature.

**Comment by felipesanches** [comment]
lookup.LookupType values in the Mada-Bold.ttf font file are: 1, 4, 6 and 9

These values correspond to:
* 1 - Single Adjustment
* 4 - MarkToBase attachment
* 6 - MarkToMark attachment
* 9 - Extension Positioning

Current fontbakery code is only dealing with lookup type 2 (Pair Adjustment)

**Comment by davelab6** [comment]
Then, the message should be INFO level and be more verbose to explain these values.

**Comment by khaledhosny** [comment]
Yes, and that is the bug I’m reporting. Extension lookup type 9 can store any other lookup, it is just mechanism to split too big lookups, which are often pair pos lookups.

**Comment by felipesanches** [comment]
The buggy check is described as "Does GPOS table have kerning information?"

It first checks whether a specific lookup type (2 = Pair Adjustment) is available in the table. Should we look for any of 1, 4, 6 and 9 as well? Or should we look for any value between 1 and 9 ?

The other conditionals within this check are validating whether the type 2 table is not corrupt. Did we ever deal with corrupt type 2 lookups? I don't see the point of checking for something if we never really faced bad instances in the wild. I think I'll simply comment out all of this type 2 specific validation and keep the check simple. It's purpose should be to simply guarantee that *some* kerning info is available in the font file, right?

**Comment by khaledhosny** [comment]
See https://www.microsoft.com/typography/otspec/gpos.htm#EP

**Comment by felipesanches** [comment]
I'll merge https://github.com/felipesanches/fontbakery/commit/3375f935474c9d9b03010559c911f50488b86445 into master

It takes into account extension type, so Mada is expected to pass the check (I tried here and it does indeed). The code changes in that commit only checks for the presence of lookup type 2 or lookup type 9 referencing extensionLookupType 2 on its subtables. It seems that's enough.

If that's enough, then we may close this issue. Otherwise, please let me know if this still needs further improvement.

**Comment by felipesanches** [comment]
I think it is more likely than not that this is a good fix to the issue, so, @khaledhosny please reopen the issue if you think we need any further improvement in this check.

**Comment by khaledhosny** [comment]
Seems good for my needs.
