### ISSUE TITLE
Conflicting requiremnts for usWeightClass

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#880]
usWeightClass for ExtraLight is required to be 275:
```
ERROR    OS/2 usWeightClass Changes that must be applied to this font: OS/2 usWeightClass from 200 to 275
```

Yet setting it to this value gives another error:
```
ERROR    Font fails to follow some family naming recommendations: [{'field': 'OS/2 usWeightClass', 'error': 'Value has to be in steps of 50.'}]
```

**Comment by felipesanches** [comment]
The spec lists values for usWeightClass that are multiples of 100 here:
https://www.microsoft.com/typography/otspec/os2.htm#wtc

And in the spec ExtraLight is supposed to have a value of 200 instead of 275.

But Dave opened an issue at a font project asking for a value change from 250 to 275 at https://github.com/etunni/Changa/issues/5

Can you clarify that, please, @davelab6  ?

**Comment by davelab6** [comment]
The step 50 check should be info level only

**Comment by felipesanches** [comment]
OK, so a value of 275 is valid even though discouraged ?

**Comment by davelab6** [comment]
I forget what the issue with non 50 values is but 275 is what I want

**Comment by felipesanches** [comment]
We need to figure it out then. 

This seems to be directly related:
https://bugzilla.mozilla.org/show_bug.cgi?id=931426#c34

A proper fix requires us to better understand the root of the problem.

**Comment by felipesanches** [comment]
Also this one:
https://lists.w3.org/Archives/Public/www-style/2010Sep/0463.html

**Comment by davelab6** [comment]
The issue is with style linking on old proprietary software.
